# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//about.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(650, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(About.sizePolicy().hasHeightForWidth())
        About.setSizePolicy(sizePolicy)
        About.setMinimumSize(QtCore.QSize(650, 600))
        About.setMaximumSize(QtCore.QSize(650, 600))
        About.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(About)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(About)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(About)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout.addWidget(self.widget_2, 5, 2, 1, 1, QtCore.Qt.AlignRight)
        self.widget = QtWidgets.QWidget(About)
        self.widget.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.editor_logo = QtWidgets.QLabel(self.widget)
        self.editor_logo.setMinimumSize(QtCore.QSize(60, 60))
        self.editor_logo.setMaximumSize(QtCore.QSize(60, 60))
        self.editor_logo.setObjectName("editor_logo")
        self.verticalLayout.addWidget(self.editor_logo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget, 0, 0, 6, 1)
        self.line = QtWidgets.QFrame(About)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 6, 1)
        self.widget_4 = QtWidgets.QWidget(About)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.inforbiomares = QtWidgets.QLabel(self.widget_4)
        self.inforbiomares.setGeometry(QtCore.QRect(70, 10, 101, 71))
        self.inforbiomares.setText("")
        self.inforbiomares.setPixmap(QtGui.QPixmap(":/resourcesFolder/marsw_logos/Inforbiomares-01.png"))
        self.inforbiomares.setScaledContents(True)
        self.inforbiomares.setObjectName("inforbiomares")
        self.marsw = QtWidgets.QLabel(self.widget_4)
        self.marsw.setGeometry(QtCore.QRect(280, 10, 161, 71))
        self.marsw.setText("")
        self.marsw.setPixmap(QtGui.QPixmap(":/resourcesFolder/marsw_logos/MARSW-01.png"))
        self.marsw.setScaledContents(True)
        self.marsw.setObjectName("marsw")
        self.icnf = QtWidgets.QLabel(self.widget_4)
        self.icnf.setGeometry(QtCore.QRect(230, 80, 131, 61))
        self.icnf.setText("")
        self.icnf.setPixmap(QtGui.QPixmap(":/resourcesFolder/marsw_logos/ICNF-01.png"))
        self.icnf.setScaledContents(True)
        self.icnf.setObjectName("icnf")
        self.lpn = QtWidgets.QLabel(self.widget_4)
        self.lpn.setGeometry(QtCore.QRect(380, 80, 101, 61))
        self.lpn.setText("")
        self.lpn.setPixmap(QtGui.QPixmap(":/resourcesFolder/marsw_logos/LPN-01.png"))
        self.lpn.setScaledContents(True)
        self.lpn.setObjectName("lpn")
        self.ccmar = QtWidgets.QLabel(self.widget_4)
        self.ccmar.setGeometry(QtCore.QRect(20, 90, 201, 41))
        self.ccmar.setText("")
        self.ccmar.setPixmap(QtGui.QPixmap(":/resourcesFolder/marsw_logos/CCMAR_UAlg-01.png"))
        self.ccmar.setScaledContents(True)
        self.ccmar.setObjectName("ccmar")
        self.mare = QtWidgets.QLabel(self.widget_4)
        self.mare.setGeometry(QtCore.QRect(190, 140, 101, 51))
        self.mare.setText("")
        self.mare.setPixmap(QtGui.QPixmap(":/resourcesFolder/marsw_logos/MARE-01.png"))
        self.mare.setScaledContents(True)
        self.mare.setObjectName("mare")
        self.uevora = QtWidgets.QLabel(self.widget_4)
        self.uevora.setGeometry(QtCore.QRect(50, 140, 111, 51))
        self.uevora.setText("")
        self.uevora.setPixmap(QtGui.QPixmap(":/resourcesFolder/marsw_logos/UEvora-01.png"))
        self.uevora.setScaledContents(True)
        self.uevora.setObjectName("uevora")
        self.ulisboa = QtWidgets.QLabel(self.widget_4)
        self.ulisboa.setGeometry(QtCore.QRect(330, 140, 111, 51))
        self.ulisboa.setText("")
        self.ulisboa.setPixmap(QtGui.QPixmap(":/resourcesFolder/marsw_logos/ULisboa_Fac_Ciencias-01.png"))
        self.ulisboa.setScaledContents(True)
        self.ulisboa.setObjectName("ulisboa")
        self.gridLayout.addWidget(self.widget_4, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(About)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(About)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout.addWidget(self.widget_3, 3, 2, 1, 1)
        self.version = QtWidgets.QLabel(About)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.version.setFont(font)
        self.version.setTextFormat(QtCore.Qt.RichText)
        self.version.setObjectName("version")
        self.gridLayout.addWidget(self.version, 2, 2, 1, 1)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Editor de metadados SNIMar - Sobre"))
        self.label.setText(_translate("About", "Editor de metadados Marsw Infobiomares"))
        self.pushButton.setText(_translate("About", "Fechar"))
        self.editor_logo.setText(_translate("About", "<img border=\"0\" alt=\"LOGO\" src=\":resourcesFolder/icons/main_icon.png\" width=\"60\" heigth=\"60\">"))
        self.label_6.setText(_translate("About", "<html><head/><body><p>O Editor de Metadados foi desenvolvido no âmbito dos projetos Marsw e Infobiomares com o objectivo de ser a ferramenta destinada à criação dos metadados em conformidade com o Perfil de Metadados SNIMar.</p></body></html>"))
        self.label_3.setText(_translate("About", " <b>Autores:</b><br>\n"
"- Pedro Dias<br>\n"
"- Eduardo Castanho<br>\n"
" <b>Contribuidores: </b><br>\n"
"- Joana Teixeira<br>\n"
"- Alexandre Neto"))
        self.version.setText(_translate("About", "<html><head/><body><p><br/></p></body></html>"))
