# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//chooseLegalRestrictionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 210)
        Dialog.setMinimumSize(QtCore.QSize(530, 210))
        Dialog.setMaximumSize(QtCore.QSize(530, 210))
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 19, 511, 146))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.widget = QtWidgets.QWidget(self.formLayoutWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_line_uselimitations = QtWidgets.QPushButton(self.widget)
        self.info_label_line_uselimitations.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_line_uselimitations.setFlat(True)
        self.info_label_line_uselimitations.setObjectName("info_label_line_uselimitations")
        self.horizontalLayout.addWidget(self.info_label_line_uselimitations)
        self.label_line_uselimitations = QtWidgets.QLabel(self.widget)
        self.label_line_uselimitations.setObjectName("label_line_uselimitations")
        self.horizontalLayout.addWidget(self.label_line_uselimitations)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.widget)
        self.widget1 = QtWidgets.QWidget(self.formLayoutWidget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_combo_accessrestrictions = QtWidgets.QPushButton(self.widget1)
        self.info_label_combo_accessrestrictions.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_combo_accessrestrictions.setFlat(True)
        self.info_label_combo_accessrestrictions.setObjectName("info_label_combo_accessrestrictions")
        self.horizontalLayout1.addWidget(self.info_label_combo_accessrestrictions)
        self.label_combo_accessrestrictions = QtWidgets.QLabel(self.widget1)
        self.label_combo_accessrestrictions.setObjectName("label_combo_accessrestrictions")
        self.horizontalLayout1.addWidget(self.label_combo_accessrestrictions)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.widget1)
        self.widget2 = QtWidgets.QWidget(self.formLayoutWidget)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_combo_userestrictions = QtWidgets.QPushButton(self.widget2)
        self.info_label_combo_userestrictions.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_combo_userestrictions.setFlat(True)
        self.info_label_combo_userestrictions.setObjectName("info_label_combo_userestrictions")
        self.horizontalLayout2.addWidget(self.info_label_combo_userestrictions)
        self.label_combo_userestrictions = QtWidgets.QLabel(self.widget2)
        self.label_combo_userestrictions.setObjectName("label_combo_userestrictions")
        self.horizontalLayout2.addWidget(self.label_combo_userestrictions)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.widget2)
        self.widget3 = QtWidgets.QWidget(self.formLayoutWidget)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_line_otherrestrictions = QtWidgets.QPushButton(self.widget3)
        self.info_label_line_otherrestrictions.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_line_otherrestrictions.setFlat(True)
        self.info_label_line_otherrestrictions.setObjectName("info_label_line_otherrestrictions")
        self.horizontalLayout3.addWidget(self.info_label_line_otherrestrictions)
        self.label_line_otherrestrictions = QtWidgets.QLabel(self.widget3)
        self.label_line_otherrestrictions.setObjectName("label_line_otherrestrictions")
        self.horizontalLayout3.addWidget(self.label_line_otherrestrictions)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.widget3)
        self.line_uselimitations = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_uselimitations.setMinimumSize(QtCore.QSize(0, 30))
        self.line_uselimitations.setObjectName("line_uselimitations")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_uselimitations)
        self.line_otherrestrictions = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_otherrestrictions.setMinimumSize(QtCore.QSize(0, 30))
        self.line_otherrestrictions.setObjectName("line_otherrestrictions")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_otherrestrictions)
        self.combo_accessrestrictions = QtWidgets.QComboBox(self.formLayoutWidget)
        self.combo_accessrestrictions.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_accessrestrictions.setObjectName("combo_accessrestrictions")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_accessrestrictions)
        self.combo_userestrictions = QtWidgets.QComboBox(self.formLayoutWidget)
        self.combo_userestrictions.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_userestrictions.setObjectName("combo_userestrictions")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.combo_userestrictions)
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(190, 170, 96, 30))
        self.btn_cancel.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_add = QtWidgets.QPushButton(Dialog)
        self.btn_add.setGeometry(QtCore.QRect(290, 170, 96, 30))
        self.btn_add.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_add.setAutoDefault(False)
        self.btn_add.setObjectName("btn_add")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Defina as Restrições"))
        self.label_line_uselimitations.setText(_translate("Dialog", "Limitações ao Uso:"))
        self.label_combo_accessrestrictions.setText(_translate("Dialog", "Restrições de Acesso:"))
        self.label_combo_userestrictions.setText(_translate("Dialog", "Restrições de Uso:"))
        self.label_line_otherrestrictions.setText(_translate("Dialog", "Outras Restrições:"))
        self.line_uselimitations.setPlaceholderText(_translate("Dialog", "Limitações..."))
        self.line_otherrestrictions.setPlaceholderText(_translate("Dialog", "outras..."))
        self.btn_cancel.setText(_translate("Dialog", "Cancelar"))
        self.btn_add.setText(_translate("Dialog", "Adicionar"))
