# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//chooseGeographicExtentOnMapDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MDExtentDialogBase(object):
    def setupUi(self, MDExtentDialogBase):
        MDExtentDialogBase.setObjectName("MDExtentDialogBase")
        MDExtentDialogBase.resize(800, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MDExtentDialogBase.sizePolicy().hasHeightForWidth())
        MDExtentDialogBase.setSizePolicy(sizePolicy)
        MDExtentDialogBase.setMinimumSize(QtCore.QSize(800, 550))
        MDExtentDialogBase.setMaximumSize(QtCore.QSize(800, 600))
        self.gridLayout = QtWidgets.QGridLayout(MDExtentDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.add_extent = QtWidgets.QPushButton(MDExtentDialogBase)
        self.add_extent.setMinimumSize(QtCore.QSize(0, 30))
        self.add_extent.setObjectName("add_extent")
        self.gridLayout.addWidget(self.add_extent, 7, 6, 1, 1)
        self.frame = QtWidgets.QWidget(MDExtentDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 7)
        self.widget = QtWidgets.QWidget(MDExtentDialogBase)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_south = QtWidgets.QPushButton(self.widget)
        self.info_label_south.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_south.setFlat(True)
        self.info_label_south.setObjectName("info_label_south")
        self.horizontalLayout.addWidget(self.info_label_south)
        self.label_south = QtWidgets.QLabel(self.widget)
        self.label_south.setObjectName("label_south")
        self.horizontalLayout.addWidget(self.label_south)
        self.gridLayout.addWidget(self.widget, 3, 3, 1, 1)
        self.btn_close = QtWidgets.QPushButton(MDExtentDialogBase)
        self.btn_close.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_close.setObjectName("btn_close")
        self.gridLayout.addWidget(self.btn_close, 7, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(MDExtentDialogBase)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 7)
        self.line = QtWidgets.QFrame(MDExtentDialogBase)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 7)
        self.widget1 = QtWidgets.QWidget(MDExtentDialogBase)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_east = QtWidgets.QPushButton(self.widget1)
        self.info_label_east.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_east.setFlat(True)
        self.info_label_east.setObjectName("info_label_east")
        self.horizontalLayout1.addWidget(self.info_label_east)
        self.label_east = QtWidgets.QLabel(self.widget1)
        self.label_east.setObjectName("label_east")
        self.horizontalLayout1.addWidget(self.label_east)
        self.gridLayout.addWidget(self.widget1, 3, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(MDExtentDialogBase)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_west = QtWidgets.QPushButton(self.widget2)
        self.info_label_west.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_west.setFlat(True)
        self.info_label_west.setObjectName("info_label_west")
        self.horizontalLayout2.addWidget(self.info_label_west)
        self.label_west = QtWidgets.QLabel(self.widget2)
        self.label_west.setObjectName("label_west")
        self.horizontalLayout2.addWidget(self.label_west)
        self.gridLayout.addWidget(self.widget2, 3, 0, 1, 1)
        self.widget3 = QtWidgets.QWidget(MDExtentDialogBase)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.label_2_NOHELP = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2_NOHELP.setFont(font)
        self.label_2_NOHELP.setObjectName("label_2_NOHELP")
        self.horizontalLayout3.addWidget(self.label_2_NOHELP)
        self.gridLayout.addWidget(self.widget3, 2, 0, 1, 1)
        self.widget4 = QtWidgets.QWidget(MDExtentDialogBase)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_north = QtWidgets.QPushButton(self.widget4)
        self.info_label_north.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_north.setFlat(True)
        self.info_label_north.setObjectName("info_label_north")
        self.horizontalLayout4.addWidget(self.info_label_north)
        self.label_north = QtWidgets.QLabel(self.widget4)
        self.label_north.setObjectName("label_north")
        self.horizontalLayout4.addWidget(self.label_north)
        self.gridLayout.addWidget(self.widget4, 3, 2, 1, 1)
        self.resourcebox = QtWidgets.QCheckBox(MDExtentDialogBase)
        self.resourcebox.setObjectName("resourcebox")
        self.gridLayout.addWidget(self.resourcebox, 5, 6, 1, 1)
        self.xMin = QtWidgets.QDoubleSpinBox(MDExtentDialogBase)
        self.xMin.setMinimumSize(QtCore.QSize(98, 30))
        self.xMin.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.xMin.setDecimals(5)
        self.xMin.setMinimum(-180.0)
        self.xMin.setMaximum(180.0)
        self.xMin.setSingleStep(0.0)
        self.xMin.setObjectName("xMin")
        self.gridLayout.addWidget(self.xMin, 5, 0, 1, 1)
        self.xMax = QtWidgets.QDoubleSpinBox(MDExtentDialogBase)
        self.xMax.setMinimumSize(QtCore.QSize(98, 30))
        self.xMax.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.xMax.setDecimals(5)
        self.xMax.setMinimum(-180.0)
        self.xMax.setMaximum(180.0)
        self.xMax.setSingleStep(0.0)
        self.xMax.setObjectName("xMax")
        self.gridLayout.addWidget(self.xMax, 5, 1, 1, 1)
        self.yMax = QtWidgets.QDoubleSpinBox(MDExtentDialogBase)
        self.yMax.setMinimumSize(QtCore.QSize(98, 30))
        self.yMax.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.yMax.setDecimals(5)
        self.yMax.setMinimum(-90.0)
        self.yMax.setMaximum(90.0)
        self.yMax.setSingleStep(0.0)
        self.yMax.setObjectName("yMax")
        self.gridLayout.addWidget(self.yMax, 5, 2, 1, 1)
        self.yMin = QtWidgets.QDoubleSpinBox(MDExtentDialogBase)
        self.yMin.setMinimumSize(QtCore.QSize(98, 30))
        self.yMin.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.yMin.setDecimals(5)
        self.yMin.setMinimum(-90.0)
        self.yMin.setMaximum(90.0)
        self.yMin.setSingleStep(0.0)
        self.yMin.setObjectName("yMin")
        self.gridLayout.addWidget(self.yMin, 5, 3, 1, 1)

        self.retranslateUi(MDExtentDialogBase)
        QtCore.QMetaObject.connectSlotsByName(MDExtentDialogBase)

    def retranslateUi(self, MDExtentDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MDExtentDialogBase.setWindowTitle(_translate("MDExtentDialogBase", "Extensão do Mapa"))
        self.add_extent.setText(_translate("MDExtentDialogBase", "Adicionar"))
        self.label_south.setText(_translate("MDExtentDialogBase", "Limite Sul"))
        self.btn_close.setText(_translate("MDExtentDialogBase", "Fechar"))
        self.label_east.setText(_translate("MDExtentDialogBase", "Limite Este"))
        self.label_west.setText(_translate("MDExtentDialogBase", "Limite Oeste"))
        self.label_2_NOHELP.setText(_translate("MDExtentDialogBase", "Seleção Actual:"))
        self.label_north.setText(_translate("MDExtentDialogBase", "Limite Norte"))
        self.resourcebox.setText(_translate("MDExtentDialogBase", "Contém Recurso"))
