# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//chooseExtentGeographicInformationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(455, 329)
        self.check_haveresources = QtWidgets.QCheckBox(Dialog)
        self.check_haveresources.setGeometry(QtCore.QRect(230, 240, 151, 22))
        self.check_haveresources.setObjectName("check_haveresources")
        self.btn_add = QtWidgets.QPushButton(Dialog)
        self.btn_add.setGeometry(QtCore.QRect(290, 270, 100, 30))
        self.btn_add.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_add.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_add.setAutoDefault(False)
        self.btn_add.setFlat(False)
        self.btn_add.setObjectName("btn_add")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(170, 270, 90, 30))
        self.btn_cancel.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_cancel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 431, 211))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(140, 0, 113, 20))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_spin_north_limit = QtWidgets.QPushButton(self.widget)
        self.info_label_spin_north_limit.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_spin_north_limit.setFlat(True)
        self.info_label_spin_north_limit.setObjectName("info_label_spin_north_limit")
        self.horizontalLayout.addWidget(self.info_label_spin_north_limit)
        self.label_spin_north_limit = QtWidgets.QLabel(self.widget)
        self.label_spin_north_limit.setObjectName("label_spin_north_limit")
        self.horizontalLayout.addWidget(self.label_spin_north_limit)
        self.spin_west_limit = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spin_west_limit.setGeometry(QtCore.QRect(0, 90, 151, 30))
        self.spin_west_limit.setMinimumSize(QtCore.QSize(98, 30))
        self.spin_west_limit.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.spin_west_limit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_west_limit.setDecimals(10)
        self.spin_west_limit.setMinimum(-180.0)
        self.spin_west_limit.setMaximum(180.0)
        self.spin_west_limit.setSingleStep(0.0)
        self.spin_west_limit.setProperty("value", 0.0)
        self.spin_west_limit.setObjectName("spin_west_limit")
        self.spin_north_limit = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spin_north_limit.setGeometry(QtCore.QRect(140, 20, 151, 30))
        self.spin_north_limit.setMinimumSize(QtCore.QSize(98, 30))
        self.spin_north_limit.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.spin_north_limit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_north_limit.setDecimals(10)
        self.spin_north_limit.setMinimum(-90.0)
        self.spin_north_limit.setMaximum(90.0)
        self.spin_north_limit.setSingleStep(0.0)
        self.spin_north_limit.setObjectName("spin_north_limit")
        self.spin_east_limit = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spin_east_limit.setGeometry(QtCore.QRect(270, 90, 151, 30))
        self.spin_east_limit.setMinimumSize(QtCore.QSize(98, 30))
        self.spin_east_limit.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.spin_east_limit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_east_limit.setDecimals(10)
        self.spin_east_limit.setMinimum(-180.0)
        self.spin_east_limit.setMaximum(180.0)
        self.spin_east_limit.setSingleStep(0.0)
        self.spin_east_limit.setProperty("value", 0.0)
        self.spin_east_limit.setObjectName("spin_east_limit")
        self.spin_south_south = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spin_south_south.setGeometry(QtCore.QRect(140, 170, 151, 30))
        self.spin_south_south.setMinimumSize(QtCore.QSize(98, 30))
        self.spin_south_south.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.spin_south_south.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_south_south.setDecimals(10)
        self.spin_south_south.setMinimum(-90.0)
        self.spin_south_south.setMaximum(90.0)
        self.spin_south_south.setSingleStep(0.0)
        self.spin_south_south.setObjectName("spin_south_south")
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(270, 70, 120, 20))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_spin_east_limit = QtWidgets.QPushButton(self.widget1)
        self.info_label_spin_east_limit.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_spin_east_limit.setFlat(True)
        self.info_label_spin_east_limit.setObjectName("info_label_spin_east_limit")
        self.horizontalLayout1.addWidget(self.info_label_spin_east_limit)
        self.label_spin_east_limit = QtWidgets.QLabel(self.widget1)
        self.label_spin_east_limit.setObjectName("label_spin_east_limit")
        self.horizontalLayout1.addWidget(self.label_spin_east_limit)
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(0, 70, 131, 20))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_spin_west_limit = QtWidgets.QPushButton(self.widget2)
        self.info_label_spin_west_limit.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_spin_west_limit.setFlat(True)
        self.info_label_spin_west_limit.setObjectName("info_label_spin_west_limit")
        self.horizontalLayout2.addWidget(self.info_label_spin_west_limit)
        self.label_spin_west_limit = QtWidgets.QLabel(self.widget2)
        self.label_spin_west_limit.setObjectName("label_spin_west_limit")
        self.horizontalLayout2.addWidget(self.label_spin_west_limit)
        self.widget3 = QtWidgets.QWidget(self.groupBox)
        self.widget3.setGeometry(QtCore.QRect(140, 150, 95, 20))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_spin_south_south = QtWidgets.QPushButton(self.widget3)
        self.info_label_spin_south_south.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_spin_south_south.setFlat(True)
        self.info_label_spin_south_south.setObjectName("info_label_spin_south_south")
        self.horizontalLayout3.addWidget(self.info_label_spin_south_south)
        self.label_spin_south_south = QtWidgets.QLabel(self.widget3)
        self.label_spin_south_south.setObjectName("label_spin_south_south")
        self.horizontalLayout3.addWidget(self.label_spin_south_south)
        self.widget4 = QtWidgets.QWidget(self.groupBox)
        self.widget4.setGeometry(QtCore.QRect(0, 0, 77, 20))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_limits = QtWidgets.QPushButton(self.widget4)
        self.info_label_limits.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_limits.setFlat(True)
        self.info_label_limits.setObjectName("info_label_limits")
        self.horizontalLayout4.addWidget(self.info_label_limits)
        self.label_limits = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_limits.setFont(font)
        self.label_limits.setObjectName("label_limits")
        self.horizontalLayout4.addWidget(self.label_limits)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Defina os limites"))
        self.check_haveresources.setText(_translate("Dialog", "Contém Recurso?"))
        self.btn_add.setText(_translate("Dialog", "Adicionar"))
        self.btn_cancel.setText(_translate("Dialog", "Cancelar"))
        self.label_spin_north_limit.setText(_translate("Dialog", "Norte (-90,90)"))
        self.label_spin_east_limit.setText(_translate("Dialog", "Este (-180,180)"))
        self.label_spin_west_limit.setText(_translate("Dialog", "Oeste (-180,180)"))
        self.label_spin_south_south.setText(_translate("Dialog", "Sul (-90,90)"))
        self.label_limits.setText(_translate("Dialog", "Limites:"))
