# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//contactInlinePanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contactWidget(object):
    def setupUi(self, contactWidget):
        contactWidget.setObjectName("contactWidget")
        contactWidget.resize(870, 544)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(contactWidget.sizePolicy().hasHeightForWidth())
        contactWidget.setSizePolicy(sizePolicy)
        contactWidget.setMinimumSize(QtCore.QSize(870, 0))
        self.gridLayout_5 = QtWidgets.QGridLayout(contactWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(contactWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(45, 200))
        self.frame.setMaximumSize(QtCore.QSize(45, 1000))
        self.frame.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_contact_list = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_contact_list.sizePolicy().hasHeightForWidth())
        self.btn_contact_list.setSizePolicy(sizePolicy)
        self.btn_contact_list.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_contact_list.setMaximumSize(QtCore.QSize(0, 0))
        self.btn_contact_list.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.btn_contact_list.setIconSize(QtCore.QSize(28, 28))
        self.btn_contact_list.setObjectName("btn_contact_list")
        self.verticalLayout_3.addWidget(self.btn_contact_list)
        self.btn_addto_list_contacts = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addto_list_contacts.sizePolicy().hasHeightForWidth())
        self.btn_addto_list_contacts.setSizePolicy(sizePolicy)
        self.btn_addto_list_contacts.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_addto_list_contacts.setMaximumSize(QtCore.QSize(0, 0))
        self.btn_addto_list_contacts.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.btn_addto_list_contacts.setIconSize(QtCore.QSize(28, 28))
        self.btn_addto_list_contacts.setObjectName("btn_addto_list_contacts")
        self.verticalLayout_3.addWidget(self.btn_addto_list_contacts)
        self.btn_del_contact = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_contact.sizePolicy().hasHeightForWidth())
        self.btn_del_contact.setSizePolicy(sizePolicy)
        self.btn_del_contact.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_del_contact.setMaximumSize(QtCore.QSize(0, 0))
        self.btn_del_contact.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.btn_del_contact.setIconSize(QtCore.QSize(28, 28))
        self.btn_del_contact.setObjectName("btn_del_contact")
        self.verticalLayout_3.addWidget(self.btn_del_contact)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.mGroupBox = gui.QgsCollapsibleGroupBox(contactWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox.sizePolicy().hasHeightForWidth())
        self.mGroupBox.setSizePolicy(sizePolicy)
        self.mGroupBox.setAccessibleName("")
        self.mGroupBox.setAccessibleDescription("")
        self.mGroupBox.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.mGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mGroupBox.setFlat(False)
        self.mGroupBox.setCollapsed(False)
        self.mGroupBox.setScrollOnExpand(True)
        self.mGroupBox.setSaveCollapsedState(False)
        self.mGroupBox.setSaveCheckedState(False)
        self.mGroupBox.setObjectName("mGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.mGroupBox)
        self.gridLayout_4.setContentsMargins(2, 8, 2, 2)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line = QtWidgets.QFrame(self.mGroupBox)
        self.line.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 7, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.mGroupBox)
        self.widget_2.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_city = QtWidgets.QPushButton(self.widget)
        self.info_label_city.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_city.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_city.setFlat(True)
        self.info_label_city.setObjectName("info_label_city")
        self.horizontalLayout.addWidget(self.info_label_city)
        self.label_city = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_city.sizePolicy().hasHeightForWidth())
        self.label_city.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_city.setFont(font)
        self.label_city.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_city.setObjectName("label_city")
        self.horizontalLayout.addWidget(self.label_city)
        self.horizontalLayout_2.addWidget(self.widget)
        self.city = gui.QgsFilterLineEdit(self.widget_2)
        self.city.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.city.setProperty("qgisRelation", "")
        self.city.setObjectName("city")
        self.horizontalLayout_2.addWidget(self.city)
        self.widget1 = QtWidgets.QWidget(self.widget_2)
        self.widget1.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_postalCode = QtWidgets.QPushButton(self.widget1)
        self.info_label_postalCode.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_postalCode.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_postalCode.setFlat(True)
        self.info_label_postalCode.setObjectName("info_label_postalCode")
        self.horizontalLayout1.addWidget(self.info_label_postalCode)
        self.label_postalCode = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_postalCode.setFont(font)
        self.label_postalCode.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_postalCode.setObjectName("label_postalCode")
        self.horizontalLayout1.addWidget(self.label_postalCode)
        self.horizontalLayout_2.addWidget(self.widget1)
        self.postalCode = gui.QgsFilterLineEdit(self.widget_2)
        self.postalCode.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.postalCode.setProperty("qgisRelation", "")
        self.postalCode.setObjectName("postalCode")
        self.horizontalLayout_2.addWidget(self.postalCode)
        self.gridLayout_4.addWidget(self.widget_2, 5, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.mGroupBox)
        self.widget2.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget2.setObjectName("widget2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.name = gui.QgsFilterLineEdit(self.widget2)
        self.name.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.name.setProperty("qgisRelation", "")
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 1, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.widget2)
        self.widget3.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_name = QtWidgets.QPushButton(self.widget3)
        self.info_label_name.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_name.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_name.setFlat(True)
        self.info_label_name.setObjectName("info_label_name")
        self.horizontalLayout2.addWidget(self.info_label_name)
        self.label_name = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_name.setObjectName("label_name")
        self.horizontalLayout2.addWidget(self.label_name)
        self.gridLayout.addWidget(self.widget3, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget2, 3, 0, 1, 1)
        self.widget_21 = QtWidgets.QWidget(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_21.sizePolicy().hasHeightForWidth())
        self.widget_21.setSizePolicy(sizePolicy)
        self.widget_21.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_6 = QtWidgets.QWidget(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.info_label_role = QtWidgets.QPushButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_label_role.sizePolicy().hasHeightForWidth())
        self.info_label_role.setSizePolicy(sizePolicy)
        self.info_label_role.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_role.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_role.setFlat(True)
        self.info_label_role.setObjectName("info_label_role")
        self.horizontalLayout_4.addWidget(self.info_label_role)
        self.label_role = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_role.sizePolicy().hasHeightForWidth())
        self.label_role.setSizePolicy(sizePolicy)
        self.label_role.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_role.setFont(font)
        self.label_role.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_role.setObjectName("label_role")
        self.horizontalLayout_4.addWidget(self.label_role)
        self.combo_role = QtWidgets.QComboBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_role.sizePolicy().hasHeightForWidth())
        self.combo_role.setSizePolicy(sizePolicy)
        self.combo_role.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.combo_role.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.combo_role.setObjectName("combo_role")
        self.horizontalLayout_4.addWidget(self.combo_role)
        self.horizontalLayout_5.addWidget(self.widget_6)
        self.gridLayout_4.addWidget(self.widget_21, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.mGroupBox)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_outra = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_outra.sizePolicy().hasHeightForWidth())
        self.label_outra.setSizePolicy(sizePolicy)
        self.label_outra.setObjectName("label_outra")
        self.horizontalLayout_3.addWidget(self.label_outra)
        self.organization = gui.QgsFilterLineEdit(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.organization.sizePolicy().hasHeightForWidth())
        self.organization.setSizePolicy(sizePolicy)
        self.organization.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.organization.setFont(font)
        self.organization.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.organization.setProperty("qgisRelation", "")
        self.organization.setObjectName("organization")
        self.horizontalLayout_3.addWidget(self.organization)
        self.gridLayout_4.addWidget(self.widget_5, 2, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(4)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_add_phone = QtWidgets.QPushButton(self.widget_3)
        self.btn_add_phone.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_add_phone.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.btn_add_phone.setAutoDefault(False)
        self.btn_add_phone.setObjectName("btn_add_phone")
        self.gridLayout_3.addWidget(self.btn_add_phone, 3, 1, 1, 1)
        self.widget4 = QtWidgets.QWidget(self.widget_3)
        self.widget4.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_fax = QtWidgets.QPushButton(self.widget4)
        self.info_label_fax.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_fax.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_fax.setFlat(True)
        self.info_label_fax.setObjectName("info_label_fax")
        self.horizontalLayout3.addWidget(self.info_label_fax)
        self.label_fax = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_fax.setFont(font)
        self.label_fax.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_fax.setObjectName("label_fax")
        self.horizontalLayout3.addWidget(self.label_fax)
        self.gridLayout_3.addWidget(self.widget4, 1, 2, 1, 1)
        self.fax = QtWidgets.QListView(self.widget_3)
        self.fax.setMaximumSize(QtCore.QSize(16777215, 75))
        self.fax.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.fax.setObjectName("fax")
        self.gridLayout_3.addWidget(self.fax, 2, 2, 1, 1)
        self.btn_del_phone = QtWidgets.QPushButton(self.widget_3)
        self.btn_del_phone.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_del_phone.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.btn_del_phone.setAutoDefault(False)
        self.btn_del_phone.setObjectName("btn_del_phone")
        self.gridLayout_3.addWidget(self.btn_del_phone, 2, 1, 1, 1)
        self.line_fax = gui.QgsFilterLineEdit(self.widget_3)
        self.line_fax.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.line_fax.setProperty("qgisRelation", "")
        self.line_fax.setObjectName("line_fax")
        self.gridLayout_3.addWidget(self.line_fax, 3, 2, 1, 1)
        self.btn_del_fax = QtWidgets.QPushButton(self.widget_3)
        self.btn_del_fax.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_del_fax.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.btn_del_fax.setAutoDefault(False)
        self.btn_del_fax.setObjectName("btn_del_fax")
        self.gridLayout_3.addWidget(self.btn_del_fax, 2, 3, 1, 1)
        self.line_phone = gui.QgsFilterLineEdit(self.widget_3)
        self.line_phone.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.line_phone.setProperty("qgisRelation", "")
        self.line_phone.setObjectName("line_phone")
        self.gridLayout_3.addWidget(self.line_phone, 3, 0, 1, 1)
        self.btn_add_fax = QtWidgets.QPushButton(self.widget_3)
        self.btn_add_fax.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_add_fax.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_add_fax.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.btn_add_fax.setIconSize(QtCore.QSize(18, 18))
        self.btn_add_fax.setAutoDefault(False)
        self.btn_add_fax.setObjectName("btn_add_fax")
        self.gridLayout_3.addWidget(self.btn_add_fax, 3, 3, 1, 1)
        self.btn_add_email = QtWidgets.QPushButton(self.widget_3)
        self.btn_add_email.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_add_email.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.btn_add_email.setAutoDefault(False)
        self.btn_add_email.setObjectName("btn_add_email")
        self.gridLayout_3.addWidget(self.btn_add_email, 9, 3, 1, 1)
        self.widget5 = QtWidgets.QWidget(self.widget_3)
        self.widget5.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_phone = QtWidgets.QPushButton(self.widget5)
        self.info_label_phone.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_phone.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_phone.setFlat(True)
        self.info_label_phone.setObjectName("info_label_phone")
        self.horizontalLayout4.addWidget(self.info_label_phone)
        self.label_phone = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_phone.setFont(font)
        self.label_phone.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_phone.setObjectName("label_phone")
        self.horizontalLayout4.addWidget(self.label_phone)
        self.gridLayout_3.addWidget(self.widget5, 1, 0, 1, 1)
        self.phone = QtWidgets.QListView(self.widget_3)
        self.phone.setMaximumSize(QtCore.QSize(16777215, 75))
        self.phone.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.phone.setObjectName("phone")
        self.gridLayout_3.addWidget(self.phone, 2, 0, 1, 1)
        self.widget6 = QtWidgets.QWidget(self.widget_3)
        self.widget6.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setSpacing(0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.info_label_email = QtWidgets.QPushButton(self.widget6)
        self.info_label_email.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_email.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_email.setFlat(True)
        self.info_label_email.setObjectName("info_label_email")
        self.horizontalLayout5.addWidget(self.info_label_email)
        self.label_email = QtWidgets.QLabel(self.widget6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_email.setFont(font)
        self.label_email.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_email.setObjectName("label_email")
        self.horizontalLayout5.addWidget(self.label_email)
        self.gridLayout_3.addWidget(self.widget6, 6, 0, 1, 1)
        self.email = QtWidgets.QListView(self.widget_3)
        self.email.setMaximumSize(QtCore.QSize(16777215, 75))
        self.email.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.email.setObjectName("email")
        self.gridLayout_3.addWidget(self.email, 7, 0, 1, 3)
        self.line_email = gui.QgsFilterLineEdit(self.widget_3)
        self.line_email.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.line_email.setProperty("qgisRelation", "")
        self.line_email.setObjectName("line_email")
        self.gridLayout_3.addWidget(self.line_email, 9, 0, 1, 3)
        self.btn_del_email = QtWidgets.QPushButton(self.widget_3)
        self.btn_del_email.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_del_email.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.btn_del_email.setAutoDefault(False)
        self.btn_del_email.setObjectName("btn_del_email")
        self.gridLayout_3.addWidget(self.btn_del_email, 7, 3, 1, 1)
        self.widget7 = QtWidgets.QWidget(self.widget_3)
        self.widget7.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget7.setObjectName("widget7")
        self.horizontalLayout6 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout6.setSpacing(4)
        self.horizontalLayout6.setObjectName("horizontalLayout6")
        self.info_label_online = QtWidgets.QPushButton(self.widget7)
        self.info_label_online.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_online.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_online.setFlat(True)
        self.info_label_online.setObjectName("info_label_online")
        self.horizontalLayout6.addWidget(self.info_label_online)
        self.label_online = QtWidgets.QLabel(self.widget7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_online.setFont(font)
        self.label_online.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_online.setObjectName("label_online")
        self.horizontalLayout6.addWidget(self.label_online)
        self.online = gui.QgsFilterLineEdit(self.widget7)
        self.online.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.online.setProperty("qgisRelation", "")
        self.online.setObjectName("online")
        self.horizontalLayout6.addWidget(self.online)
        self.gridLayout_3.addWidget(self.widget7, 5, 0, 1, 4)
        self.gridLayout_4.addWidget(self.widget_3, 6, 0, 1, 1)
        self.widget8 = QtWidgets.QWidget(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget8.sizePolicy().hasHeightForWidth())
        self.widget8.setSizePolicy(sizePolicy)
        self.widget8.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget8.setObjectName("widget8")
        self.horizontalLayout7 = QtWidgets.QHBoxLayout(self.widget8)
        self.horizontalLayout7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout7.setSpacing(0)
        self.horizontalLayout7.setObjectName("horizontalLayout7")
        self.info_label_organization = QtWidgets.QPushButton(self.widget8)
        self.info_label_organization.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_organization.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_organization.setFlat(True)
        self.info_label_organization.setObjectName("info_label_organization")
        self.horizontalLayout7.addWidget(self.info_label_organization)
        self.label_organization = QtWidgets.QLabel(self.widget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_organization.sizePolicy().hasHeightForWidth())
        self.label_organization.setSizePolicy(sizePolicy)
        self.label_organization.setMinimumSize(QtCore.QSize(0, 0))
        self.label_organization.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_organization.setFont(font)
        self.label_organization.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_organization.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_organization.setObjectName("label_organization")
        self.horizontalLayout7.addWidget(self.label_organization)
        self.combo_org = QtWidgets.QComboBox(self.widget8)
        self.combo_org.setObjectName("combo_org")
        self.horizontalLayout7.addWidget(self.combo_org)
        self.gridLayout_4.addWidget(self.widget8, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_4.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout8 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout8.setSpacing(4)
        self.horizontalLayout8.setObjectName("horizontalLayout8")
        self.widget9 = QtWidgets.QWidget(self.widget_4)
        self.widget9.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget9.setObjectName("widget9")
        self.horizontalLayout9 = QtWidgets.QHBoxLayout(self.widget9)
        self.horizontalLayout9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout9.setSpacing(0)
        self.horizontalLayout9.setObjectName("horizontalLayout9")
        self.info_label_address = QtWidgets.QPushButton(self.widget9)
        self.info_label_address.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_address.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_address.setFlat(True)
        self.info_label_address.setObjectName("info_label_address")
        self.horizontalLayout9.addWidget(self.info_label_address)
        self.label_address = QtWidgets.QLabel(self.widget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_address.sizePolicy().hasHeightForWidth())
        self.label_address.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_address.setFont(font)
        self.label_address.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_address.setObjectName("label_address")
        self.horizontalLayout9.addWidget(self.label_address)
        self.horizontalLayout8.addWidget(self.widget9)
        self.address = gui.QgsFilterLineEdit(self.widget_4)
        self.address.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.address.setProperty("qgisRelation", "")
        self.address.setObjectName("address")
        self.horizontalLayout8.addWidget(self.address)
        self.widget10 = QtWidgets.QWidget(self.widget_4)
        self.widget10.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.widget10.setObjectName("widget10")
        self.horizontalLayout10 = QtWidgets.QHBoxLayout(self.widget10)
        self.horizontalLayout10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout10.setSpacing(0)
        self.horizontalLayout10.setObjectName("horizontalLayout10")
        self.info_label_country = QtWidgets.QPushButton(self.widget10)
        self.info_label_country.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_country.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.info_label_country.setFlat(True)
        self.info_label_country.setObjectName("info_label_country")
        self.horizontalLayout10.addWidget(self.info_label_country)
        self.label_country = QtWidgets.QLabel(self.widget10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_country.setFont(font)
        self.label_country.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_country.setObjectName("label_country")
        self.horizontalLayout10.addWidget(self.label_country)
        self.horizontalLayout8.addWidget(self.widget10)
        self.country = gui.QgsFilterLineEdit(self.widget_4)
        self.country.setMaximumSize(QtCore.QSize(300, 16777215))
        self.country.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.country.setProperty("qgisRelation", "")
        self.country.setObjectName("country")
        self.horizontalLayout8.addWidget(self.country)
        self.gridLayout_4.addWidget(self.widget_4, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.mGroupBox, 0, 1, 1, 1)

        self.retranslateUi(contactWidget)
        QtCore.QMetaObject.connectSlotsByName(contactWidget)

    def retranslateUi(self, contactWidget):
        _translate = QtCore.QCoreApplication.translate
        contactWidget.setWindowTitle(_translate("contactWidget", "Form"))
        self.btn_contact_list.setText(_translate("contactWidget", "I"))
        self.btn_addto_list_contacts.setText(_translate("contactWidget", "G"))
        self.btn_del_contact.setText(_translate("contactWidget", "R"))
        self.mGroupBox.setTitle(_translate("contactWidget", "INFO RESUMIDA "))
        self.label_city.setText(_translate("contactWidget", "Cidade  "))
        self.city.setPlaceholderText(_translate("contactWidget", "Cidade da Organização"))
        self.label_postalCode.setText(_translate("contactWidget", "Código Postal"))
        self.postalCode.setPlaceholderText(_translate("contactWidget", "Codigo Postal da Organização"))
        self.name.setPlaceholderText(_translate("contactWidget", "Nome da pessoa responsável"))
        self.label_name.setText(_translate("contactWidget", "Nome     "))
        self.label_role.setText(_translate("contactWidget", "Função"))
        self.label_outra.setText(_translate("contactWidget", "Outra (Não Listada)"))
        self.organization.setPlaceholderText(_translate("contactWidget", "NomePorExtenso (SIGLA)"))
        self.btn_add_phone.setText(_translate("contactWidget", "+"))
        self.label_fax.setText(_translate("contactWidget", "Fax"))
        self.btn_del_phone.setText(_translate("contactWidget", "-"))
        self.line_fax.setPlaceholderText(_translate("contactWidget", "21..."))
        self.btn_del_fax.setText(_translate("contactWidget", "-"))
        self.line_phone.setPlaceholderText(_translate("contactWidget", "21..."))
        self.btn_add_fax.setText(_translate("contactWidget", "+"))
        self.btn_add_email.setText(_translate("contactWidget", "+"))
        self.label_phone.setText(_translate("contactWidget", "Telefone"))
        self.label_email.setText(_translate("contactWidget", "Endereço Eletrónico(Email)*"))
        self.line_email.setPlaceholderText(_translate("contactWidget", "lorem@ipsum.pt"))
        self.btn_del_email.setText(_translate("contactWidget", "-"))
        self.label_online.setText(_translate("contactWidget", "Informação Online"))
        self.online.setPlaceholderText(_translate("contactWidget", "http://"))
        self.label_organization.setText(_translate("contactWidget", "Organização*"))
        self.label_address.setText(_translate("contactWidget", "Morada"))
        self.address.setPlaceholderText(_translate("contactWidget", "Rua,Av,..."))
        self.label_country.setText(_translate("contactWidget", "País"))
        self.country.setPlaceholderText(_translate("contactWidget", "País da Organização"))
from qgis import gui
