# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//crossrefDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_crossref_dialog(object):
    def setupUi(self, crossref_dialog):
        crossref_dialog.setObjectName("crossref_dialog")
        crossref_dialog.setWindowModality(QtCore.Qt.WindowModal)
        crossref_dialog.resize(662, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(crossref_dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_group_box = QtWidgets.QGroupBox(crossref_dialog)
        self.search_group_box.setObjectName("search_group_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.search_group_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_params_layout = QtWidgets.QHBoxLayout()
        self.search_params_layout.setObjectName("search_params_layout")
        self.author_layout = QtWidgets.QVBoxLayout()
        self.author_layout.setObjectName("author_layout")
        self.author_label = QtWidgets.QLabel(self.search_group_box)
        self.author_label.setObjectName("author_label")
        self.author_layout.addWidget(self.author_label)
        self.author_edit = QtWidgets.QLineEdit(self.search_group_box)
        self.author_edit.setObjectName("author_edit")
        self.author_layout.addWidget(self.author_edit)
        self.search_params_layout.addLayout(self.author_layout)
        self.title_layout = QtWidgets.QVBoxLayout()
        self.title_layout.setObjectName("title_layout")
        self.title_label = QtWidgets.QLabel(self.search_group_box)
        self.title_label.setObjectName("title_label")
        self.title_layout.addWidget(self.title_label)
        self.title_edit = QtWidgets.QLineEdit(self.search_group_box)
        self.title_edit.setObjectName("title_edit")
        self.title_layout.addWidget(self.title_edit)
        self.search_params_layout.addLayout(self.title_layout)
        self.verticalLayout_2.addLayout(self.search_params_layout)
        self.search_inner_layout = QtWidgets.QHBoxLayout()
        self.search_inner_layout.setObjectName("search_inner_layout")
        self.btn_search = QtWidgets.QPushButton(self.search_group_box)
        self.btn_search.setObjectName("btn_search")
        self.search_inner_layout.addWidget(self.btn_search)
        self.search_status = QtWidgets.QLabel(self.search_group_box)
        self.search_status.setText("")
        self.search_status.setObjectName("search_status")
        self.search_inner_layout.addWidget(self.search_status)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.search_inner_layout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.search_inner_layout)
        self.verticalLayout.addWidget(self.search_group_box)
        self.results_group_box = QtWidgets.QGroupBox(crossref_dialog)
        self.results_group_box.setObjectName("results_group_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.results_group_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.results_table = QtWidgets.QTableView(self.results_group_box)
        self.results_table.setObjectName("results_table")
        self.verticalLayout_3.addWidget(self.results_table)
        self.pagination_layout = QtWidgets.QHBoxLayout()
        self.pagination_layout.setObjectName("pagination_layout")
        self.previous_page = QtWidgets.QPushButton(self.results_group_box)
        self.previous_page.setMaximumSize(QtCore.QSize(30, 16777215))
        self.previous_page.setObjectName("previous_page")
        self.pagination_layout.addWidget(self.previous_page)
        self.current_page = QtWidgets.QLabel(self.results_group_box)
        self.current_page.setText("")
        self.current_page.setObjectName("current_page")
        self.pagination_layout.addWidget(self.current_page)
        self.next_page = QtWidgets.QPushButton(self.results_group_box)
        self.next_page.setMaximumSize(QtCore.QSize(30, 16777215))
        self.next_page.setObjectName("next_page")
        self.pagination_layout.addWidget(self.next_page)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.pagination_layout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.pagination_layout)
        self.verticalLayout.addWidget(self.results_group_box)
        self.dialog_btn_layout = QtWidgets.QHBoxLayout()
        self.dialog_btn_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.dialog_btn_layout.setObjectName("dialog_btn_layout")
        self.add_row_btn = QtWidgets.QPushButton(crossref_dialog)
        self.add_row_btn.setEnabled(False)
        self.add_row_btn.setObjectName("add_row_btn")
        self.dialog_btn_layout.addWidget(self.add_row_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dialog_btn_layout.addItem(spacerItem2)
        self.btn_close_dialog = QtWidgets.QPushButton(crossref_dialog)
        self.btn_close_dialog.setObjectName("btn_close_dialog")
        self.dialog_btn_layout.addWidget(self.btn_close_dialog)
        self.verticalLayout.addLayout(self.dialog_btn_layout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(crossref_dialog)
        QtCore.QMetaObject.connectSlotsByName(crossref_dialog)

    def retranslateUi(self, crossref_dialog):
        _translate = QtCore.QCoreApplication.translate
        crossref_dialog.setWindowTitle(_translate("crossref_dialog", "Dialog"))
        self.search_group_box.setTitle(_translate("crossref_dialog", "Pesquisa"))
        self.author_label.setText(_translate("crossref_dialog", "Autor"))
        self.title_label.setText(_translate("crossref_dialog", "Titulo"))
        self.btn_search.setText(_translate("crossref_dialog", "Pesquisar"))
        self.results_group_box.setTitle(_translate("crossref_dialog", "Resultados"))
        self.previous_page.setText(_translate("crossref_dialog", "<"))
        self.next_page.setText(_translate("crossref_dialog", ">"))
        self.add_row_btn.setText(_translate("crossref_dialog", "Adicionar"))
        self.btn_close_dialog.setText(_translate("crossref_dialog", "Fechar"))
