# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//login_geonetwork.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Geonetwork(object):
    def setupUi(self, Login_Geonetwork):
        Login_Geonetwork.setObjectName("Login_Geonetwork")
        Login_Geonetwork.resize(518, 163)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login_Geonetwork.sizePolicy().hasHeightForWidth())
        Login_Geonetwork.setSizePolicy(sizePolicy)
        Login_Geonetwork.setMinimumSize(QtCore.QSize(400, 140))
        Login_Geonetwork.setMaximumSize(QtCore.QSize(518, 218))
        Login_Geonetwork.setAutoFillBackground(False)
        Login_Geonetwork.setStyleSheet("background: #005caf;")
        Login_Geonetwork.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Login_Geonetwork)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Login_Geonetwork)
        self.widget.setMinimumSize(QtCore.QSize(500, 100))
        self.widget.setMaximumSize(QtCore.QSize(500, 150))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 17))
        self.label.setStyleSheet("color:white\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.carregar = QtWidgets.QPushButton(self.widget)
        self.carregar.setGeometry(QtCore.QRect(160, 100, 89, 31))
        self.carregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.carregar.setObjectName("carregar")
        self.voltar = QtWidgets.QPushButton(self.widget)
        self.voltar.setGeometry(QtCore.QRect(270, 100, 89, 31))
        self.voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.voltar.setObjectName("voltar")
        self.user = QtWidgets.QLineEdit(self.widget)
        self.user.setGeometry(QtCore.QRect(20, 40, 211, 31))
        self.user.setStyleSheet("color:white")
        self.user.setObjectName("user")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(260, 10, 211, 17))
        self.label_2.setStyleSheet("color:white\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(260, 40, 211, 31))
        self.password.setStyleSheet("color:white")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Login_Geonetwork)
        QtCore.QMetaObject.connectSlotsByName(Login_Geonetwork)

    def retranslateUi(self, Login_Geonetwork):
        _translate = QtCore.QCoreApplication.translate
        Login_Geonetwork.setWindowTitle(_translate("Login_Geonetwork", "Login Geonetwork"))
        self.label.setText(_translate("Login_Geonetwork", "<html><head/><body><p><span style=\" font-size:12pt;\">Utilizador:</span></p></body></html>"))
        self.carregar.setText(_translate("Login_Geonetwork", "Entrar"))
        self.voltar.setText(_translate("Login_Geonetwork", "Voltar"))
        self.label_2.setText(_translate("Login_Geonetwork", "<html><head/><body><p><span style=\" font-size:12pt;\">Password:</span></p></body></html>"))
