# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//operationInlinePanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_operations(object):
    def setupUi(self, operations):
        operations.setObjectName("operations")
        operations.resize(594, 347)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(operations.sizePolicy().hasHeightForWidth())
        operations.setSizePolicy(sizePolicy)
        operations.setMinimumSize(QtCore.QSize(500, 0))
        operations.setMaximumSize(QtCore.QSize(16777215, 583))
        self.gridLayout_2 = QtWidgets.QGridLayout(operations)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(operations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_del_operation = QtWidgets.QPushButton(self.frame)
        self.btn_del_operation.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_operation.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_operation.setObjectName("btn_del_operation")
        self.gridLayout_3.addWidget(self.btn_del_operation, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.operation_gbox = gui.QgsCollapsibleGroupBox(operations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operation_gbox.sizePolicy().hasHeightForWidth())
        self.operation_gbox.setSizePolicy(sizePolicy)
        self.operation_gbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.operation_gbox.setFont(font)
        self.operation_gbox.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.operation_gbox.setSaveCollapsedState(False)
        self.operation_gbox.setObjectName("operation_gbox")
        self.gridLayout = QtWidgets.QGridLayout(self.operation_gbox)
        self.gridLayout.setContentsMargins(0, 8, 0, 0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_del_dcp = QtWidgets.QPushButton(self.operation_gbox)
        self.btn_del_dcp.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_dcp.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_dcp.setObjectName("btn_del_dcp")
        self.gridLayout.addWidget(self.btn_del_dcp, 5, 1, 1, 1)
        self.dcp = QtWidgets.QListView(self.operation_gbox)
        self.dcp.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dcp.setFont(font)
        self.dcp.setObjectName("dcp")
        self.gridLayout.addWidget(self.dcp, 4, 0, 2, 1)
        self.line_connectionPoint = gui.QgsFilterLineEdit(self.operation_gbox)
        self.line_connectionPoint.setMinimumSize(QtCore.QSize(58, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_connectionPoint.setFont(font)
        self.line_connectionPoint.setText("")
        self.line_connectionPoint.setProperty("qgisRelation", "")
        self.line_connectionPoint.setObjectName("line_connectionPoint")
        self.gridLayout.addWidget(self.line_connectionPoint, 11, 0, 1, 1)
        self.combo_dcp = QtWidgets.QComboBox(self.operation_gbox)
        self.combo_dcp.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_dcp.setFont(font)
        self.combo_dcp.setObjectName("combo_dcp")
        self.gridLayout.addWidget(self.combo_dcp, 6, 0, 1, 1)
        self.btn_add_connectionPoint = QtWidgets.QPushButton(self.operation_gbox)
        self.btn_add_connectionPoint.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_connectionPoint.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_connectionPoint.setObjectName("btn_add_connectionPoint")
        self.gridLayout.addWidget(self.btn_add_connectionPoint, 11, 1, 1, 1)
        self.btn_add_dcp = QtWidgets.QPushButton(self.operation_gbox)
        self.btn_add_dcp.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_dcp.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_dcp.setObjectName("btn_add_dcp")
        self.gridLayout.addWidget(self.btn_add_dcp, 6, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.operation_gbox)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.info_label_connectionPoint = QtWidgets.QPushButton(self.frame_3)
        self.info_label_connectionPoint.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_connectionPoint.setText("")
        self.info_label_connectionPoint.setFlat(True)
        self.info_label_connectionPoint.setObjectName("info_label_connectionPoint")
        self.horizontalLayout_3.addWidget(self.info_label_connectionPoint)
        self.label_connectionPoint = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_connectionPoint.setFont(font)
        self.label_connectionPoint.setObjectName("label_connectionPoint")
        self.horizontalLayout_3.addWidget(self.label_connectionPoint)
        self.gridLayout.addWidget(self.frame_3, 7, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.operation_gbox)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.info_label_dcp = QtWidgets.QPushButton(self.frame_2)
        self.info_label_dcp.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_dcp.setText("")
        self.info_label_dcp.setFlat(True)
        self.info_label_dcp.setObjectName("info_label_dcp")
        self.horizontalLayout_2.addWidget(self.info_label_dcp)
        self.label_dcp = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_dcp.setFont(font)
        self.label_dcp.setObjectName("label_dcp")
        self.horizontalLayout_2.addWidget(self.label_dcp)
        self.gridLayout.addWidget(self.frame_2, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.operation_gbox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.btn_del_connectionPoint = QtWidgets.QPushButton(self.operation_gbox)
        self.btn_del_connectionPoint.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_connectionPoint.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_connectionPoint.setObjectName("btn_del_connectionPoint")
        self.gridLayout.addWidget(self.btn_del_connectionPoint, 10, 1, 1, 1)
        self.connectionPoint = QtWidgets.QListView(self.operation_gbox)
        self.connectionPoint.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.connectionPoint.setFont(font)
        self.connectionPoint.setObjectName("connectionPoint")
        self.gridLayout.addWidget(self.connectionPoint, 9, 0, 2, 1)
        self.frame1 = QtWidgets.QFrame(self.operation_gbox)
        self.frame1.setObjectName("frame1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_operationName = QtWidgets.QPushButton(self.frame1)
        self.info_label_operationName.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_operationName.setText("")
        self.info_label_operationName.setFlat(True)
        self.info_label_operationName.setObjectName("info_label_operationName")
        self.horizontalLayout.addWidget(self.info_label_operationName)
        self.label_operationName = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_operationName.setFont(font)
        self.label_operationName.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_operationName.setObjectName("label_operationName")
        self.horizontalLayout.addWidget(self.label_operationName)
        self.operationName = gui.QgsFilterLineEdit(self.frame1)
        self.operationName.setMinimumSize(QtCore.QSize(58, 30))
        self.operationName.setProperty("qgisRelation", "")
        self.operationName.setObjectName("operationName")
        self.horizontalLayout.addWidget(self.operationName)
        self.gridLayout.addWidget(self.frame1, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.operation_gbox, 0, 1, 1, 1)

        self.retranslateUi(operations)
        QtCore.QMetaObject.connectSlotsByName(operations)

    def retranslateUi(self, operations):
        _translate = QtCore.QCoreApplication.translate
        operations.setWindowTitle(_translate("operations", "Form"))
        self.btn_del_operation.setText(_translate("operations", "-"))
        self.operation_gbox.setTitle(_translate("operations", "operation Name"))
        self.btn_del_dcp.setText(_translate("operations", "-"))
        self.line_connectionPoint.setPlaceholderText(_translate("operations", "URI ou http://"))
        self.btn_add_connectionPoint.setText(_translate("operations", "+"))
        self.btn_add_dcp.setText(_translate("operations", "+"))
        self.label_connectionPoint.setText(_translate("operations", "Pontos de Acesso(URL/URI)*"))
        self.label_dcp.setText(_translate("operations", "DCP <span style=\" font-style:italic;\">(Distributed Computing Platforms)</span>*"))
        self.btn_del_connectionPoint.setText(_translate("operations", "-"))
        self.label_operationName.setText(_translate("operations", "Nome da Operação*:"))
        self.operationName.setPlaceholderText(_translate("operations", "Identificador único para a interface..."))
from qgis import gui
