# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//read_geonetwork.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(650, 164)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(About.sizePolicy().hasHeightForWidth())
        About.setSizePolicy(sizePolicy)
        About.setMinimumSize(QtCore.QSize(600, 150))
        About.setMaximumSize(QtCore.QSize(650, 600))
        About.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(About)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(About)
        self.widget.setObjectName("widget")
        self.editor_logo = QtWidgets.QLabel(self.widget)
        self.editor_logo.setGeometry(QtCore.QRect(10, 30, 60, 60))
        self.editor_logo.setMinimumSize(QtCore.QSize(60, 60))
        self.editor_logo.setMaximumSize(QtCore.QSize(60, 60))
        self.editor_logo.setObjectName("editor_logo")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 20, 211, 17))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(83, 10, 20, 111))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.carregar = QtWidgets.QPushButton(self.widget)
        self.carregar.setGeometry(QtCore.QRect(430, 100, 89, 25))
        self.carregar.setObjectName("carregar")
        self.voltar = QtWidgets.QPushButton(self.widget)
        self.voltar.setGeometry(QtCore.QRect(530, 100, 89, 25))
        self.voltar.setObjectName("voltar")
        self.url = QtWidgets.QLineEdit(self.widget)
        self.url.setGeometry(QtCore.QRect(130, 50, 491, 31))
        self.url.setObjectName("url")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", " Abrir por endereço"))
        self.editor_logo.setText(_translate("About", "<img border=\"0\" alt=\"LOGO\" src=\":resourcesFolder/icons/main_icon.png\" width=\"60\" heigth=\"60\">"))
        self.label.setText(_translate("About", "<html><head/><body><p><span style=\" font-size:12pt;\">Endereço de leitura (URL):</span></p></body></html>"))
        self.carregar.setText(_translate("About", "Carregar"))
        self.voltar.setText(_translate("About", "Voltar"))
