# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/dialogs//wormsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_worms_dialog(object):
    def setupUi(self, worms_dialog):
        worms_dialog.setObjectName("worms_dialog")
        worms_dialog.setWindowModality(QtCore.Qt.WindowModal)
        worms_dialog.resize(662, 459)
        self.verticalLayout = QtWidgets.QVBoxLayout(worms_dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_group_box = QtWidgets.QGroupBox(worms_dialog)
        self.search_group_box.setObjectName("search_group_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.search_group_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_params_layout = QtWidgets.QHBoxLayout()
        self.search_params_layout.setObjectName("search_params_layout")
        self.name_layout = QtWidgets.QVBoxLayout()
        self.name_layout.setObjectName("name_layout")
        self.name_label = QtWidgets.QLabel(self.search_group_box)
        self.name_label.setObjectName("name_label")
        self.name_layout.addWidget(self.name_label)
        self.name_edit = QtWidgets.QLineEdit(self.search_group_box)
        self.name_edit.setObjectName("name_edit")
        self.name_layout.addWidget(self.name_edit)
        self.search_params_layout.addLayout(self.name_layout)
        self.vernacular_layout = QtWidgets.QVBoxLayout()
        self.vernacular_layout.setObjectName("vernacular_layout")
        self.vernacular_label = QtWidgets.QLabel(self.search_group_box)
        self.vernacular_label.setObjectName("vernacular_label")
        self.vernacular_layout.addWidget(self.vernacular_label)
        self.vernacular_edit = QtWidgets.QLineEdit(self.search_group_box)
        self.vernacular_edit.setObjectName("vernacular_edit")
        self.vernacular_layout.addWidget(self.vernacular_edit)
        self.search_params_layout.addLayout(self.vernacular_layout)
        self.identifier_layout = QtWidgets.QVBoxLayout()
        self.identifier_layout.setObjectName("identifier_layout")
        self.identifier_label = QtWidgets.QLabel(self.search_group_box)
        self.identifier_label.setObjectName("identifier_label")
        self.identifier_layout.addWidget(self.identifier_label)
        self.identifier_edit = QtWidgets.QLineEdit(self.search_group_box)
        self.identifier_edit.setObjectName("identifier_edit")
        self.identifier_layout.addWidget(self.identifier_edit)
        self.search_params_layout.addLayout(self.identifier_layout)
        self.verticalLayout_2.addLayout(self.search_params_layout)
        self.search_inner_layout = QtWidgets.QHBoxLayout()
        self.search_inner_layout.setObjectName("search_inner_layout")
        self.btn_search = QtWidgets.QPushButton(self.search_group_box)
        self.btn_search.setObjectName("btn_search")
        self.search_inner_layout.addWidget(self.btn_search)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.search_inner_layout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.search_inner_layout)
        self.verticalLayout.addWidget(self.search_group_box)
        self.results_group_box = QtWidgets.QGroupBox(worms_dialog)
        self.results_group_box.setObjectName("results_group_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.results_group_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.results_table = QtWidgets.QTableView(self.results_group_box)
        self.results_table.setObjectName("results_table")
        self.verticalLayout_3.addWidget(self.results_table)
        self.verticalLayout.addWidget(self.results_group_box)
        self.dialog_btn_layout = QtWidgets.QHBoxLayout()
        self.dialog_btn_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.dialog_btn_layout.setObjectName("dialog_btn_layout")
        self.add_row_btn = QtWidgets.QPushButton(worms_dialog)
        self.add_row_btn.setEnabled(False)
        self.add_row_btn.setObjectName("add_row_btn")
        self.dialog_btn_layout.addWidget(self.add_row_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dialog_btn_layout.addItem(spacerItem1)
        self.btn_close_dialog = QtWidgets.QPushButton(worms_dialog)
        self.btn_close_dialog.setObjectName("btn_close_dialog")
        self.dialog_btn_layout.addWidget(self.btn_close_dialog)
        self.verticalLayout.addLayout(self.dialog_btn_layout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(worms_dialog)
        QtCore.QMetaObject.connectSlotsByName(worms_dialog)

    def retranslateUi(self, worms_dialog):
        _translate = QtCore.QCoreApplication.translate
        worms_dialog.setWindowTitle(_translate("worms_dialog", "Dialog"))
        self.search_group_box.setTitle(_translate("worms_dialog", "Pesquisa"))
        self.name_label.setText(_translate("worms_dialog", "Nome científico"))
        self.vernacular_label.setText(_translate("worms_dialog", "Nome vernacular"))
        self.identifier_label.setText(_translate("worms_dialog", "AphiaID"))
        self.btn_search.setText(_translate("worms_dialog", "Pesquisar"))
        self.results_group_box.setTitle(_translate("worms_dialog", "Resultados"))
        self.add_row_btn.setText(_translate("worms_dialog", "Adicionar"))
        self.btn_close_dialog.setText(_translate("worms_dialog", "Fechar"))
