# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/distributionPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_distribution(object):
    def setupUi(self, distribution):
        distribution.setObjectName("distribution")
        distribution.resize(580, 636)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(distribution.sizePolicy().hasHeightForWidth())
        distribution.setSizePolicy(sizePolicy)
        distribution.setMinimumSize(QtCore.QSize(580, 0))
        self.gridLayout = QtWidgets.QGridLayout(distribution)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(distribution)
        self.scrollArea.setMinimumSize(QtCore.QSize(580, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 562, 680))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.resourcelocator = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.resourcelocator.setMinimumSize(QtCore.QSize(0, 180))
        self.resourcelocator.setMaximumSize(QtCore.QSize(16777215, 180))
        self.resourcelocator.setObjectName("resourcelocator")
        self.resourcelocator.verticalHeader().setDefaultSectionSize(0)
        self.gridLayout_2.addWidget(self.resourcelocator, 7, 0, 2, 2)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_filesize = QtWidgets.QPushButton(self.widget)
        self.info_label_filesize.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_filesize.setFlat(True)
        self.info_label_filesize.setObjectName("info_label_filesize")
        self.horizontalLayout.addWidget(self.info_label_filesize)
        self.label_filesize = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_filesize.setFont(font)
        self.label_filesize.setObjectName("label_filesize")
        self.horizontalLayout.addWidget(self.label_filesize)
        self.gridLayout_2.addWidget(self.widget, 4, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_resourcelocator = QtWidgets.QPushButton(self.widget1)
        self.info_label_resourcelocator.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_resourcelocator.setFlat(True)
        self.info_label_resourcelocator.setObjectName("info_label_resourcelocator")
        self.horizontalLayout1.addWidget(self.info_label_resourcelocator)
        self.label_resourcelocator = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_resourcelocator.setFont(font)
        self.label_resourcelocator.setObjectName("label_resourcelocator")
        self.horizontalLayout1.addWidget(self.label_resourcelocator)
        self.gridLayout_2.addWidget(self.widget1, 6, 0, 1, 1)
        self.btn_add_distributionformat = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_add_distributionformat.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_distributionformat.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_distributionformat.setObjectName("btn_add_distributionformat")
        self.gridLayout_2.addWidget(self.btn_add_distributionformat, 3, 2, 1, 1)
        self.distributionformat = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.distributionformat.setMinimumSize(QtCore.QSize(0, 180))
        self.distributionformat.setMaximumSize(QtCore.QSize(16777215, 180))
        self.distributionformat.setObjectName("distributionformat")
        self.distributionformat.verticalHeader().setDefaultSectionSize(0)
        self.gridLayout_2.addWidget(self.distributionformat, 1, 0, 2, 2)
        self.widget2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_distributionformat = QtWidgets.QPushButton(self.widget2)
        self.info_label_distributionformat.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_distributionformat.setFlat(True)
        self.info_label_distributionformat.setObjectName("info_label_distributionformat")
        self.horizontalLayout2.addWidget(self.info_label_distributionformat)
        self.label_distributionformat = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_distributionformat.setFont(font)
        self.label_distributionformat.setObjectName("label_distributionformat")
        self.horizontalLayout2.addWidget(self.label_distributionformat)
        self.gridLayout_2.addWidget(self.widget2, 0, 0, 1, 1)
        self.btn_del_distributionformat = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_del_distributionformat.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_distributionformat.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_distributionformat.setObjectName("btn_del_distributionformat")
        self.gridLayout_2.addWidget(self.btn_del_distributionformat, 2, 2, 1, 1)
        self.horizontalLayout3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.line_name = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.line_name.setMinimumSize(QtCore.QSize(0, 30))
        self.line_name.setProperty("qgisRelation", "")
        self.line_name.setObjectName("line_name")
        self.horizontalLayout3.addWidget(self.line_name)
        self.line_version = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.line_version.setMinimumSize(QtCore.QSize(0, 30))
        self.line_version.setText("")
        self.line_version.setProperty("qgisRelation", "")
        self.line_version.setObjectName("line_version")
        self.horizontalLayout3.addWidget(self.line_version)
        self.gridLayout_2.addLayout(self.horizontalLayout3, 3, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_linkage = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.line_linkage.sizePolicy().hasHeightForWidth())
        self.line_linkage.setSizePolicy(sizePolicy)
        self.line_linkage.setMinimumSize(QtCore.QSize(0, 30))
        self.line_linkage.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.line_linkage.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.line_linkage.setProperty("qgisRelation", "")
        self.line_linkage.setObjectName("line_linkage")
        self.horizontalLayout_2.addWidget(self.line_linkage)
        self.combo_function = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.combo_function.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_function.setObjectName("combo_function")
        self.horizontalLayout_2.addWidget(self.combo_function)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 9, 0, 1, 2)
        self.btn_add_resourcelocator = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_add_resourcelocator.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_resourcelocator.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_resourcelocator.setObjectName("btn_add_resourcelocator")
        self.gridLayout_2.addWidget(self.btn_add_resourcelocator, 9, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 14, 0, 1, 1)
        self.btn_adi_contact = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_adi_contact.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_adi_contact.setFont(font)
        self.btn_adi_contact.setObjectName("btn_adi_contact")
        self.gridLayout_2.addWidget(self.btn_adi_contact, 12, 0, 1, 3)
        self.btn_del_resourcelocator = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_del_resourcelocator.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_resourcelocator.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_resourcelocator.setObjectName("btn_del_resourcelocator")
        self.gridLayout_2.addWidget(self.btn_del_resourcelocator, 8, 2, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_ditribution_contact = QtWidgets.QPushButton(self.widget3)
        self.info_label_ditribution_contact.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_ditribution_contact.setFlat(True)
        self.info_label_ditribution_contact.setObjectName("info_label_ditribution_contact")
        self.horizontalLayout4.addWidget(self.info_label_ditribution_contact)
        self.label_ditribution_contact = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ditribution_contact.setFont(font)
        self.label_ditribution_contact.setObjectName("label_ditribution_contact")
        self.horizontalLayout4.addWidget(self.label_ditribution_contact)
        self.gridLayout_2.addWidget(self.widget3, 10, 0, 1, 1)
        self.Contacts = QtWidgets.QVBoxLayout()
        self.Contacts.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Contacts.setContentsMargins(-1, 0, -1, 0)
        self.Contacts.setSpacing(0)
        self.Contacts.setObjectName("Contacts")
        self.gridLayout_2.addLayout(self.Contacts, 11, 0, 1, 3)
        self.filesize = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.filesize.setMinimumSize(QtCore.QSize(98, 30))
        self.filesize.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.filesize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.filesize.setMaximum(999999999.0)
        self.filesize.setSingleStep(0.0)
        self.filesize.setObjectName("filesize")
        self.gridLayout_2.addWidget(self.filesize, 5, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(distribution)
        QtCore.QMetaObject.connectSlotsByName(distribution)
        distribution.setTabOrder(self.info_label_distributionformat, self.scrollArea)
        distribution.setTabOrder(self.scrollArea, self.line_version)
        distribution.setTabOrder(self.line_version, self.btn_del_distributionformat)
        distribution.setTabOrder(self.btn_del_distributionformat, self.btn_add_distributionformat)
        distribution.setTabOrder(self.btn_add_distributionformat, self.filesize)
        distribution.setTabOrder(self.filesize, self.line_name)
        distribution.setTabOrder(self.line_name, self.info_label_resourcelocator)
        distribution.setTabOrder(self.info_label_resourcelocator, self.resourcelocator)
        distribution.setTabOrder(self.resourcelocator, self.info_label_filesize)
        distribution.setTabOrder(self.info_label_filesize, self.distributionformat)
        distribution.setTabOrder(self.distributionformat, self.line_linkage)
        distribution.setTabOrder(self.line_linkage, self.combo_function)
        distribution.setTabOrder(self.combo_function, self.btn_add_resourcelocator)
        distribution.setTabOrder(self.btn_add_resourcelocator, self.btn_adi_contact)
        distribution.setTabOrder(self.btn_adi_contact, self.btn_del_resourcelocator)
        distribution.setTabOrder(self.btn_del_resourcelocator, self.info_label_ditribution_contact)

    def retranslateUi(self, distribution):
        _translate = QtCore.QCoreApplication.translate
        distribution.setWindowTitle(_translate("distribution", "Form"))
        self.label_filesize.setText(_translate("distribution", "Tamanho do Ficheiro (MB)"))
        self.label_resourcelocator.setText(_translate("distribution", "Localizador do Recurso"))
        self.btn_add_distributionformat.setText(_translate("distribution", "+"))
        self.label_distributionformat.setText(_translate("distribution", "Formato de Distribuição*"))
        self.btn_del_distributionformat.setText(_translate("distribution", "-"))
        self.line_name.setPlaceholderText(_translate("distribution", "SHP, TIFF ,..."))
        self.line_version.setPlaceholderText(_translate("distribution", "Versão..."))
        self.line_linkage.setPlaceholderText(_translate("distribution", "http://"))
        self.btn_add_resourcelocator.setText(_translate("distribution", "+"))
        self.btn_adi_contact.setText(_translate("distribution", "Adicionar Contacto"))
        self.btn_del_resourcelocator.setText(_translate("distribution", "-"))
        self.label_ditribution_contact.setText(_translate("distribution", " Responsáveis pela Distribuição (Contactos)"))
from qgis import gui
