# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/keywordsPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_keywords(object):
    def setupUi(self, keywords):
        keywords.setObjectName("keywords")
        keywords.resize(723, 713)
        keywords.setMinimumSize(QtCore.QSize(580, 0))
        self.gridLayout = QtWidgets.QGridLayout(keywords)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(keywords)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -745, 707, 1462))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 29, 3, 1, 1)
        self.snimarkeywords = QtWidgets.QTableView(self.widget)
        self.snimarkeywords.setMinimumSize(QtCore.QSize(0, 240))
        self.snimarkeywords.setMaximumSize(QtCore.QSize(16777215, 240))
        self.snimarkeywords.setAccessibleName("")
        self.snimarkeywords.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.snimarkeywords.setObjectName("snimarkeywords")
        self.gridLayout_2.addWidget(self.snimarkeywords, 13, 0, 4, 3)
        self.widget_inspire = QtWidgets.QWidget(self.widget)
        self.widget_inspire.setObjectName("widget_inspire")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_inspire)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_inspire = QtWidgets.QPushButton(self.widget_inspire)
        self.info_label_inspire.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_inspire.setFlat(True)
        self.info_label_inspire.setObjectName("info_label_inspire")
        self.horizontalLayout.addWidget(self.info_label_inspire)
        self.label_inspire = QtWidgets.QLabel(self.widget_inspire)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_inspire.setFont(font)
        self.label_inspire.setAccessibleName("")
        self.label_inspire.setObjectName("label_inspire")
        self.horizontalLayout.addWidget(self.label_inspire)
        self.gridLayout_2.addWidget(self.widget_inspire, 5, 0, 1, 2)
        self.freekeywords = QtWidgets.QTableView(self.widget)
        self.freekeywords.setMinimumSize(QtCore.QSize(0, 240))
        self.freekeywords.setMaximumSize(QtCore.QSize(16777215, 240))
        self.freekeywords.setAccessibleName("")
        self.freekeywords.setObjectName("freekeywords")
        self.freekeywords.verticalHeader().setDefaultSectionSize(0)
        self.gridLayout_2.addWidget(self.freekeywords, 28, 0, 3, 3)
        self.btn_open_freekeywords = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_freekeywords.sizePolicy().hasHeightForWidth())
        self.btn_open_freekeywords.setSizePolicy(sizePolicy)
        self.btn_open_freekeywords.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_open_freekeywords.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_open_freekeywords.setAccessibleName("")
        self.btn_open_freekeywords.setObjectName("btn_open_freekeywords")
        self.gridLayout_2.addWidget(self.btn_open_freekeywords, 31, 0, 1, 3)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.info_label_worms = QtWidgets.QPushButton(self.widget_5)
        self.info_label_worms.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_worms.setText("")
        self.info_label_worms.setFlat(True)
        self.info_label_worms.setObjectName("info_label_worms")
        self.horizontalLayout_5.addWidget(self.info_label_worms)
        self.label_worms = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_worms.setFont(font)
        self.label_worms.setObjectName("label_worms")
        self.horizontalLayout_5.addWidget(self.label_worms)
        self.horizontalLayout_5.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.widget_5, 18, 0, 1, 1)
        self.btn_del_freekeywords = QtWidgets.QPushButton(self.widget)
        self.btn_del_freekeywords.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_freekeywords.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_freekeywords.setAccessibleName("")
        self.btn_del_freekeywords.setObjectName("btn_del_freekeywords")
        self.gridLayout_2.addWidget(self.btn_del_freekeywords, 30, 3, 1, 1)
        self.btn_del_topiccategory = QtWidgets.QPushButton(self.widget)
        self.btn_del_topiccategory.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_topiccategory.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_topiccategory.setAccessibleName("")
        self.btn_del_topiccategory.setObjectName("btn_del_topiccategory")
        self.gridLayout_2.addWidget(self.btn_del_topiccategory, 10, 3, 1, 1)
        self.combo_serviceClassification = QtWidgets.QComboBox(self.widget)
        self.combo_serviceClassification.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_serviceClassification.setMaxVisibleItems(5)
        self.combo_serviceClassification.setObjectName("combo_serviceClassification")
        self.gridLayout_2.addWidget(self.combo_serviceClassification, 4, 0, 1, 3)
        self.btn_add_serviceClassification = QtWidgets.QPushButton(self.widget)
        self.btn_add_serviceClassification.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_serviceClassification.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_serviceClassification.setObjectName("btn_add_serviceClassification")
        self.gridLayout_2.addWidget(self.btn_add_serviceClassification, 4, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout1.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.combo_inspire = QtWidgets.QComboBox(self.widget_2)
        self.combo_inspire.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_inspire.setObjectName("combo_inspire")
        self.horizontalLayout1.addWidget(self.combo_inspire)
        self.btn_add_inspire = QtWidgets.QPushButton(self.widget_2)
        self.btn_add_inspire.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_inspire.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_inspire.setAccessibleName("")
        self.btn_add_inspire.setObjectName("btn_add_inspire")
        self.horizontalLayout1.addWidget(self.btn_add_inspire)
        self.gridLayout_2.addWidget(self.widget_2, 11, 0, 1, 2)
        self.topiccategory = QtWidgets.QListView(self.widget)
        self.topiccategory.setMinimumSize(QtCore.QSize(0, 160))
        self.topiccategory.setMaximumSize(QtCore.QSize(16777215, 160))
        self.topiccategory.setObjectName("topiccategory")
        self.gridLayout_2.addWidget(self.topiccategory, 8, 2, 3, 1)
        self.inspire = QtWidgets.QListView(self.widget)
        self.inspire.setMinimumSize(QtCore.QSize(0, 160))
        self.inspire.setMaximumSize(QtCore.QSize(16777215, 160))
        self.inspire.setAccessibleName("")
        self.inspire.setObjectName("inspire")
        self.gridLayout_2.addWidget(self.inspire, 8, 0, 3, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.link_ckw = QtWidgets.QLabel(self.widget_4)
        self.link_ckw.setMinimumSize(QtCore.QSize(0, 0))
        self.link_ckw.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.link_ckw.setScaledContents(True)
        self.link_ckw.setOpenExternalLinks(True)
        self.link_ckw.setObjectName("link_ckw")
        self.horizontalLayout_4.addWidget(self.link_ckw)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btn_update_snimar = QtWidgets.QPushButton(self.widget_4)
        self.btn_update_snimar.setObjectName("btn_update_snimar")
        self.horizontalLayout_4.addWidget(self.btn_update_snimar)
        self.gridLayout_2.addWidget(self.widget_4, 12, 2, 1, 1)
        self.btn_open_snimarkeywords = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_snimarkeywords.sizePolicy().hasHeightForWidth())
        self.btn_open_snimarkeywords.setSizePolicy(sizePolicy)
        self.btn_open_snimarkeywords.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_open_snimarkeywords.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_open_snimarkeywords.setAccessibleName("")
        self.btn_open_snimarkeywords.setObjectName("btn_open_snimarkeywords")
        self.gridLayout_2.addWidget(self.btn_open_snimarkeywords, 17, 0, 1, 3)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.combo_topiccategory = QtWidgets.QComboBox(self.widget_3)
        self.combo_topiccategory.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_topiccategory.setObjectName("combo_topiccategory")
        self.horizontalLayout_2.addWidget(self.combo_topiccategory)
        self.btn_add_topiccategory = QtWidgets.QPushButton(self.widget_3)
        self.btn_add_topiccategory.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_topiccategory.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_topiccategory.setAccessibleName("")
        self.btn_add_topiccategory.setObjectName("btn_add_topiccategory")
        self.horizontalLayout_2.addWidget(self.btn_add_topiccategory)
        self.gridLayout_2.addWidget(self.widget_3, 11, 2, 1, 2)
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_freekeywords = QtWidgets.QPushButton(self.widget1)
        self.info_label_freekeywords.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_freekeywords.setFlat(True)
        self.info_label_freekeywords.setObjectName("info_label_freekeywords")
        self.horizontalLayout2.addWidget(self.info_label_freekeywords)
        self.label_freekeywords = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_freekeywords.setFont(font)
        self.label_freekeywords.setAccessibleName("")
        self.label_freekeywords.setObjectName("label_freekeywords")
        self.horizontalLayout2.addWidget(self.label_freekeywords)
        self.gridLayout_2.addWidget(self.widget1, 27, 0, 1, 1)
        self.btn_del_snimarkeywords = QtWidgets.QPushButton(self.widget)
        self.btn_del_snimarkeywords.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_snimarkeywords.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_snimarkeywords.setAccessibleName("")
        self.btn_del_snimarkeywords.setObjectName("btn_del_snimarkeywords")
        self.gridLayout_2.addWidget(self.btn_del_snimarkeywords, 16, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 20, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 20, 3, 1, 1)
        self.btn_del_wormskeyword = QtWidgets.QPushButton(self.widget)
        self.btn_del_wormskeyword.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_wormskeyword.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_wormskeyword.setObjectName("btn_del_wormskeyword")
        self.gridLayout_2.addWidget(self.btn_del_wormskeyword, 21, 1, 1, 1)
        self.widget_serviceClassification = QtWidgets.QWidget(self.widget)
        self.widget_serviceClassification.setObjectName("widget_serviceClassification")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_serviceClassification)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.info_label_serviceClassification = QtWidgets.QPushButton(self.widget_serviceClassification)
        self.info_label_serviceClassification.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_serviceClassification.setText("")
        self.info_label_serviceClassification.setFlat(True)
        self.info_label_serviceClassification.setObjectName("info_label_serviceClassification")
        self.horizontalLayout_3.addWidget(self.info_label_serviceClassification)
        self.label_serviceClassification = QtWidgets.QLabel(self.widget_serviceClassification)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_serviceClassification.setFont(font)
        self.label_serviceClassification.setObjectName("label_serviceClassification")
        self.horizontalLayout_3.addWidget(self.label_serviceClassification)
        self.gridLayout_2.addWidget(self.widget_serviceClassification, 0, 0, 1, 2)
        self.btn_del_inspire = QtWidgets.QPushButton(self.widget)
        self.btn_del_inspire.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_inspire.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_inspire.setAccessibleName("")
        self.btn_del_inspire.setObjectName("btn_del_inspire")
        self.gridLayout_2.addWidget(self.btn_del_inspire, 10, 1, 1, 1)
        self.widget_topic = QtWidgets.QWidget(self.widget)
        self.widget_topic.setObjectName("widget_topic")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget_topic)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_topiccategory = QtWidgets.QPushButton(self.widget_topic)
        self.info_label_topiccategory.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_topiccategory.setFlat(True)
        self.info_label_topiccategory.setObjectName("info_label_topiccategory")
        self.horizontalLayout3.addWidget(self.info_label_topiccategory)
        self.label_topiccategory = QtWidgets.QLabel(self.widget_topic)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_topiccategory.setFont(font)
        self.label_topiccategory.setAccessibleName("")
        self.label_topiccategory.setObjectName("label_topiccategory")
        self.horizontalLayout3.addWidget(self.label_topiccategory)
        self.gridLayout_2.addWidget(self.widget_topic, 5, 2, 1, 1)
        self.serviceClassification = QtWidgets.QListView(self.widget)
        self.serviceClassification.setMinimumSize(QtCore.QSize(0, 200))
        self.serviceClassification.setMaximumSize(QtCore.QSize(16777215, 200))
        self.serviceClassification.setObjectName("serviceClassification")
        self.gridLayout_2.addWidget(self.serviceClassification, 1, 0, 2, 3)
        self.widget2 = QtWidgets.QWidget(self.widget)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_snimarkeywords = QtWidgets.QPushButton(self.widget2)
        self.info_label_snimarkeywords.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_snimarkeywords.setFlat(True)
        self.info_label_snimarkeywords.setObjectName("info_label_snimarkeywords")
        self.horizontalLayout4.addWidget(self.info_label_snimarkeywords)
        self.label_snimarkeywords = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_snimarkeywords.setFont(font)
        self.label_snimarkeywords.setAccessibleName("")
        self.label_snimarkeywords.setObjectName("label_snimarkeywords")
        self.horizontalLayout4.addWidget(self.label_snimarkeywords)
        self.gridLayout_2.addWidget(self.widget2, 12, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 15, 3, 1, 1)
        self.btn_del_serviceClassification = QtWidgets.QPushButton(self.widget)
        self.btn_del_serviceClassification.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_serviceClassification.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_serviceClassification.setObjectName("btn_del_serviceClassification")
        self.gridLayout_2.addWidget(self.btn_del_serviceClassification, 2, 3, 1, 1)
        self.btn_open_wormskeywords = QtWidgets.QPushButton(self.widget)
        self.btn_open_wormskeywords.setObjectName("btn_open_wormskeywords")
        self.gridLayout_2.addWidget(self.btn_open_wormskeywords, 22, 0, 1, 1)
        self.wormskeywords = QtWidgets.QTableView(self.widget)
        self.wormskeywords.setMinimumSize(QtCore.QSize(0, 240))
        self.wormskeywords.setMaximumSize(QtCore.QSize(16777215, 240))
        self.wormskeywords.setObjectName("wormskeywords")
        self.gridLayout_2.addWidget(self.wormskeywords, 19, 0, 3, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.info_label_crossref = QtWidgets.QPushButton(self.widget_6)
        self.info_label_crossref.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_crossref.setText("")
        self.info_label_crossref.setFlat(True)
        self.info_label_crossref.setObjectName("info_label_crossref")
        self.horizontalLayout_6.addWidget(self.info_label_crossref)
        self.label_crossref = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_crossref.setFont(font)
        self.label_crossref.setObjectName("label_crossref")
        self.horizontalLayout_6.addWidget(self.label_crossref)
        self.horizontalLayout_6.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.widget_6, 18, 2, 1, 1)
        self.btn_del_crossrefkeyword = QtWidgets.QPushButton(self.widget)
        self.btn_del_crossrefkeyword.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_crossrefkeyword.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_crossrefkeyword.setObjectName("btn_del_crossrefkeyword")
        self.gridLayout_2.addWidget(self.btn_del_crossrefkeyword, 21, 3, 1, 1)
        self.btn_open_crossrefkeywords = QtWidgets.QPushButton(self.widget)
        self.btn_open_crossrefkeywords.setObjectName("btn_open_crossrefkeywords")
        self.gridLayout_2.addWidget(self.btn_open_crossrefkeywords, 22, 2, 1, 1)
        self.crossrefkeywords = QtWidgets.QTableView(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(240)
        sizePolicy.setHeightForWidth(self.crossrefkeywords.sizePolicy().hasHeightForWidth())
        self.crossrefkeywords.setSizePolicy(sizePolicy)
        self.crossrefkeywords.setMinimumSize(QtCore.QSize(0, 240))
        self.crossrefkeywords.setObjectName("crossrefkeywords")
        self.gridLayout_2.addWidget(self.crossrefkeywords, 20, 2, 2, 1)
        self.verticalLayout.addWidget(self.widget)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(keywords)
        QtCore.QMetaObject.connectSlotsByName(keywords)

    def retranslateUi(self, keywords):
        _translate = QtCore.QCoreApplication.translate
        keywords.setWindowTitle(_translate("keywords", "Form"))
        self.label_inspire.setText(_translate("keywords", "Temas INSPIRE*"))
        self.btn_open_freekeywords.setText(_translate("keywords", "Adicionar Palavra-Chave Livre"))
        self.label_worms.setText(_translate("keywords", "Palavras-Chave Worms"))
        self.btn_del_freekeywords.setText(_translate("keywords", "-"))
        self.btn_del_topiccategory.setText(_translate("keywords", "-"))
        self.btn_add_serviceClassification.setText(_translate("keywords", "+"))
        self.btn_add_inspire.setText(_translate("keywords", "+"))
        self.link_ckw.setText(_translate("keywords", "<a href=\"http://collab-keywords.snimar.pt/\"><img border=\"0\" alt=\"ckw Logo\" src=\":resourcesFolder/logo_ckw.png\"  >"))
        self.btn_update_snimar.setText(_translate("keywords", "Atualizar palavras"))
        self.btn_open_snimarkeywords.setText(_translate("keywords", "Adicionar Palavra-Chave SNIMar"))
        self.btn_add_topiccategory.setText(_translate("keywords", "+"))
        self.label_freekeywords.setText(_translate("keywords", "Palavras-Chave Livres"))
        self.btn_del_snimarkeywords.setText(_translate("keywords", "-"))
        self.btn_del_wormskeyword.setText(_translate("keywords", "-"))
        self.label_serviceClassification.setText(_translate("keywords", "Classificação dos Serviços*"))
        self.btn_del_inspire.setText(_translate("keywords", "-"))
        self.label_topiccategory.setText(_translate("keywords", "Categoria Temática*"))
        self.label_snimarkeywords.setText(_translate("keywords", "Palavras-Chave SNIMar*"))
        self.btn_del_serviceClassification.setText(_translate("keywords", "-"))
        self.btn_open_wormskeywords.setText(_translate("keywords", "Adicionar Palavra-Chave Worms"))
        self.label_crossref.setText(_translate("keywords", "Palavras-Chave Crossref"))
        self.btn_del_crossrefkeyword.setText(_translate("keywords", "-"))
        self.btn_open_crossrefkeywords.setText(_translate("keywords", "Adicionar Palavra-Chave CrossRef"))
