# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInforbiomares/snimarQtInterfaceView/templates/restrictionsPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_restrictions(object):
    def setupUi(self, restrictions):
        restrictions.setObjectName("restrictions")
        restrictions.resize(1080, 802)
        restrictions.setMinimumSize(QtCore.QSize(580, 0))
        self.gridLayout = QtWidgets.QGridLayout(restrictions)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(restrictions)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1078, 800))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_legalrestrictions = QtWidgets.QPushButton(self.widget1)
        self.info_label_legalrestrictions.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_legalrestrictions.setFlat(True)
        self.info_label_legalrestrictions.setObjectName("info_label_legalrestrictions")
        self.horizontalLayout.addWidget(self.info_label_legalrestrictions)
        self.label_legalrestrictions = QtWidgets.QLabel(self.widget1)
        self.label_legalrestrictions.setEnabled(True)
        self.label_legalrestrictions.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_legalrestrictions.setFont(font)
        self.label_legalrestrictions.setAccessibleName("")
        self.label_legalrestrictions.setObjectName("label_legalrestrictions")
        self.horizontalLayout.addWidget(self.label_legalrestrictions)
        self.gridLayout_2.addWidget(self.widget1, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.info_label_accessConstraints = QtWidgets.QPushButton(self.widget_4)
        self.info_label_accessConstraints.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_accessConstraints.setText("")
        self.info_label_accessConstraints.setFlat(True)
        self.info_label_accessConstraints.setObjectName("info_label_accessConstraints")
        self.horizontalLayout_3.addWidget(self.info_label_accessConstraints)
        self.label_accessConstraints = QtWidgets.QLabel(self.widget_4)
        self.label_accessConstraints.setObjectName("label_accessConstraints")
        self.horizontalLayout_3.addWidget(self.label_accessConstraints)
        self.gridLayout_2.addWidget(self.widget_4, 6, 0, 1, 1)
        self.btn_add_useLimitation = QtWidgets.QPushButton(self.widget)
        self.btn_add_useLimitation.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_useLimitation.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_useLimitation.setObjectName("btn_add_useLimitation")
        self.gridLayout_2.addWidget(self.btn_add_useLimitation, 5, 1, 1, 1)
        self.combo_accessConstraints = QtWidgets.QComboBox(self.widget)
        self.combo_accessConstraints.setObjectName("combo_accessConstraints")
        self.gridLayout_2.addWidget(self.combo_accessConstraints, 9, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.info_label_useLimitation = QtWidgets.QPushButton(self.widget_3)
        self.info_label_useLimitation.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_useLimitation.setText("")
        self.info_label_useLimitation.setFlat(True)
        self.info_label_useLimitation.setObjectName("info_label_useLimitation")
        self.horizontalLayout_2.addWidget(self.info_label_useLimitation)
        self.label_useLimitation = QtWidgets.QLabel(self.widget_3)
        self.label_useLimitation.setObjectName("label_useLimitation")
        self.horizontalLayout_2.addWidget(self.label_useLimitation)
        self.gridLayout_2.addWidget(self.widget_3, 2, 0, 1, 1)
        self.btn_del_useConstraints = QtWidgets.QPushButton(self.widget)
        self.btn_del_useConstraints.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_useConstraints.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_useConstraints.setObjectName("btn_del_useConstraints")
        self.gridLayout_2.addWidget(self.btn_del_useConstraints, 12, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.info_label_useConstraints = QtWidgets.QPushButton(self.widget_5)
        self.info_label_useConstraints.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_useConstraints.setText("")
        self.info_label_useConstraints.setFlat(True)
        self.info_label_useConstraints.setObjectName("info_label_useConstraints")
        self.horizontalLayout_4.addWidget(self.info_label_useConstraints)
        self.label_useConstraints = QtWidgets.QLabel(self.widget_5)
        self.label_useConstraints.setObjectName("label_useConstraints")
        self.horizontalLayout_4.addWidget(self.label_useConstraints)
        self.gridLayout_2.addWidget(self.widget_5, 10, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.info_label_otherConstraints = QtWidgets.QPushButton(self.widget_6)
        self.info_label_otherConstraints.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_otherConstraints.setText("")
        self.info_label_otherConstraints.setFlat(True)
        self.info_label_otherConstraints.setObjectName("info_label_otherConstraints")
        self.horizontalLayout_5.addWidget(self.info_label_otherConstraints)
        self.label_otherConstraints = QtWidgets.QLabel(self.widget_6)
        self.label_otherConstraints.setObjectName("label_otherConstraints")
        self.horizontalLayout_5.addWidget(self.label_otherConstraints)
        self.gridLayout_2.addWidget(self.widget_6, 14, 0, 1, 1)
        self.combo_useConstraints = QtWidgets.QComboBox(self.widget)
        self.combo_useConstraints.setObjectName("combo_useConstraints")
        self.gridLayout_2.addWidget(self.combo_useConstraints, 13, 0, 1, 1)
        self.line_otherConstraints = gui.QgsFilterLineEdit(self.widget)
        self.line_otherConstraints.setProperty("qgisRelation", "")
        self.line_otherConstraints.setObjectName("line_otherConstraints")
        self.gridLayout_2.addWidget(self.line_otherConstraints, 17, 0, 1, 1)
        self.btn_add_otherConstraints = QtWidgets.QPushButton(self.widget)
        self.btn_add_otherConstraints.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_otherConstraints.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_otherConstraints.setObjectName("btn_add_otherConstraints")
        self.gridLayout_2.addWidget(self.btn_add_otherConstraints, 17, 1, 1, 1)
        self.btn_del_useLimitation = QtWidgets.QPushButton(self.widget)
        self.btn_del_useLimitation.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_useLimitation.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_useLimitation.setObjectName("btn_del_useLimitation")
        self.gridLayout_2.addWidget(self.btn_del_useLimitation, 4, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 18, 0, 1, 1)
        self.line_useLimitation = gui.QgsFilterLineEdit(self.widget)
        self.line_useLimitation.setProperty("qgisRelation", "")
        self.line_useLimitation.setObjectName("line_useLimitation")
        self.gridLayout_2.addWidget(self.line_useLimitation, 5, 0, 1, 1)
        self.btn_add_accessConstraints = QtWidgets.QPushButton(self.widget)
        self.btn_add_accessConstraints.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_accessConstraints.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_accessConstraints.setObjectName("btn_add_accessConstraints")
        self.gridLayout_2.addWidget(self.btn_add_accessConstraints, 9, 1, 1, 1)
        self.btn_del_accessConstraints = QtWidgets.QPushButton(self.widget)
        self.btn_del_accessConstraints.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_accessConstraints.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_accessConstraints.setObjectName("btn_del_accessConstraints")
        self.gridLayout_2.addWidget(self.btn_del_accessConstraints, 8, 1, 1, 1)
        self.btn_add_useConstraints = QtWidgets.QPushButton(self.widget)
        self.btn_add_useConstraints.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_useConstraints.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_useConstraints.setObjectName("btn_add_useConstraints")
        self.gridLayout_2.addWidget(self.btn_add_useConstraints, 13, 1, 1, 1)
        self.btn_del_otherConstraints = QtWidgets.QPushButton(self.widget)
        self.btn_del_otherConstraints.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_otherConstraints.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_otherConstraints.setObjectName("btn_del_otherConstraints")
        self.gridLayout_2.addWidget(self.btn_del_otherConstraints, 16, 1, 1, 1)
        self.otherConstraints = QtWidgets.QListView(self.widget)
        self.otherConstraints.setObjectName("otherConstraints")
        self.gridLayout_2.addWidget(self.otherConstraints, 15, 0, 2, 1)
        self.useConstraints = QtWidgets.QListView(self.widget)
        self.useConstraints.setObjectName("useConstraints")
        self.gridLayout_2.addWidget(self.useConstraints, 11, 0, 2, 1)
        self.accessConstraints = QtWidgets.QListView(self.widget)
        self.accessConstraints.setObjectName("accessConstraints")
        self.gridLayout_2.addWidget(self.accessConstraints, 7, 0, 2, 1)
        self.useLimitation = QtWidgets.QListView(self.widget)
        self.useLimitation.setObjectName("useLimitation")
        self.gridLayout_2.addWidget(self.useLimitation, 3, 0, 2, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.combo_securityrestrictions = QtWidgets.QComboBox(self.widget_2)
        self.combo_securityrestrictions.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_securityrestrictions.setObjectName("combo_securityrestrictions")
        self.gridLayout_3.addWidget(self.combo_securityrestrictions, 4, 0, 1, 3)
        self.securityrestrictions = QtWidgets.QListView(self.widget_2)
        self.securityrestrictions.setMinimumSize(QtCore.QSize(0, 0))
        self.securityrestrictions.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.securityrestrictions.setAccessibleName("")
        self.securityrestrictions.setObjectName("securityrestrictions")
        self.gridLayout_3.addWidget(self.securityrestrictions, 1, 0, 2, 3)
        self.btn_del_securityrestrictions = QtWidgets.QPushButton(self.widget_2)
        self.btn_del_securityrestrictions.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_securityrestrictions.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_securityrestrictions.setAccessibleName("")
        self.btn_del_securityrestrictions.setObjectName("btn_del_securityrestrictions")
        self.gridLayout_3.addWidget(self.btn_del_securityrestrictions, 2, 3, 1, 1)
        self.btn_add_securityrestrictions = QtWidgets.QPushButton(self.widget_2)
        self.btn_add_securityrestrictions.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_securityrestrictions.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_securityrestrictions.setAccessibleName("")
        self.btn_add_securityrestrictions.setObjectName("btn_add_securityrestrictions")
        self.gridLayout_3.addWidget(self.btn_add_securityrestrictions, 4, 3, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.widget_2)
        self.widget2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_securityrestrictions = QtWidgets.QPushButton(self.widget2)
        self.info_label_securityrestrictions.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_securityrestrictions.setFlat(True)
        self.info_label_securityrestrictions.setObjectName("info_label_securityrestrictions")
        self.horizontalLayout1.addWidget(self.info_label_securityrestrictions)
        self.label_securityrestrictions = QtWidgets.QLabel(self.widget2)
        self.label_securityrestrictions.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_securityrestrictions.setFont(font)
        self.label_securityrestrictions.setAccessibleName("")
        self.label_securityrestrictions.setObjectName("label_securityrestrictions")
        self.horizontalLayout1.addWidget(self.label_securityrestrictions)
        self.gridLayout_3.addWidget(self.widget2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(restrictions)
        QtCore.QMetaObject.connectSlotsByName(restrictions)

    def retranslateUi(self, restrictions):
        _translate = QtCore.QCoreApplication.translate
        restrictions.setWindowTitle(_translate("restrictions", "Form"))
        self.label_legalrestrictions.setText(_translate("restrictions", "Restrições Legais*"))
        self.label_accessConstraints.setText(_translate("restrictions", "Restrições ao Acesso"))
        self.btn_add_useLimitation.setText(_translate("restrictions", "+"))
        self.label_useLimitation.setText(_translate("restrictions", "Limitações ao Uso "))
        self.btn_del_useConstraints.setText(_translate("restrictions", "-"))
        self.label_useConstraints.setText(_translate("restrictions", "Restrições ao Uso "))
        self.label_otherConstraints.setText(_translate("restrictions", "Outras Restrições"))
        self.btn_add_otherConstraints.setText(_translate("restrictions", "+"))
        self.btn_del_useLimitation.setText(_translate("restrictions", "-"))
        self.btn_add_accessConstraints.setText(_translate("restrictions", "+"))
        self.btn_del_accessConstraints.setText(_translate("restrictions", "-"))
        self.btn_add_useConstraints.setText(_translate("restrictions", "+"))
        self.btn_del_otherConstraints.setText(_translate("restrictions", "-"))
        self.btn_del_securityrestrictions.setText(_translate("restrictions", "-"))
        self.btn_add_securityrestrictions.setText(_translate("restrictions", "+"))
        self.label_securityrestrictions.setText(_translate("restrictions", "Restrições de Segurança"))
from qgis import gui
