# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInfobiomares/snimarQtInterfaceView/templates/geographicinformationPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_geographicinfo(object):
    def setupUi(self, geographicinfo):
        geographicinfo.setObjectName("geographicinfo")
        geographicinfo.resize(665, 747)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(geographicinfo.sizePolicy().hasHeightForWidth())
        geographicinfo.setSizePolicy(sizePolicy)
        geographicinfo.setMinimumSize(QtCore.QSize(580, 0))
        self.gridLayout = QtWidgets.QGridLayout(geographicinfo)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(geographicinfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 647, 1052))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 7, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_boundingbox = QtWidgets.QPushButton(self.widget1)
        self.info_label_boundingbox.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_boundingbox.setFlat(True)
        self.info_label_boundingbox.setObjectName("info_label_boundingbox")
        self.horizontalLayout.addWidget(self.info_label_boundingbox)
        self.label_boundingbox = QtWidgets.QLabel(self.widget1)
        self.label_boundingbox.setAccessibleName("")
        self.label_boundingbox.setObjectName("label_boundingbox")
        self.horizontalLayout.addWidget(self.label_boundingbox)
        self.gridLayout_2.addWidget(self.widget1, 1, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.widget)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_geo_ext = QtWidgets.QPushButton(self.widget2)
        self.info_label_geo_ext.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_geo_ext.setFlat(True)
        self.info_label_geo_ext.setObjectName("info_label_geo_ext")
        self.horizontalLayout1.addWidget(self.info_label_geo_ext)
        self.label_geo_ext = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_geo_ext.setFont(font)
        self.label_geo_ext.setAccessibleName("")
        self.label_geo_ext.setObjectName("label_geo_ext")
        self.horizontalLayout1.addWidget(self.label_geo_ext)
        self.gridLayout_2.addWidget(self.widget2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 2, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.widget)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_geographicidentifier = QtWidgets.QPushButton(self.widget3)
        self.info_label_geographicidentifier.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_geographicidentifier.setFlat(True)
        self.info_label_geographicidentifier.setObjectName("info_label_geographicidentifier")
        self.horizontalLayout2.addWidget(self.info_label_geographicidentifier)
        self.label_geographicidentifier = QtWidgets.QLabel(self.widget3)
        self.label_geographicidentifier.setAccessibleName("")
        self.label_geographicidentifier.setObjectName("label_geographicidentifier")
        self.horizontalLayout2.addWidget(self.label_geographicidentifier)
        self.gridLayout_2.addWidget(self.widget3, 6, 0, 1, 1)
        self.btn_del_geographicidentifier = QtWidgets.QPushButton(self.widget)
        self.btn_del_geographicidentifier.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_geographicidentifier.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_geographicidentifier.setAccessibleName("")
        self.btn_del_geographicidentifier.setObjectName("btn_del_geographicidentifier")
        self.gridLayout_2.addWidget(self.btn_del_geographicidentifier, 8, 2, 1, 1)
        self.btn_del_boundingbox = QtWidgets.QPushButton(self.widget)
        self.btn_del_boundingbox.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_boundingbox.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_boundingbox.setAccessibleName("")
        self.btn_del_boundingbox.setObjectName("btn_del_boundingbox")
        self.gridLayout_2.addWidget(self.btn_del_boundingbox, 3, 2, 1, 1)
        self.btn_open_boundingbox = QtWidgets.QPushButton(self.widget)
        self.btn_open_boundingbox.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_open_boundingbox.setObjectName("btn_open_boundingbox")
        self.gridLayout_2.addWidget(self.btn_open_boundingbox, 5, 0, 1, 2)
        self.extent_btn = QtWidgets.QPushButton(self.widget)
        self.extent_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.extent_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.extent_btn.setObjectName("extent_btn")
        self.gridLayout_2.addWidget(self.extent_btn, 5, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setHorizontalSpacing(4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_identifier = gui.QgsFilterLineEdit(self.widget)
        self.line_identifier.setMinimumSize(QtCore.QSize(50, 30))
        self.line_identifier.setProperty("qgisRelation", "")
        self.line_identifier.setObjectName("line_identifier")
        self.gridLayout_5.addWidget(self.line_identifier, 0, 0, 1, 1)
        self.check_haveResource = QtWidgets.QCheckBox(self.widget)
        self.check_haveResource.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_haveResource.setObjectName("check_haveResource")
        self.gridLayout_5.addWidget(self.check_haveResource, 0, 1, 1, 1)
        self.btn_add_geographicidentifier = QtWidgets.QPushButton(self.widget)
        self.btn_add_geographicidentifier.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_geographicidentifier.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_geographicidentifier.setAccessibleName("")
        self.btn_add_geographicidentifier.setObjectName("btn_add_geographicidentifier")
        self.gridLayout_5.addWidget(self.btn_add_geographicidentifier, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 10, 0, 1, 3)
        self.boundingbox = QtWidgets.QTableView(self.widget)
        self.boundingbox.setMinimumSize(QtCore.QSize(0, 240))
        self.boundingbox.setMaximumSize(QtCore.QSize(16777215, 240))
        self.boundingbox.setAccessibleName("")
        self.boundingbox.setObjectName("boundingbox")
        self.boundingbox.verticalHeader().setDefaultSectionSize(0)
        self.gridLayout_2.addWidget(self.boundingbox, 2, 0, 2, 2)
        self.geographicidentifier = QtWidgets.QTableView(self.widget)
        self.geographicidentifier.setMinimumSize(QtCore.QSize(0, 180))
        self.geographicidentifier.setMaximumSize(QtCore.QSize(16777215, 180))
        self.geographicidentifier.setAccessibleName("")
        self.geographicidentifier.setObjectName("geographicidentifier")
        self.geographicidentifier.verticalHeader().setDefaultSectionSize(0)
        self.gridLayout_2.addWidget(self.geographicidentifier, 7, 0, 2, 2)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.referencesystem = QtWidgets.QListView(self.widget_2)
        self.referencesystem.setMinimumSize(QtCore.QSize(0, 180))
        self.referencesystem.setMaximumSize(QtCore.QSize(16777215, 180))
        self.referencesystem.setAccessibleName("")
        self.referencesystem.setObjectName("referencesystem")
        self.gridLayout_3.addWidget(self.referencesystem, 1, 0, 3, 1)
        self.combo_referencesystem = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_referencesystem.sizePolicy().hasHeightForWidth())
        self.combo_referencesystem.setSizePolicy(sizePolicy)
        self.combo_referencesystem.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_referencesystem.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.combo_referencesystem.setInputMethodHints(QtCore.Qt.ImhNone)
        self.combo_referencesystem.setEditable(False)
        self.combo_referencesystem.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.combo_referencesystem.setObjectName("combo_referencesystem")
        self.gridLayout_3.addWidget(self.combo_referencesystem, 4, 0, 1, 1)
        self.widget4 = QtWidgets.QWidget(self.widget_2)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_referencesystem = QtWidgets.QPushButton(self.widget4)
        self.info_label_referencesystem.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_referencesystem.setFlat(True)
        self.info_label_referencesystem.setObjectName("info_label_referencesystem")
        self.horizontalLayout3.addWidget(self.info_label_referencesystem)
        self.label_referencesystem = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_referencesystem.setFont(font)
        self.label_referencesystem.setAccessibleName("")
        self.label_referencesystem.setObjectName("label_referencesystem")
        self.horizontalLayout3.addWidget(self.label_referencesystem)
        self.gridLayout_3.addWidget(self.widget4, 0, 0, 1, 1)
        self.btn_add_referencesystem = QtWidgets.QPushButton(self.widget_2)
        self.btn_add_referencesystem.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_referencesystem.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_referencesystem.setObjectName("btn_add_referencesystem")
        self.gridLayout_3.addWidget(self.btn_add_referencesystem, 4, 1, 1, 1)
        self.btn_del_referencesystem = QtWidgets.QPushButton(self.widget_2)
        self.btn_del_referencesystem.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_referencesystem.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_referencesystem.setAccessibleName("")
        self.btn_del_referencesystem.setObjectName("btn_del_referencesystem")
        self.gridLayout_3.addWidget(self.btn_del_referencesystem, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 1, 2, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.referencesystemidentifier = QtWidgets.QComboBox(self.widget_3)
        self.referencesystemidentifier.setAccessibleName("")
        self.referencesystemidentifier.setObjectName("referencesystemidentifier")
        self.gridLayout_4.addWidget(self.referencesystemidentifier, 6, 0, 1, 1)
        self.widget5 = QtWidgets.QWidget(self.widget_3)
        self.widget5.setObjectName("widget5")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_vertical_extent = QtWidgets.QPushButton(self.widget5)
        self.info_label_vertical_extent.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_vertical_extent.setFlat(True)
        self.info_label_vertical_extent.setObjectName("info_label_vertical_extent")
        self.horizontalLayout4.addWidget(self.info_label_vertical_extent)
        self.label_vertical_extent = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_vertical_extent.setFont(font)
        self.label_vertical_extent.setAccessibleName("")
        self.label_vertical_extent.setObjectName("label_vertical_extent")
        self.horizontalLayout4.addWidget(self.label_vertical_extent)
        self.gridLayout_4.addWidget(self.widget5, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.minimumValue = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.minimumValue.setMinimumSize(QtCore.QSize(0, 30))
        self.minimumValue.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.minimumValue.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.minimumValue.setDecimals(4)
        self.minimumValue.setMinimum(-999999999.0)
        self.minimumValue.setMaximum(999999999.0)
        self.minimumValue.setSingleStep(0.0)
        self.minimumValue.setProperty("value", -999999999.0)
        self.minimumValue.setObjectName("minimumValue")
        self.gridLayout_7.addWidget(self.minimumValue, 1, 0, 1, 1)
        self.maximumValue = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.maximumValue.setMinimumSize(QtCore.QSize(0, 30))
        self.maximumValue.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.maximumValue.setFrame(True)
        self.maximumValue.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.maximumValue.setDecimals(4)
        self.maximumValue.setMinimum(-999999999.0)
        self.maximumValue.setMaximum(999999999.0)
        self.maximumValue.setSingleStep(0.0)
        self.maximumValue.setProperty("value", -999999999.0)
        self.maximumValue.setObjectName("maximumValue")
        self.gridLayout_7.addWidget(self.maximumValue, 1, 1, 1, 1)
        self.btn_clear_all = QtWidgets.QPushButton(self.widget_4)
        self.btn_clear_all.setMinimumSize(QtCore.QSize(30, 0))
        self.btn_clear_all.setMaximumSize(QtCore.QSize(140, 16777215))
        self.btn_clear_all.setObjectName("btn_clear_all")
        self.gridLayout_7.addWidget(self.btn_clear_all, 1, 2, 1, 1)
        self.label_minimumValue = QtWidgets.QLabel(self.widget_4)
        self.label_minimumValue.setAccessibleName("")
        self.label_minimumValue.setObjectName("label_minimumValue")
        self.gridLayout_7.addWidget(self.label_minimumValue, 0, 0, 1, 1)
        self.label_maximumValue = QtWidgets.QLabel(self.widget_4)
        self.label_maximumValue.setAccessibleName("")
        self.label_maximumValue.setObjectName("label_maximumValue")
        self.gridLayout_7.addWidget(self.label_maximumValue, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_4, 1, 0, 1, 2)
        self.widget6 = QtWidgets.QWidget(self.widget_3)
        self.widget6.setObjectName("widget6")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setSpacing(0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.info_label_referencesystemidentifier = QtWidgets.QPushButton(self.widget6)
        self.info_label_referencesystemidentifier.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_referencesystemidentifier.setFlat(True)
        self.info_label_referencesystemidentifier.setObjectName("info_label_referencesystemidentifier")
        self.horizontalLayout5.addWidget(self.info_label_referencesystemidentifier)
        self.label_referencesystemidentifier = QtWidgets.QLabel(self.widget6)
        self.label_referencesystemidentifier.setAccessibleName("")
        self.label_referencesystemidentifier.setObjectName("label_referencesystemidentifier")
        self.horizontalLayout5.addWidget(self.label_referencesystemidentifier)
        self.gridLayout_4.addWidget(self.widget6, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(geographicinfo)
        QtCore.QMetaObject.connectSlotsByName(geographicinfo)

    def retranslateUi(self, geographicinfo):
        _translate = QtCore.QCoreApplication.translate
        geographicinfo.setWindowTitle(_translate("geographicinfo", "Form"))
        self.label_boundingbox.setText(_translate("geographicinfo", "Localização Geográfica"))
        self.label_geo_ext.setText(_translate("geographicinfo", "Extensão Geográfica*"))
        self.label_geographicidentifier.setText(_translate("geographicinfo", "Identificador Geográfico"))
        self.btn_del_geographicidentifier.setText(_translate("geographicinfo", "-"))
        self.btn_del_boundingbox.setText(_translate("geographicinfo", "-"))
        self.btn_open_boundingbox.setText(_translate("geographicinfo", "Adicionar Localização"))
        self.extent_btn.setText(_translate("geographicinfo", "ext"))
        self.line_identifier.setPlaceholderText(_translate("geographicinfo", "Identificador Geográfico..."))
        self.check_haveResource.setText(_translate("geographicinfo", "Contém Recurso"))
        self.btn_add_geographicidentifier.setText(_translate("geographicinfo", "+"))
        self.label_referencesystem.setText(_translate("geographicinfo", "Sistema de Referência*"))
        self.btn_add_referencesystem.setText(_translate("geographicinfo", "+"))
        self.btn_del_referencesystem.setText(_translate("geographicinfo", "-"))
        self.label_vertical_extent.setText(_translate("geographicinfo", "Extensão Altimétrica"))
        self.minimumValue.setSpecialValueText(_translate("geographicinfo", "Sem Valor"))
        self.maximumValue.setSpecialValueText(_translate("geographicinfo", "Sem Valor"))
        self.btn_clear_all.setText(_translate("geographicinfo", "Limpar Valores"))
        self.label_minimumValue.setText(_translate("geographicinfo", "Valor Mínimo (Metros)"))
        self.label_maximumValue.setText(_translate("geographicinfo", "Valor Máximo(Metros)"))
        self.label_referencesystemidentifier.setText(_translate("geographicinfo", "Identificador do Sistema de Referência"))
from qgis import gui
