# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInfobiomares/snimarQtInterfaceView/templates/identificationPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_identification(object):
    def setupUi(self, identification):
        identification.setObjectName("identification")
        identification.resize(822, 879)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(identification.sizePolicy().hasHeightForWidth())
        identification.setSizePolicy(sizePolicy)
        identification.setMinimumSize(QtCore.QSize(580, 0))
        self.gridLayout = QtWidgets.QGridLayout(identification)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(identification)
        self.scrollArea.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -933, 808, 2026))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.serviceType = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.serviceType.setMinimumSize(QtCore.QSize(0, 30))
        self.serviceType.setObjectName("serviceType")
        self.gridLayout_2.addWidget(self.serviceType, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 9, 0, 1, 2)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_hierarchylevel = QtWidgets.QPushButton(self.widget)
        self.info_label_hierarchylevel.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_hierarchylevel.setFlat(True)
        self.info_label_hierarchylevel.setObjectName("info_label_hierarchylevel")
        self.horizontalLayout.addWidget(self.info_label_hierarchylevel)
        self.label_hierarchylevel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_hierarchylevel.setFont(font)
        self.label_hierarchylevel.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_hierarchylevel.setObjectName("label_hierarchylevel")
        self.horizontalLayout.addWidget(self.label_hierarchylevel)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.purpose = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.purpose.setMinimumSize(QtCore.QSize(0, 90))
        self.purpose.setMaximumSize(QtCore.QSize(16777215, 90))
        self.purpose.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.purpose.setObjectName("purpose")
        self.gridLayout_2.addWidget(self.purpose, 23, 0, 1, 2)
        self.hierarchylevel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.hierarchylevel.setMinimumSize(QtCore.QSize(0, 30))
        self.hierarchylevel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.hierarchylevel.setObjectName("hierarchylevel")
        self.gridLayout_2.addWidget(self.hierarchylevel, 1, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_alternatetitle = QtWidgets.QPushButton(self.widget1)
        self.info_label_alternatetitle.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_alternatetitle.setFlat(True)
        self.info_label_alternatetitle.setObjectName("info_label_alternatetitle")
        self.horizontalLayout1.addWidget(self.info_label_alternatetitle)
        self.label_alternatetitle = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_alternatetitle.setFont(font)
        self.label_alternatetitle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_alternatetitle.setObjectName("label_alternatetitle")
        self.horizontalLayout1.addWidget(self.label_alternatetitle)
        self.gridLayout_2.addWidget(self.widget1, 19, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_purpose = QtWidgets.QPushButton(self.widget2)
        self.info_label_purpose.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_purpose.setFlat(True)
        self.info_label_purpose.setObjectName("info_label_purpose")
        self.horizontalLayout2.addWidget(self.info_label_purpose)
        self.label_purpose = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_purpose.setFont(font)
        self.label_purpose.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_purpose.setObjectName("label_purpose")
        self.horizontalLayout2.addWidget(self.label_purpose)
        self.gridLayout_2.addWidget(self.widget2, 22, 0, 1, 1)
        self.alternatetitle = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.alternatetitle.setMinimumSize(QtCore.QSize(58, 30))
        self.alternatetitle.setMouseTracking(False)
        self.alternatetitle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.alternatetitle.setInputMethodHints(QtCore.Qt.ImhNone)
        self.alternatetitle.setProperty("qgisRelation", "")
        self.alternatetitle.setObjectName("alternatetitle")
        self.gridLayout_2.addWidget(self.alternatetitle, 20, 0, 1, 2)
        self.widget_service = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_service.setObjectName("widget_service")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_service)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.info_label_serviceType = QtWidgets.QPushButton(self.widget_service)
        self.info_label_serviceType.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_serviceType.setText("")
        self.info_label_serviceType.setFlat(True)
        self.info_label_serviceType.setObjectName("info_label_serviceType")
        self.horizontalLayout_2.addWidget(self.info_label_serviceType)
        self.label_serviceType = QtWidgets.QLabel(self.widget_service)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_serviceType.setFont(font)
        self.label_serviceType.setObjectName("label_serviceType")
        self.horizontalLayout_2.addWidget(self.label_serviceType)
        self.gridLayout_2.addWidget(self.widget_service, 2, 0, 1, 1)
        self.widget_coupling = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_coupling.setObjectName("widget_coupling")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_coupling)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.info_label_couplingType = QtWidgets.QPushButton(self.widget_coupling)
        self.info_label_couplingType.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_couplingType.setText("")
        self.info_label_couplingType.setFlat(True)
        self.info_label_couplingType.setObjectName("info_label_couplingType")
        self.horizontalLayout_5.addWidget(self.info_label_couplingType)
        self.label_couplingType = QtWidgets.QLabel(self.widget_coupling)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_couplingType.setFont(font)
        self.label_couplingType.setObjectName("label_couplingType")
        self.horizontalLayout_5.addWidget(self.label_couplingType)
        self.gridLayout_2.addWidget(self.widget_coupling, 2, 1, 1, 1)
        self.couplingType = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.couplingType.setMinimumSize(QtCore.QSize(0, 30))
        self.couplingType.setObjectName("couplingType")
        self.gridLayout_2.addWidget(self.couplingType, 3, 1, 1, 1)
        self.gtyugfv = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gtyugfv.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gtyugfv.setObjectName("gtyugfv")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gtyugfv)
        self.verticalLayout_3.setContentsMargins(0, 4, 4, 4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget3 = QtWidgets.QWidget(self.gtyugfv)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_titleEN = QtWidgets.QPushButton(self.widget3)
        self.info_label_titleEN.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_titleEN.setFlat(True)
        self.info_label_titleEN.setObjectName("info_label_titleEN")
        self.horizontalLayout3.addWidget(self.info_label_titleEN)
        self.label_titleEN = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_titleEN.setFont(font)
        self.label_titleEN.setObjectName("label_titleEN")
        self.horizontalLayout3.addWidget(self.label_titleEN)
        self.verticalLayout_3.addWidget(self.widget3)
        self.titleEN = gui.QgsFilterLineEdit(self.gtyugfv)
        self.titleEN.setMinimumSize(QtCore.QSize(58, 30))
        self.titleEN.setProperty("qgisRelation", "")
        self.titleEN.setObjectName("titleEN")
        self.verticalLayout_3.addWidget(self.titleEN)
        self.widget4 = QtWidgets.QWidget(self.gtyugfv)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_abstractEN = QtWidgets.QPushButton(self.widget4)
        self.info_label_abstractEN.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_abstractEN.setFlat(True)
        self.info_label_abstractEN.setObjectName("info_label_abstractEN")
        self.horizontalLayout4.addWidget(self.info_label_abstractEN)
        self.label_abstractEN = QtWidgets.QLabel(self.widget4)
        self.label_abstractEN.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_abstractEN.setObjectName("label_abstractEN")
        self.horizontalLayout4.addWidget(self.label_abstractEN)
        self.verticalLayout_3.addWidget(self.widget4)
        self.abstractEN = QtWidgets.QPlainTextEdit(self.gtyugfv)
        self.abstractEN.setMinimumSize(QtCore.QSize(0, 90))
        self.abstractEN.setMaximumSize(QtCore.QSize(16777215, 90))
        self.abstractEN.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.abstractEN.setObjectName("abstractEN")
        self.verticalLayout_3.addWidget(self.abstractEN)
        self.gridLayout_2.addWidget(self.gtyugfv, 11, 0, 1, 2)
        self.group = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.group.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.group.setObjectName("group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group)
        self.verticalLayout_2.setContentsMargins(0, 4, 4, 4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget5 = QtWidgets.QWidget(self.group)
        self.widget5.setObjectName("widget5")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setSpacing(0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.info_label_title = QtWidgets.QPushButton(self.widget5)
        self.info_label_title.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_title.setFlat(True)
        self.info_label_title.setObjectName("info_label_title")
        self.horizontalLayout5.addWidget(self.info_label_title)
        self.label_title = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout5.addWidget(self.label_title)
        self.verticalLayout_2.addWidget(self.widget5)
        self.title = gui.QgsFilterLineEdit(self.group)
        self.title.setMinimumSize(QtCore.QSize(58, 30))
        self.title.setProperty("qgisRelation", "")
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.widget6 = QtWidgets.QWidget(self.group)
        self.widget6.setObjectName("widget6")
        self.horizontalLayout6 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout6.setSpacing(0)
        self.horizontalLayout6.setObjectName("horizontalLayout6")
        self.info_label_abstract = QtWidgets.QPushButton(self.widget6)
        self.info_label_abstract.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_abstract.setFlat(True)
        self.info_label_abstract.setObjectName("info_label_abstract")
        self.horizontalLayout6.addWidget(self.info_label_abstract)
        self.label_abstract = QtWidgets.QLabel(self.widget6)
        self.label_abstract.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_abstract.setObjectName("label_abstract")
        self.horizontalLayout6.addWidget(self.label_abstract)
        self.verticalLayout_2.addWidget(self.widget6)
        self.abstract_ = QtWidgets.QPlainTextEdit(self.group)
        self.abstract_.setMinimumSize(QtCore.QSize(0, 90))
        self.abstract_.setMaximumSize(QtCore.QSize(16777215, 90))
        self.abstract_.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.abstract_.setObjectName("abstract_")
        self.verticalLayout_2.addWidget(self.abstract_)
        self.gridLayout_2.addWidget(self.group, 4, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.widget7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.widget7.setObjectName("widget7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget7)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget8 = QtWidgets.QWidget(self.widget7)
        self.widget8.setObjectName("widget8")
        self.horizontalLayout7 = QtWidgets.QHBoxLayout(self.widget8)
        self.horizontalLayout7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout7.setSpacing(0)
        self.horizontalLayout7.setObjectName("horizontalLayout7")
        self.info_label_resourcemaintenance = QtWidgets.QPushButton(self.widget8)
        self.info_label_resourcemaintenance.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_resourcemaintenance.setFlat(True)
        self.info_label_resourcemaintenance.setObjectName("info_label_resourcemaintenance")
        self.horizontalLayout7.addWidget(self.info_label_resourcemaintenance)
        self.label_resourcemaintenance = QtWidgets.QLabel(self.widget8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_resourcemaintenance.setFont(font)
        self.label_resourcemaintenance.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_resourcemaintenance.setObjectName("label_resourcemaintenance")
        self.horizontalLayout7.addWidget(self.label_resourcemaintenance)
        self.gridLayout_5.addWidget(self.widget8, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 1, 1, 1, 1)
        self.btn_add_resourcemaintenance = QtWidgets.QPushButton(self.widget7)
        self.btn_add_resourcemaintenance.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_resourcemaintenance.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_resourcemaintenance.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_add_resourcemaintenance.setObjectName("btn_add_resourcemaintenance")
        self.gridLayout_5.addWidget(self.btn_add_resourcemaintenance, 3, 3, 1, 1)
        self.credits = QtWidgets.QListView(self.widget7)
        self.credits.setMinimumSize(QtCore.QSize(0, 90))
        self.credits.setMaximumSize(QtCore.QSize(16777215, 90))
        self.credits.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.credits.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.credits.setSelectionRectVisible(True)
        self.credits.setObjectName("credits")
        self.gridLayout_5.addWidget(self.credits, 1, 0, 2, 1)
        self.widget9 = QtWidgets.QWidget(self.widget7)
        self.widget9.setObjectName("widget9")
        self.horizontalLayout8 = QtWidgets.QHBoxLayout(self.widget9)
        self.horizontalLayout8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout8.setSpacing(0)
        self.horizontalLayout8.setObjectName("horizontalLayout8")
        self.info_label_credits = QtWidgets.QPushButton(self.widget9)
        self.info_label_credits.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_credits.setFlat(True)
        self.info_label_credits.setObjectName("info_label_credits")
        self.horizontalLayout8.addWidget(self.info_label_credits)
        self.label_credits = QtWidgets.QLabel(self.widget9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_credits.setFont(font)
        self.label_credits.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout8.addWidget(self.label_credits)
        self.gridLayout_5.addWidget(self.widget9, 0, 0, 1, 1)
        self.resourcemaintenance = QtWidgets.QListView(self.widget7)
        self.resourcemaintenance.setMinimumSize(QtCore.QSize(0, 90))
        self.resourcemaintenance.setMaximumSize(QtCore.QSize(16777215, 90))
        self.resourcemaintenance.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.resourcemaintenance.setObjectName("resourcemaintenance")
        self.gridLayout_5.addWidget(self.resourcemaintenance, 1, 2, 2, 1)
        self.btn_del_resourcemaintenance = QtWidgets.QPushButton(self.widget7)
        self.btn_del_resourcemaintenance.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_resourcemaintenance.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_resourcemaintenance.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_del_resourcemaintenance.setObjectName("btn_del_resourcemaintenance")
        self.gridLayout_5.addWidget(self.btn_del_resourcemaintenance, 2, 3, 1, 1)
        self.combo_resourcemaintenance = QtWidgets.QComboBox(self.widget7)
        self.combo_resourcemaintenance.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_resourcemaintenance.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.combo_resourcemaintenance.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.combo_resourcemaintenance.setObjectName("combo_resourcemaintenance")
        self.gridLayout_5.addWidget(self.combo_resourcemaintenance, 3, 2, 1, 1)
        self.line_credits = gui.QgsFilterLineEdit(self.widget7)
        self.line_credits.setMinimumSize(QtCore.QSize(58, 30))
        self.line_credits.setText("")
        self.line_credits.setProperty("qgisRelation", "")
        self.line_credits.setObjectName("line_credits")
        self.gridLayout_5.addWidget(self.line_credits, 3, 0, 1, 1)
        self.btn_add_credits = QtWidgets.QPushButton(self.widget7)
        self.btn_add_credits.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_credits.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_credits.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_add_credits.setObjectName("btn_add_credits")
        self.gridLayout_5.addWidget(self.btn_add_credits, 3, 1, 1, 1)
        self.btn_del_credits = QtWidgets.QPushButton(self.widget7)
        self.btn_del_credits.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_credits.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_credits.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_del_credits.setObjectName("btn_del_credits")
        self.gridLayout_5.addWidget(self.btn_del_credits, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget7)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget10 = QtWidgets.QWidget(self.widget_2)
        self.widget10.setObjectName("widget10")
        self.horizontalLayout9 = QtWidgets.QHBoxLayout(self.widget10)
        self.horizontalLayout9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout9.setSpacing(0)
        self.horizontalLayout9.setObjectName("horizontalLayout9")
        self.info_label_identifiers = QtWidgets.QPushButton(self.widget10)
        self.info_label_identifiers.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_identifiers.setFlat(True)
        self.info_label_identifiers.setObjectName("info_label_identifiers")
        self.horizontalLayout9.addWidget(self.info_label_identifiers)
        self.label_identifiers = QtWidgets.QLabel(self.widget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_identifiers.sizePolicy().hasHeightForWidth())
        self.label_identifiers.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_identifiers.setFont(font)
        self.label_identifiers.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_identifiers.setScaledContents(False)
        self.label_identifiers.setObjectName("label_identifiers")
        self.horizontalLayout9.addWidget(self.label_identifiers)
        self.gridLayout_6.addWidget(self.widget10, 0, 0, 1, 1)
        self.identifiers = QtWidgets.QTableView(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.identifiers.sizePolicy().hasHeightForWidth())
        self.identifiers.setSizePolicy(sizePolicy)
        self.identifiers.setMinimumSize(QtCore.QSize(0, 180))
        self.identifiers.setMaximumSize(QtCore.QSize(16777215, 180))
        self.identifiers.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.identifiers.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.identifiers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.identifiers.setObjectName("identifiers")
        self.gridLayout_6.addWidget(self.identifiers, 1, 0, 2, 1)
        self.btn_del_identifiers = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_identifiers.sizePolicy().hasHeightForWidth())
        self.btn_del_identifiers.setSizePolicy(sizePolicy)
        self.btn_del_identifiers.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_identifiers.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_identifiers.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_del_identifiers.setObjectName("btn_del_identifiers")
        self.gridLayout_6.addWidget(self.btn_del_identifiers, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 1, 1, 1, 1)
        self.btn_gen_uuid_identifiers = QtWidgets.QPushButton(self.widget_2)
        self.btn_gen_uuid_identifiers.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_gen_uuid_identifiers.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_gen_uuid_identifiers.setCheckable(False)
        self.btn_gen_uuid_identifiers.setChecked(False)
        self.btn_gen_uuid_identifiers.setFlat(False)
        self.btn_gen_uuid_identifiers.setObjectName("btn_gen_uuid_identifiers")
        self.gridLayout_6.addWidget(self.btn_gen_uuid_identifiers, 4, 0, 1, 2)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_namespace = gui.QgsFilterLineEdit(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_namespace.sizePolicy().hasHeightForWidth())
        self.line_namespace.setSizePolicy(sizePolicy)
        self.line_namespace.setMinimumSize(QtCore.QSize(0, 33))
        self.line_namespace.setProperty("qgisRelation", "")
        self.line_namespace.setObjectName("line_namespace")
        self.gridLayout_4.addWidget(self.line_namespace, 0, 1, 1, 1)
        self.line_identifier = gui.QgsFilterLineEdit(self.widget_6)
        self.line_identifier.setMinimumSize(QtCore.QSize(0, 33))
        self.line_identifier.setText("")
        self.line_identifier.setProperty("qgisRelation", "")
        self.line_identifier.setObjectName("line_identifier")
        self.gridLayout_4.addWidget(self.line_identifier, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_6, 3, 0, 1, 1)
        self.btn_add_identifiers = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_identifiers.sizePolicy().hasHeightForWidth())
        self.btn_add_identifiers.setSizePolicy(sizePolicy)
        self.btn_add_identifiers.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_identifiers.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_identifiers.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_add_identifiers.setObjectName("btn_add_identifiers")
        self.gridLayout_6.addWidget(self.btn_add_identifiers, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_9 = QtWidgets.QWidget(self.widget_4)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(353, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.gridLayout_8.addWidget(self.widget_9, 3, 0, 1, 1)
        self.box_spatial_resolution = QtWidgets.QWidget(self.widget_4)
        self.box_spatial_resolution.setObjectName("box_spatial_resolution")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.box_spatial_resolution)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget11 = QtWidgets.QWidget(self.box_spatial_resolution)
        self.widget11.setObjectName("widget11")
        self.horizontalLayout10 = QtWidgets.QHBoxLayout(self.widget11)
        self.horizontalLayout10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout10.setSpacing(0)
        self.horizontalLayout10.setObjectName("horizontalLayout10")
        self.info_label_spatialResolution = QtWidgets.QPushButton(self.widget11)
        self.info_label_spatialResolution.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_spatialResolution.setFlat(True)
        self.info_label_spatialResolution.setObjectName("info_label_spatialResolution")
        self.horizontalLayout10.addWidget(self.info_label_spatialResolution)
        self.label_spatialResolution = QtWidgets.QLabel(self.widget11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_spatialResolution.setFont(font)
        self.label_spatialResolution.setObjectName("label_spatialResolution")
        self.horizontalLayout10.addWidget(self.label_spatialResolution)
        self.spatiaResolutionUnknown = QtWidgets.QCheckBox(self.widget11)
        self.spatiaResolutionUnknown.setObjectName("spatiaResolutionUnknown")
        self.horizontalLayout10.addWidget(self.spatiaResolutionUnknown)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout10.addItem(spacerItem3)
        self.gridLayout_10.addWidget(self.widget11, 0, 0, 1, 2)
        self.box_spatial_res_tables = QtWidgets.QWidget(self.box_spatial_resolution)
        self.box_spatial_res_tables.setObjectName("box_spatial_res_tables")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.box_spatial_res_tables)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(8)
        self.gridLayout_11.setVerticalSpacing(2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.box_distance = QtWidgets.QWidget(self.box_spatial_res_tables)
        self.box_distance.setMinimumSize(QtCore.QSize(100, 0))
        self.box_distance.setObjectName("box_distance")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.box_distance)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.distance = QtWidgets.QTableView(self.box_distance)
        self.distance.setMinimumSize(QtCore.QSize(0, 90))
        self.distance.setMaximumSize(QtCore.QSize(16777215, 90))
        self.distance.setObjectName("distance")
        self.gridLayout_7.addWidget(self.distance, 0, 0, 2, 1)
        self.btn_del_distance = QtWidgets.QPushButton(self.box_distance)
        self.btn_del_distance.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_distance.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_distance.setObjectName("btn_del_distance")
        self.gridLayout_7.addWidget(self.btn_del_distance, 1, 1, 1, 1)
        self.btn_add_distance = QtWidgets.QPushButton(self.box_distance)
        self.btn_add_distance.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_distance.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_distance.setObjectName("btn_add_distance")
        self.gridLayout_7.addWidget(self.btn_add_distance, 3, 1, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.box_distance)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.spin_distance = QtWidgets.QDoubleSpinBox(self.widget_11)
        self.spin_distance.setMinimumSize(QtCore.QSize(0, 30))
        self.spin_distance.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_distance.setDecimals(4)
        self.spin_distance.setMinimum(0.0001)
        self.spin_distance.setMaximum(999999999.0)
        self.spin_distance.setSingleStep(0.0)
        self.spin_distance.setObjectName("spin_distance")
        self.horizontalLayout_11.addWidget(self.spin_distance)
        self.combo_distance = QtWidgets.QComboBox(self.widget_11)
        self.combo_distance.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_distance.setMaximumSize(QtCore.QSize(120, 16777215))
        self.combo_distance.setObjectName("combo_distance")
        self.horizontalLayout_11.addWidget(self.combo_distance)
        self.gridLayout_7.addWidget(self.widget_11, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.box_distance, 1, 1, 1, 1)
        self.box_equivalent_scale = QtWidgets.QWidget(self.box_spatial_res_tables)
        self.box_equivalent_scale.setMinimumSize(QtCore.QSize(0, 0))
        self.box_equivalent_scale.setObjectName("box_equivalent_scale")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.box_equivalent_scale)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_add_equivalentscale = QtWidgets.QPushButton(self.box_equivalent_scale)
        self.btn_add_equivalentscale.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_equivalentscale.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_equivalentscale.setObjectName("btn_add_equivalentscale")
        self.gridLayout_3.addWidget(self.btn_add_equivalentscale, 5, 2, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.box_equivalent_scale)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6_NOHELP = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6_NOHELP.sizePolicy().hasHeightForWidth())
        self.label_6_NOHELP.setSizePolicy(sizePolicy)
        self.label_6_NOHELP.setObjectName("label_6_NOHELP")
        self.horizontalLayout_7.addWidget(self.label_6_NOHELP)
        self.spin_equivalentscale = QtWidgets.QSpinBox(self.widget_5)
        self.spin_equivalentscale.setMinimumSize(QtCore.QSize(160, 30))
        self.spin_equivalentscale.setStyleSheet("padding-right: 40px;")
        self.spin_equivalentscale.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_equivalentscale.setMinimum(1)
        self.spin_equivalentscale.setMaximum(1000000062)
        self.spin_equivalentscale.setSingleStep(0)
        self.spin_equivalentscale.setObjectName("spin_equivalentscale")
        self.horizontalLayout_7.addWidget(self.spin_equivalentscale)
        self.gridLayout_3.addWidget(self.widget_5, 5, 1, 1, 1)
        self.btn_del_equivalentscale = QtWidgets.QPushButton(self.box_equivalent_scale)
        self.btn_del_equivalentscale.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_equivalentscale.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_equivalentscale.setObjectName("btn_del_equivalentscale")
        self.gridLayout_3.addWidget(self.btn_del_equivalentscale, 3, 2, 1, 1)
        self.equivalentscale = QtWidgets.QListView(self.box_equivalent_scale)
        self.equivalentscale.setMinimumSize(QtCore.QSize(0, 90))
        self.equivalentscale.setMaximumSize(QtCore.QSize(16777215, 90))
        self.equivalentscale.setObjectName("equivalentscale")
        self.gridLayout_3.addWidget(self.equivalentscale, 2, 1, 2, 1)
        self.gridLayout_11.addWidget(self.box_equivalent_scale, 1, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.box_spatial_res_tables)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_3 = QtWidgets.QWidget(self.widget_10)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.info_label_equivalentscale = QtWidgets.QPushButton(self.widget_3)
        self.info_label_equivalentscale.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_equivalentscale.setText("")
        self.info_label_equivalentscale.setFlat(True)
        self.info_label_equivalentscale.setObjectName("info_label_equivalentscale")
        self.horizontalLayout_3.addWidget(self.info_label_equivalentscale)
        self.label_equivalentscale = QtWidgets.QLabel(self.widget_3)
        self.label_equivalentscale.setObjectName("label_equivalentscale")
        self.horizontalLayout_3.addWidget(self.label_equivalentscale)
        self.horizontalLayout_8.addWidget(self.widget_3)
        self.widget_7 = QtWidgets.QWidget(self.widget_10)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.info_label_distance = QtWidgets.QPushButton(self.widget_7)
        self.info_label_distance.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_distance.setText("")
        self.info_label_distance.setFlat(True)
        self.info_label_distance.setObjectName("info_label_distance")
        self.horizontalLayout_4.addWidget(self.info_label_distance)
        self.label_distance = QtWidgets.QLabel(self.widget_7)
        self.label_distance.setObjectName("label_distance")
        self.horizontalLayout_4.addWidget(self.label_distance)
        self.horizontalLayout_8.addWidget(self.widget_7)
        self.gridLayout_11.addWidget(self.widget_10, 0, 0, 1, 2)
        self.widget_10.raise_()
        self.box_distance.raise_()
        self.box_equivalent_scale.raise_()
        self.gridLayout_10.addWidget(self.box_spatial_res_tables, 1, 0, 1, 2)
        self.gridLayout_8.addWidget(self.box_spatial_resolution, 0, 0, 1, 3)
        self.widget12 = QtWidgets.QWidget(self.widget_4)
        self.widget12.setObjectName("widget12")
        self.horizontalLayout11 = QtWidgets.QHBoxLayout(self.widget12)
        self.horizontalLayout11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout11.setSpacing(0)
        self.horizontalLayout11.setObjectName("horizontalLayout11")
        self.info_label_resourcestatus = QtWidgets.QPushButton(self.widget12)
        self.info_label_resourcestatus.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_resourcestatus.setFlat(True)
        self.info_label_resourcestatus.setObjectName("info_label_resourcestatus")
        self.horizontalLayout11.addWidget(self.info_label_resourcestatus)
        self.label_resourcestatus = QtWidgets.QLabel(self.widget12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_resourcestatus.setFont(font)
        self.label_resourcestatus.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_resourcestatus.setObjectName("label_resourcestatus")
        self.horizontalLayout11.addWidget(self.label_resourcestatus)
        self.gridLayout_8.addWidget(self.widget12, 1, 1, 1, 1)
        self.btn_add_resourcestatus = QtWidgets.QPushButton(self.widget_4)
        self.btn_add_resourcestatus.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_resourcestatus.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_resourcestatus.setObjectName("btn_add_resourcestatus")
        self.gridLayout_8.addWidget(self.btn_add_resourcestatus, 4, 2, 1, 1)
        self.combo_resourcestatus = QtWidgets.QComboBox(self.widget_4)
        self.combo_resourcestatus.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_resourcestatus.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.combo_resourcestatus.setObjectName("combo_resourcestatus")
        self.gridLayout_8.addWidget(self.combo_resourcestatus, 4, 1, 1, 1)
        self.btn_del_resourcestatus = QtWidgets.QPushButton(self.widget_4)
        self.btn_del_resourcestatus.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_resourcestatus.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_resourcestatus.setObjectName("btn_del_resourcestatus")
        self.gridLayout_8.addWidget(self.btn_del_resourcestatus, 3, 2, 1, 1)
        self.resourcestatus = QtWidgets.QListView(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resourcestatus.sizePolicy().hasHeightForWidth())
        self.resourcestatus.setSizePolicy(sizePolicy)
        self.resourcestatus.setMinimumSize(QtCore.QSize(0, 90))
        self.resourcestatus.setMaximumSize(QtCore.QSize(16777215, 90))
        self.resourcestatus.setObjectName("resourcestatus")
        self.gridLayout_8.addWidget(self.resourcestatus, 2, 1, 2, 1)
        self.widget_operatesOn = QtWidgets.QWidget(self.widget_4)
        self.widget_operatesOn.setObjectName("widget_operatesOn")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_operatesOn)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.info_label_operatesOn = QtWidgets.QPushButton(self.widget_operatesOn)
        self.info_label_operatesOn.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_operatesOn.setText("")
        self.info_label_operatesOn.setFlat(True)
        self.info_label_operatesOn.setObjectName("info_label_operatesOn")
        self.horizontalLayout_6.addWidget(self.info_label_operatesOn)
        self.label_operatesOn = QtWidgets.QLabel(self.widget_operatesOn)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_operatesOn.setFont(font)
        self.label_operatesOn.setObjectName("label_operatesOn")
        self.horizontalLayout_6.addWidget(self.label_operatesOn)
        self.gridLayout_8.addWidget(self.widget_operatesOn, 5, 0, 1, 1)
        self.widget_charset = QtWidgets.QWidget(self.widget_4)
        self.widget_charset.setObjectName("widget_charset")
        self.horizontalLayout12 = QtWidgets.QHBoxLayout(self.widget_charset)
        self.horizontalLayout12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout12.setSpacing(0)
        self.horizontalLayout12.setObjectName("horizontalLayout12")
        self.info_label_characterset = QtWidgets.QPushButton(self.widget_charset)
        self.info_label_characterset.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_characterset.setFlat(True)
        self.info_label_characterset.setObjectName("info_label_characterset")
        self.horizontalLayout12.addWidget(self.info_label_characterset)
        self.label_characterset = QtWidgets.QLabel(self.widget_charset)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_characterset.setFont(font)
        self.label_characterset.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_characterset.setObjectName("label_characterset")
        self.horizontalLayout12.addWidget(self.label_characterset)
        self.gridLayout_8.addWidget(self.widget_charset, 1, 0, 1, 1)
        self.btn_add_operatesOn = QtWidgets.QPushButton(self.widget_4)
        self.btn_add_operatesOn.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_operatesOn.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_operatesOn.setObjectName("btn_add_operatesOn")
        self.gridLayout_8.addWidget(self.btn_add_operatesOn, 9, 2, 1, 1)
        self.btn_del_operatesOn = QtWidgets.QPushButton(self.widget_4)
        self.btn_del_operatesOn.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_operatesOn.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_operatesOn.setObjectName("btn_del_operatesOn")
        self.gridLayout_8.addWidget(self.btn_del_operatesOn, 8, 2, 1, 1)
        self.line_operatesOn = gui.QgsFilterLineEdit(self.widget_4)
        self.line_operatesOn.setMinimumSize(QtCore.QSize(58, 30))
        self.line_operatesOn.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_operatesOn.setProperty("qgisRelation", "")
        self.line_operatesOn.setObjectName("line_operatesOn")
        self.gridLayout_8.addWidget(self.line_operatesOn, 9, 0, 1, 2)
        self.graphicoverview = gui.QgsFilterLineEdit(self.widget_4)
        self.graphicoverview.setMinimumSize(QtCore.QSize(58, 30))
        self.graphicoverview.setProperty("qgisRelation", "")
        self.graphicoverview.setObjectName("graphicoverview")
        self.gridLayout_8.addWidget(self.graphicoverview, 16, 0, 1, 2)
        self.widget13 = QtWidgets.QWidget(self.widget_4)
        self.widget13.setObjectName("widget13")
        self.horizontalLayout13 = QtWidgets.QHBoxLayout(self.widget13)
        self.horizontalLayout13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout13.setSpacing(0)
        self.horizontalLayout13.setObjectName("horizontalLayout13")
        self.info_label_graphicoverview = QtWidgets.QPushButton(self.widget13)
        self.info_label_graphicoverview.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_graphicoverview.setFlat(True)
        self.info_label_graphicoverview.setObjectName("info_label_graphicoverview")
        self.horizontalLayout13.addWidget(self.info_label_graphicoverview)
        self.label_graphicoverview = QtWidgets.QLabel(self.widget13)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_graphicoverview.setFont(font)
        self.label_graphicoverview.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_graphicoverview.setObjectName("label_graphicoverview")
        self.horizontalLayout13.addWidget(self.label_graphicoverview)
        self.gridLayout_8.addWidget(self.widget13, 11, 0, 1, 1)
        self.operatesOn = QtWidgets.QListView(self.widget_4)
        self.operatesOn.setMaximumSize(QtCore.QSize(16777215, 90))
        self.operatesOn.setObjectName("operatesOn")
        self.gridLayout_8.addWidget(self.operatesOn, 6, 0, 3, 2)
        self.characterset = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.characterset.sizePolicy().hasHeightForWidth())
        self.characterset.setSizePolicy(sizePolicy)
        self.characterset.setMinimumSize(QtCore.QSize(150, 30))
        self.characterset.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.characterset.setObjectName("characterset")
        self.gridLayout_8.addWidget(self.characterset, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_4)
        self.box_language_geoReprType = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.box_language_geoReprType.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.box_language_geoReprType.setObjectName("box_language_geoReprType")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.box_language_geoReprType)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btn_del_geographicrepresentation = QtWidgets.QPushButton(self.box_language_geoReprType)
        self.btn_del_geographicrepresentation.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_geographicrepresentation.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_geographicrepresentation.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_del_geographicrepresentation.setObjectName("btn_del_geographicrepresentation")
        self.gridLayout_9.addWidget(self.btn_del_geographicrepresentation, 2, 3, 1, 1)
        self.btn_del_language = QtWidgets.QPushButton(self.box_language_geoReprType)
        self.btn_del_language.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_language.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_language.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_del_language.setObjectName("btn_del_language")
        self.gridLayout_9.addWidget(self.btn_del_language, 2, 1, 1, 1)
        self.combo_geographicrepresentation = QtWidgets.QComboBox(self.box_language_geoReprType)
        self.combo_geographicrepresentation.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_geographicrepresentation.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.combo_geographicrepresentation.setObjectName("combo_geographicrepresentation")
        self.gridLayout_9.addWidget(self.combo_geographicrepresentation, 4, 2, 1, 1)
        self.combo_language = QtWidgets.QComboBox(self.box_language_geoReprType)
        self.combo_language.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_language.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.combo_language.setObjectName("combo_language")
        self.gridLayout_9.addWidget(self.combo_language, 4, 0, 1, 1)
        self.btn_add_language = QtWidgets.QPushButton(self.box_language_geoReprType)
        self.btn_add_language.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_language.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_language.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_add_language.setObjectName("btn_add_language")
        self.gridLayout_9.addWidget(self.btn_add_language, 4, 1, 1, 1)
        self.btn_add_geographicrepresentation = QtWidgets.QPushButton(self.box_language_geoReprType)
        self.btn_add_geographicrepresentation.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_geographicrepresentation.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_geographicrepresentation.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_add_geographicrepresentation.setObjectName("btn_add_geographicrepresentation")
        self.gridLayout_9.addWidget(self.btn_add_geographicrepresentation, 4, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 1, 1, 1, 1)
        self.language = QtWidgets.QListView(self.box_language_geoReprType)
        self.language.setMinimumSize(QtCore.QSize(0, 90))
        self.language.setMaximumSize(QtCore.QSize(16777215, 90))
        self.language.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.language.setObjectName("language")
        self.gridLayout_9.addWidget(self.language, 1, 0, 3, 1)
        self.geographicrepresentation = QtWidgets.QListView(self.box_language_geoReprType)
        self.geographicrepresentation.setMinimumSize(QtCore.QSize(0, 90))
        self.geographicrepresentation.setMaximumSize(QtCore.QSize(16777215, 90))
        self.geographicrepresentation.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.geographicrepresentation.setObjectName("geographicrepresentation")
        self.gridLayout_9.addWidget(self.geographicrepresentation, 1, 2, 3, 1)
        self.widget_8 = QtWidgets.QWidget(self.box_language_geoReprType)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_language = QtWidgets.QWidget(self.widget_8)
        self.widget_language.setObjectName("widget_language")
        self.horizontalLayout14 = QtWidgets.QHBoxLayout(self.widget_language)
        self.horizontalLayout14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout14.setSpacing(0)
        self.horizontalLayout14.setObjectName("horizontalLayout14")
        self.info_label_language = QtWidgets.QPushButton(self.widget_language)
        self.info_label_language.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_language.setFlat(True)
        self.info_label_language.setObjectName("info_label_language")
        self.horizontalLayout14.addWidget(self.info_label_language)
        self.label_language = QtWidgets.QLabel(self.widget_language)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_language.setFont(font)
        self.label_language.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_language.setObjectName("label_language")
        self.horizontalLayout14.addWidget(self.label_language)
        self.horizontalLayout_9.addWidget(self.widget_language)
        self.widget_spatial_repre_type = QtWidgets.QWidget(self.widget_8)
        self.widget_spatial_repre_type.setObjectName("widget_spatial_repre_type")
        self.horizontalLayout15 = QtWidgets.QHBoxLayout(self.widget_spatial_repre_type)
        self.horizontalLayout15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout15.setSpacing(0)
        self.horizontalLayout15.setObjectName("horizontalLayout15")
        self.info_label_geographicrepresentation = QtWidgets.QPushButton(self.widget_spatial_repre_type)
        self.info_label_geographicrepresentation.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_geographicrepresentation.setFlat(True)
        self.info_label_geographicrepresentation.setObjectName("info_label_geographicrepresentation")
        self.horizontalLayout15.addWidget(self.info_label_geographicrepresentation)
        self.label_geographicrepresentation = QtWidgets.QLabel(self.widget_spatial_repre_type)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_geographicrepresentation.setFont(font)
        self.label_geographicrepresentation.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_geographicrepresentation.setObjectName("label_geographicrepresentation")
        self.horizontalLayout15.addWidget(self.label_geographicrepresentation)
        self.horizontalLayout_9.addWidget(self.widget_spatial_repre_type)
        self.gridLayout_9.addWidget(self.widget_8, 0, 0, 1, 3)
        self.verticalLayout.addWidget(self.box_language_geoReprType)
        self.widget14 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget14.setObjectName("widget14")
        self.horizontalLayout16 = QtWidgets.QHBoxLayout(self.widget14)
        self.horizontalLayout16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout16.setSpacing(0)
        self.horizontalLayout16.setObjectName("horizontalLayout16")
        self.info_label_contacts = QtWidgets.QPushButton(self.widget14)
        self.info_label_contacts.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_contacts.setFlat(True)
        self.info_label_contacts.setObjectName("info_label_contacts")
        self.horizontalLayout16.addWidget(self.info_label_contacts)
        self.label_contacts = QtWidgets.QLabel(self.widget14)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_contacts.setFont(font)
        self.label_contacts.setObjectName("label_contacts")
        self.horizontalLayout16.addWidget(self.label_contacts)
        self.verticalLayout.addWidget(self.widget14)
        self.Contacts = QtWidgets.QVBoxLayout()
        self.Contacts.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Contacts.setContentsMargins(-1, 0, -1, 0)
        self.Contacts.setSpacing(0)
        self.Contacts.setObjectName("Contacts")
        self.verticalLayout.addLayout(self.Contacts)
        self.btn_adi_contact = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_adi_contact.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_adi_contact.setFont(font)
        self.btn_adi_contact.setObjectName("btn_adi_contact")
        self.verticalLayout.addWidget(self.btn_adi_contact)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(identification)
        QtCore.QMetaObject.connectSlotsByName(identification)

    def retranslateUi(self, identification):
        _translate = QtCore.QCoreApplication.translate
        identification.setWindowTitle(_translate("identification", "Form"))
        self.label_hierarchylevel.setText(_translate("identification", "Tipo de Recurso*"))
        self.label_alternatetitle.setText(_translate("identification", "Título Alternativo"))
        self.label_purpose.setText(_translate("identification", "Objetivo"))
        self.alternatetitle.setPlaceholderText(_translate("identification", "Designação Alternativa do Recurso..."))
        self.label_serviceType.setText(_translate("identification", "Tipo De Serviço*"))
        self.label_couplingType.setText(_translate("identification", "Acoplamento*"))
        self.label_titleEN.setText(_translate("identification", "Título (Inglês)*"))
        self.titleEN.setPlaceholderText(_translate("identification", " Designação do recurso em Inglês..."))
        self.label_abstractEN.setText(_translate("identification", "Resumo (Inglês)*"))
        self.label_title.setText(_translate("identification", "Título (Português)*"))
        self.title.setPlaceholderText(_translate("identification", " Designação do recurso..."))
        self.label_abstract.setText(_translate("identification", "Resumo (Português)*"))
        self.label_resourcemaintenance.setText(_translate("identification", "Manutenção do Recurso*"))
        self.btn_add_resourcemaintenance.setText(_translate("identification", "+"))
        self.label_credits.setText(_translate("identification", "Créditos"))
        self.btn_del_resourcemaintenance.setText(_translate("identification", "-"))
        self.line_credits.setPlaceholderText(_translate("identification", "Entidades que contribuiram..."))
        self.btn_add_credits.setText(_translate("identification", "+"))
        self.btn_del_credits.setText(_translate("identification", "-"))
        self.label_identifiers.setText(_translate("identification", "Identificador Único do Recurso*"))
        self.btn_del_identifiers.setText(_translate("identification", "-"))
        self.btn_gen_uuid_identifiers.setText(_translate("identification", "Adicionar Linha com UUID gerado"))
        self.line_namespace.setPlaceholderText(_translate("identification", "Espaço de Nomes..."))
        self.line_identifier.setPlaceholderText(_translate("identification", "Identificador..."))
        self.btn_add_identifiers.setText(_translate("identification", "+"))
        self.label_spatialResolution.setText(_translate("identification", "Resolução Espacial*"))
        self.spatiaResolutionUnknown.setText(_translate("identification", "Resolução Espacial Desconhecida"))
        self.btn_del_distance.setText(_translate("identification", "-"))
        self.btn_add_distance.setText(_translate("identification", "+"))
        self.btn_add_equivalentscale.setText(_translate("identification", "+"))
        self.label_6_NOHELP.setText(_translate("identification", "1:"))
        self.btn_del_equivalentscale.setText(_translate("identification", "-"))
        self.label_equivalentscale.setText(_translate("identification", "Escala Equivalente"))
        self.label_distance.setText(_translate("identification", "Distância "))
        self.label_resourcestatus.setText(_translate("identification", "Estado do Recurso"))
        self.btn_add_resourcestatus.setText(_translate("identification", "+"))
        self.btn_del_resourcestatus.setText(_translate("identification", "-"))
        self.label_operatesOn.setText(_translate("identification", "Recursos Associados"))
        self.label_characterset.setText(_translate("identification", "Codificação*"))
        self.btn_add_operatesOn.setText(_translate("identification", "+"))
        self.btn_del_operatesOn.setText(_translate("identification", "-"))
        self.line_operatesOn.setPlaceholderText(_translate("identification", "URI ou http://"))
        self.graphicoverview.setPlaceholderText(_translate("identification", "http://"))
        self.label_graphicoverview.setText(_translate("identification", "Endereço(URL) da visualização gráfica"))
        self.btn_del_geographicrepresentation.setText(_translate("identification", "-"))
        self.btn_del_language.setText(_translate("identification", "-"))
        self.btn_add_language.setText(_translate("identification", "+"))
        self.btn_add_geographicrepresentation.setText(_translate("identification", "+"))
        self.label_language.setText(_translate("identification", "Idioma*"))
        self.label_geographicrepresentation.setText(_translate("identification", "Tipo de Representação Espacial*"))
        self.label_contacts.setText(_translate("identification", "Responsáveis pelo Recurso (Contacto)*"))
        self.btn_adi_contact.setText(_translate("identification", "Adicionar Contacto"))
from qgis import gui
