# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInfobiomares/snimarQtInterfaceView/templates/metadataPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_metadata(object):
    def setupUi(self, metadata):
        metadata.setObjectName("metadata")
        metadata.resize(600, 534)
        metadata.setMinimumSize(QtCore.QSize(580, 0))
        self.gridLayout = QtWidgets.QGridLayout(metadata)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(metadata)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(600, 0))
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 598, 532))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_characterset = QtWidgets.QPushButton(self.widget)
        self.info_label_characterset.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_characterset.setFlat(True)
        self.info_label_characterset.setObjectName("info_label_characterset")
        self.horizontalLayout.addWidget(self.info_label_characterset)
        self.label_characterset = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_characterset.setFont(font)
        self.label_characterset.setObjectName("label_characterset")
        self.horizontalLayout.addWidget(self.label_characterset)
        self.gridLayout_3.addWidget(self.widget, 5, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_profile = QtWidgets.QPushButton(self.widget1)
        self.info_label_profile.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_profile.setFlat(True)
        self.info_label_profile.setObjectName("info_label_profile")
        self.horizontalLayout1.addWidget(self.info_label_profile)
        self.label_profile = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_profile.setFont(font)
        self.label_profile.setObjectName("label_profile")
        self.horizontalLayout1.addWidget(self.label_profile)
        self.gridLayout_3.addWidget(self.widget1, 7, 0, 1, 1)
        self.btn_gen_uuid_fileidentifier = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_gen_uuid_fileidentifier.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_gen_uuid_fileidentifier.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_gen_uuid_fileidentifier.setObjectName("btn_gen_uuid_fileidentifier")
        self.gridLayout_3.addWidget(self.btn_gen_uuid_fileidentifier, 2, 1, 1, 1)
        self.stdversion = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.stdversion.setMinimumSize(QtCore.QSize(0, 30))
        self.stdversion.setProperty("qgisRelation", "")
        self.stdversion.setObjectName("stdversion")
        self.gridLayout_3.addWidget(self.stdversion, 9, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_stdname = QtWidgets.QPushButton(self.widget2)
        self.info_label_stdname.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_stdname.setFlat(True)
        self.info_label_stdname.setObjectName("info_label_stdname")
        self.horizontalLayout2.addWidget(self.info_label_stdname)
        self.label_stdname = QtWidgets.QLabel(self.widget2)
        self.label_stdname.setObjectName("label_stdname")
        self.horizontalLayout2.addWidget(self.label_stdname)
        self.gridLayout_3.addWidget(self.widget2, 8, 0, 1, 1)
        self.fileidentifier = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.fileidentifier.setMinimumSize(QtCore.QSize(0, 30))
        self.fileidentifier.setProperty("qgisRelation", "")
        self.fileidentifier.setObjectName("fileidentifier")
        self.gridLayout_3.addWidget(self.fileidentifier, 2, 0, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_datestamp = QtWidgets.QPushButton(self.widget3)
        self.info_label_datestamp.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_datestamp.setFlat(True)
        self.info_label_datestamp.setObjectName("info_label_datestamp")
        self.horizontalLayout3.addWidget(self.info_label_datestamp)
        self.label_datestamp = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_datestamp.setFont(font)
        self.label_datestamp.setObjectName("label_datestamp")
        self.horizontalLayout3.addWidget(self.label_datestamp)
        self.gridLayout_3.addWidget(self.widget3, 3, 0, 1, 1)
        self.widget4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_stdversion = QtWidgets.QPushButton(self.widget4)
        self.info_label_stdversion.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_stdversion.setFlat(True)
        self.info_label_stdversion.setObjectName("info_label_stdversion")
        self.horizontalLayout4.addWidget(self.info_label_stdversion)
        self.label_stdversion = QtWidgets.QLabel(self.widget4)
        self.label_stdversion.setObjectName("label_stdversion")
        self.horizontalLayout4.addWidget(self.label_stdversion)
        self.gridLayout_3.addWidget(self.widget4, 8, 1, 1, 1)
        self.stdname = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.stdname.setMinimumSize(QtCore.QSize(0, 30))
        self.stdname.setProperty("qgisRelation", "")
        self.stdname.setObjectName("stdname")
        self.gridLayout_3.addWidget(self.stdname, 9, 0, 1, 1)
        self.widget5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget5.setObjectName("widget5")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setSpacing(0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.info_label_language = QtWidgets.QPushButton(self.widget5)
        self.info_label_language.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_language.setFlat(True)
        self.info_label_language.setObjectName("info_label_language")
        self.horizontalLayout5.addWidget(self.info_label_language)
        self.label_language = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_language.setFont(font)
        self.label_language.setObjectName("label_language")
        self.horizontalLayout5.addWidget(self.label_language)
        self.gridLayout_3.addWidget(self.widget5, 5, 1, 1, 1)
        self.characterset = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.characterset.setMinimumSize(QtCore.QSize(0, 30))
        self.characterset.setObjectName("characterset")
        self.gridLayout_3.addWidget(self.characterset, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.language = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.language.setMinimumSize(QtCore.QSize(0, 30))
        self.language.setObjectName("language")
        self.gridLayout_3.addWidget(self.language, 6, 1, 1, 1)
        self.widget6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget6.setObjectName("widget6")
        self.horizontalLayout6 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout6.setSpacing(0)
        self.horizontalLayout6.setObjectName("horizontalLayout6")
        self.info_label_contacts = QtWidgets.QPushButton(self.widget6)
        self.info_label_contacts.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_contacts.setFlat(True)
        self.info_label_contacts.setObjectName("info_label_contacts")
        self.horizontalLayout6.addWidget(self.info_label_contacts)
        self.label_contacts = QtWidgets.QLabel(self.widget6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_contacts.setFont(font)
        self.label_contacts.setObjectName("label_contacts")
        self.horizontalLayout6.addWidget(self.label_contacts)
        self.gridLayout_3.addWidget(self.widget6, 10, 0, 1, 2)
        self.widget7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget7.setObjectName("widget7")
        self.horizontalLayout7 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout7.setSpacing(0)
        self.horizontalLayout7.setObjectName("horizontalLayout7")
        self.info_label_fileidentifier = QtWidgets.QPushButton(self.widget7)
        self.info_label_fileidentifier.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_fileidentifier.setFlat(True)
        self.info_label_fileidentifier.setObjectName("info_label_fileidentifier")
        self.horizontalLayout7.addWidget(self.info_label_fileidentifier)
        self.label_fileidentifier = QtWidgets.QLabel(self.widget7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_fileidentifier.setFont(font)
        self.label_fileidentifier.setLineWidth(0)
        self.label_fileidentifier.setObjectName("label_fileidentifier")
        self.horizontalLayout7.addWidget(self.label_fileidentifier)
        self.gridLayout_3.addWidget(self.widget7, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.datestamp = QtWidgets.QDateEdit(self.widget_2)
        self.datestamp.setMinimumSize(QtCore.QSize(0, 30))
        self.datestamp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.datestamp.setCalendarPopup(True)
        self.datestamp.setObjectName("datestamp")
        self.horizontalLayout_2.addWidget(self.datestamp)
        self.btn_clear_datestamp = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_datestamp.sizePolicy().hasHeightForWidth())
        self.btn_clear_datestamp.setSizePolicy(sizePolicy)
        self.btn_clear_datestamp.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_clear_datestamp.setMaximumSize(QtCore.QSize(40, 30))
        self.btn_clear_datestamp.setText("")
        self.btn_clear_datestamp.setObjectName("btn_clear_datestamp")
        self.horizontalLayout_2.addWidget(self.btn_clear_datestamp)
        self.gridLayout_3.addWidget(self.widget_2, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 3)
        self.btn_adi_contact = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_adi_contact.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_adi_contact.setFont(font)
        self.btn_adi_contact.setObjectName("btn_adi_contact")
        self.gridLayout_2.addWidget(self.btn_adi_contact, 13, 0, 1, 3)
        self.Contacts = QtWidgets.QVBoxLayout()
        self.Contacts.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Contacts.setContentsMargins(-1, 0, -1, 0)
        self.Contacts.setSpacing(0)
        self.Contacts.setObjectName("Contacts")
        self.gridLayout_2.addLayout(self.Contacts, 11, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 14, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(metadata)
        QtCore.QMetaObject.connectSlotsByName(metadata)

    def retranslateUi(self, metadata):
        _translate = QtCore.QCoreApplication.translate
        metadata.setWindowTitle(_translate("metadata", "Form"))
        self.label_characterset.setText(_translate("metadata", "Codificação dos Caracteres"))
        self.label_profile.setText(_translate("metadata", "Norma e Perfil de Metadados"))
        self.btn_gen_uuid_fileidentifier.setText(_translate("metadata", "Gerar UUID"))
        self.label_stdname.setText(_translate("metadata", "Nome"))
        self.fileidentifier.setPlaceholderText(_translate("metadata", "Identificador Único..."))
        self.label_datestamp.setText(_translate("metadata", "Data dos Metadados*"))
        self.label_stdversion.setText(_translate("metadata", "Versão"))
        self.label_language.setText(_translate("metadata", "Idioma*"))
        self.label_contacts.setText(_translate("metadata", "Responsáveis pelos Metadados (Contacto)*"))
        self.label_fileidentifier.setText(_translate("metadata", "Identificador Único do Ficheiro*"))
        self.datestamp.setDisplayFormat(_translate("metadata", "yyyy-MM-dd"))
        self.btn_adi_contact.setText(_translate("metadata", "Adicionar Contacto"))
from qgis import gui
