# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInfobiomares/snimarQtInterfaceView/templates/qualityPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quality(object):
    def setupUi(self, quality):
        quality.setObjectName("quality")
        quality.resize(955, 872)
        quality.setMinimumSize(QtCore.QSize(580, 0))
        self.gridLayout = QtWidgets.QGridLayout(quality)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(quality)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 941, 1098))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_hist = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.panel_hist.setObjectName("panel_hist")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panel_hist)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.panel_hist)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_hist = QtWidgets.QPushButton(self.widget1)
        self.info_label_hist.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_hist.setFlat(True)
        self.info_label_hist.setObjectName("info_label_hist")
        self.horizontalLayout.addWidget(self.info_label_hist)
        self.label_hist = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_hist.setFont(font)
        self.label_hist.setObjectName("label_hist")
        self.horizontalLayout.addWidget(self.label_hist)
        self.verticalLayout_3.addWidget(self.widget1)
        self.widget2 = QtWidgets.QWidget(self.widget)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_statement = QtWidgets.QPushButton(self.widget2)
        self.info_label_statement.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_statement.setFlat(True)
        self.info_label_statement.setObjectName("info_label_statement")
        self.horizontalLayout1.addWidget(self.info_label_statement)
        self.label_statement = QtWidgets.QLabel(self.widget2)
        self.label_statement.setObjectName("label_statement")
        self.horizontalLayout1.addWidget(self.label_statement)
        self.verticalLayout_3.addWidget(self.widget2)
        self.statement = QtWidgets.QPlainTextEdit(self.widget)
        self.statement.setMinimumSize(QtCore.QSize(0, 90))
        self.statement.setMaximumSize(QtCore.QSize(16777215, 90))
        self.statement.setObjectName("statement")
        self.verticalLayout_3.addWidget(self.statement)
        self.widget3 = QtWidgets.QWidget(self.widget)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_statementEN = QtWidgets.QPushButton(self.widget3)
        self.info_label_statementEN.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_statementEN.setFlat(True)
        self.info_label_statementEN.setObjectName("info_label_statementEN")
        self.horizontalLayout2.addWidget(self.info_label_statementEN)
        self.label_statementEN = QtWidgets.QLabel(self.widget3)
        self.label_statementEN.setObjectName("label_statementEN")
        self.horizontalLayout2.addWidget(self.label_statementEN)
        self.verticalLayout_3.addWidget(self.widget3)
        self.statementEN = QtWidgets.QPlainTextEdit(self.widget)
        self.statementEN.setMinimumSize(QtCore.QSize(0, 90))
        self.statementEN.setMaximumSize(QtCore.QSize(16777215, 90))
        self.statementEN.setObjectName("statementEN")
        self.verticalLayout_3.addWidget(self.statementEN)
        self.hist_data = QtWidgets.QCheckBox(self.widget)
        self.hist_data.setObjectName("hist_data")
        self.verticalLayout_3.addWidget(self.hist_data)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(0, 9, 0, 9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_del_source = QtWidgets.QPushButton(self.widget_2)
        self.btn_del_source.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_source.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_source.setObjectName("btn_del_source")
        self.gridLayout_5.addWidget(self.btn_del_source, 7, 4, 1, 1)
        self.btn_del_processsteps = QtWidgets.QPushButton(self.widget_2)
        self.btn_del_processsteps.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_processsteps.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_processsteps.setObjectName("btn_del_processsteps")
        self.gridLayout_5.addWidget(self.btn_del_processsteps, 2, 4, 1, 1)
        self.source = QtWidgets.QListView(self.widget_2)
        self.source.setMinimumSize(QtCore.QSize(0, 90))
        self.source.setMaximumSize(QtCore.QSize(16777215, 90))
        self.source.setObjectName("source")
        self.gridLayout_5.addWidget(self.source, 6, 1, 2, 3)
        self.line_description = gui.QgsFilterLineEdit(self.widget_2)
        self.line_description.setMinimumSize(QtCore.QSize(58, 30))
        self.line_description.setProperty("qgisRelation", "")
        self.line_description.setObjectName("line_description")
        self.gridLayout_5.addWidget(self.line_description, 3, 1, 1, 1)
        self.btn_add_source = QtWidgets.QPushButton(self.widget_2)
        self.btn_add_source.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_source.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_source.setObjectName("btn_add_source")
        self.gridLayout_5.addWidget(self.btn_add_source, 9, 4, 1, 1)
        self.btn_add_processsteps = QtWidgets.QPushButton(self.widget_2)
        self.btn_add_processsteps.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_processsteps.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_processsteps.setObjectName("btn_add_processsteps")
        self.gridLayout_5.addWidget(self.btn_add_processsteps, 3, 4, 1, 1)
        self.line_source = gui.QgsFilterLineEdit(self.widget_2)
        self.line_source.setMinimumSize(QtCore.QSize(0, 30))
        self.line_source.setProperty("qgisRelation", "")
        self.line_source.setObjectName("line_source")
        self.gridLayout_5.addWidget(self.line_source, 9, 1, 1, 3)
        self.widget4 = QtWidgets.QWidget(self.widget_2)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_source = QtWidgets.QPushButton(self.widget4)
        self.info_label_source.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_source.setFlat(True)
        self.info_label_source.setObjectName("info_label_source")
        self.horizontalLayout3.addWidget(self.info_label_source)
        self.label_source = QtWidgets.QLabel(self.widget4)
        self.label_source.setObjectName("label_source")
        self.horizontalLayout3.addWidget(self.label_source)
        self.gridLayout_5.addWidget(self.widget4, 5, 1, 1, 1)
        self.line_rationale = gui.QgsFilterLineEdit(self.widget_2)
        self.line_rationale.setMinimumSize(QtCore.QSize(58, 30))
        self.line_rationale.setProperty("qgisRelation", "")
        self.line_rationale.setObjectName("line_rationale")
        self.gridLayout_5.addWidget(self.line_rationale, 3, 3, 1, 1)
        self.widget5 = QtWidgets.QWidget(self.widget_2)
        self.widget5.setObjectName("widget5")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_processsteps = QtWidgets.QPushButton(self.widget5)
        self.info_label_processsteps.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_processsteps.setFlat(True)
        self.info_label_processsteps.setObjectName("info_label_processsteps")
        self.horizontalLayout4.addWidget(self.info_label_processsteps)
        self.label_processsteps = QtWidgets.QLabel(self.widget5)
        self.label_processsteps.setObjectName("label_processsteps")
        self.horizontalLayout4.addWidget(self.label_processsteps)
        self.gridLayout_5.addWidget(self.widget5, 0, 1, 1, 1)
        self.date_processdate = QtWidgets.QDateTimeEdit(self.widget_2)
        self.date_processdate.setMinimumSize(QtCore.QSize(260, 30))
        self.date_processdate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.date_processdate.setSpecialValueText("")
        self.date_processdate.setCalendarPopup(True)
        self.date_processdate.setObjectName("date_processdate")
        self.gridLayout_5.addWidget(self.date_processdate, 3, 2, 1, 1)
        self.processsteps = QtWidgets.QTableView(self.widget_2)
        self.processsteps.setMinimumSize(QtCore.QSize(0, 240))
        self.processsteps.setMaximumSize(QtCore.QSize(16777215, 240))
        self.processsteps.setObjectName("processsteps")
        self.gridLayout_5.addWidget(self.processsteps, 1, 1, 2, 3)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget.raise_()
        self.widget.raise_()
        self.widget.raise_()
        self.statement.raise_()
        self.statementEN.raise_()
        self.widget_2.raise_()
        self.hist_data.raise_()
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.panel_hist)
        self.panel_report = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.panel_report.setEnabled(True)
        self.panel_report.setTitle("")
        self.panel_report.setObjectName("panel_report")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.panel_report)
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mGroupBox = gui.QgsCollapsibleGroupBox(self.panel_report)
        self.mGroupBox.setObjectName("mGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mGroupBox)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.mGroupBox)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setContentsMargins(14, -1, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget6 = QtWidgets.QWidget(self.widget_3)
        self.widget6.setObjectName("widget6")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setSpacing(0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.info_label_conformancetitle = QtWidgets.QPushButton(self.widget6)
        self.info_label_conformancetitle.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_conformancetitle.setFlat(True)
        self.info_label_conformancetitle.setObjectName("info_label_conformancetitle")
        self.horizontalLayout5.addWidget(self.info_label_conformancetitle)
        self.label_conformancetitle = QtWidgets.QLabel(self.widget6)
        self.label_conformancetitle.setObjectName("label_conformancetitle")
        self.horizontalLayout5.addWidget(self.label_conformancetitle)
        self.gridLayout_4.addWidget(self.widget6, 1, 0, 1, 1)
        self.widget7 = QtWidgets.QWidget(self.widget_3)
        self.widget7.setObjectName("widget7")
        self.horizontalLayout6 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout6.setSpacing(0)
        self.horizontalLayout6.setObjectName("horizontalLayout6")
        self.info_label_conformancedatetype = QtWidgets.QPushButton(self.widget7)
        self.info_label_conformancedatetype.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_conformancedatetype.setFlat(True)
        self.info_label_conformancedatetype.setObjectName("info_label_conformancedatetype")
        self.horizontalLayout6.addWidget(self.info_label_conformancedatetype)
        self.label_conformancedatetype = QtWidgets.QLabel(self.widget7)
        self.label_conformancedatetype.setObjectName("label_conformancedatetype")
        self.horizontalLayout6.addWidget(self.label_conformancedatetype)
        self.gridLayout_4.addWidget(self.widget7, 3, 2, 1, 1)
        self.conformancedatetype = QtWidgets.QComboBox(self.widget_3)
        self.conformancedatetype.setMinimumSize(QtCore.QSize(0, 30))
        self.conformancedatetype.setObjectName("conformancedatetype")
        self.gridLayout_4.addWidget(self.conformancedatetype, 4, 2, 1, 1)
        self.conformanceexplanation = QtWidgets.QLineEdit(self.widget_3)
        self.conformanceexplanation.setMinimumSize(QtCore.QSize(0, 30))
        self.conformanceexplanation.setObjectName("conformanceexplanation")
        self.gridLayout_4.addWidget(self.conformanceexplanation, 6, 0, 1, 5)
        self.widget8 = QtWidgets.QWidget(self.widget_3)
        self.widget8.setObjectName("widget8")
        self.horizontalLayout7 = QtWidgets.QHBoxLayout(self.widget8)
        self.horizontalLayout7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout7.setSpacing(0)
        self.horizontalLayout7.setObjectName("horizontalLayout7")
        self.info_label_conformanceexplanation = QtWidgets.QPushButton(self.widget8)
        self.info_label_conformanceexplanation.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_conformanceexplanation.setFlat(True)
        self.info_label_conformanceexplanation.setObjectName("info_label_conformanceexplanation")
        self.horizontalLayout7.addWidget(self.info_label_conformanceexplanation)
        self.label_conformanceexplanation = QtWidgets.QLabel(self.widget8)
        self.label_conformanceexplanation.setObjectName("label_conformanceexplanation")
        self.horizontalLayout7.addWidget(self.label_conformanceexplanation)
        self.gridLayout_4.addWidget(self.widget8, 5, 0, 1, 1)
        self.widget9 = QtWidgets.QWidget(self.widget_3)
        self.widget9.setObjectName("widget9")
        self.horizontalLayout8 = QtWidgets.QHBoxLayout(self.widget9)
        self.horizontalLayout8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout8.setSpacing(0)
        self.horizontalLayout8.setObjectName("horizontalLayout8")
        self.info_label_Conformity = QtWidgets.QPushButton(self.widget9)
        self.info_label_Conformity.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_Conformity.setFlat(True)
        self.info_label_Conformity.setObjectName("info_label_Conformity")
        self.horizontalLayout8.addWidget(self.info_label_Conformity)
        self.label_Conformity = QtWidgets.QLabel(self.widget9)
        self.label_Conformity.setObjectName("label_Conformity")
        self.horizontalLayout8.addWidget(self.label_Conformity)
        self.gridLayout_4.addWidget(self.widget9, 0, 0, 1, 1)
        self.widget10 = QtWidgets.QWidget(self.widget_3)
        self.widget10.setObjectName("widget10")
        self.horizontalLayout9 = QtWidgets.QHBoxLayout(self.widget10)
        self.horizontalLayout9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout9.setSpacing(0)
        self.horizontalLayout9.setObjectName("horizontalLayout9")
        self.info_label_conformancedate = QtWidgets.QPushButton(self.widget10)
        self.info_label_conformancedate.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_conformancedate.setFlat(True)
        self.info_label_conformancedate.setObjectName("info_label_conformancedate")
        self.horizontalLayout9.addWidget(self.info_label_conformancedate)
        self.label_conformancedate = QtWidgets.QLabel(self.widget10)
        self.label_conformancedate.setObjectName("label_conformancedate")
        self.horizontalLayout9.addWidget(self.label_conformancedate)
        self.gridLayout_4.addWidget(self.widget10, 3, 0, 1, 1)
        self.conformancetitle = QtWidgets.QLineEdit(self.widget_3)
        self.conformancetitle.setMinimumSize(QtCore.QSize(0, 30))
        self.conformancetitle.setObjectName("conformancetitle")
        self.gridLayout_4.addWidget(self.conformancetitle, 2, 0, 1, 5)
        self.conformancedate = QtWidgets.QDateEdit(self.widget_3)
        self.conformancedate.setMinimumSize(QtCore.QSize(98, 30))
        self.conformancedate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.conformancedate.setCalendarPopup(True)
        self.conformancedate.setObjectName("conformancedate")
        self.gridLayout_4.addWidget(self.conformancedate, 4, 0, 1, 1)
        self.btn_clear_conformancedate = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_conformancedate.sizePolicy().hasHeightForWidth())
        self.btn_clear_conformancedate.setSizePolicy(sizePolicy)
        self.btn_clear_conformancedate.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_clear_conformancedate.setMaximumSize(QtCore.QSize(40, 30))
        self.btn_clear_conformancedate.setText("")
        self.btn_clear_conformancedate.setObjectName("btn_clear_conformancedate")
        self.gridLayout_4.addWidget(self.btn_clear_conformancedate, 4, 1, 1, 1)
        self.widget11 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget11.sizePolicy().hasHeightForWidth())
        self.widget11.setSizePolicy(sizePolicy)
        self.widget11.setMinimumSize(QtCore.QSize(210, 30))
        self.widget11.setMaximumSize(QtCore.QSize(210, 30))
        self.widget11.setObjectName("widget11")
        self.horizontalLayout10 = QtWidgets.QHBoxLayout(self.widget11)
        self.horizontalLayout10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout10.setSpacing(0)
        self.horizontalLayout10.setObjectName("horizontalLayout10")
        self.info_label_conform = QtWidgets.QPushButton(self.widget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_label_conform.sizePolicy().hasHeightForWidth())
        self.info_label_conform.setSizePolicy(sizePolicy)
        self.info_label_conform.setMinimumSize(QtCore.QSize(20, 20))
        self.info_label_conform.setMaximumSize(QtCore.QSize(16, 20))
        self.info_label_conform.setFlat(True)
        self.info_label_conform.setObjectName("info_label_conform")
        self.horizontalLayout10.addWidget(self.info_label_conform)
        self.label_conform = QtWidgets.QLabel(self.widget11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_conform.sizePolicy().hasHeightForWidth())
        self.label_conform.setSizePolicy(sizePolicy)
        self.label_conform.setMinimumSize(QtCore.QSize(155, 20))
        self.label_conform.setMaximumSize(QtCore.QSize(155, 20))
        self.label_conform.setObjectName("label_conform")
        self.horizontalLayout10.addWidget(self.label_conform)
        self.conformancedegree = QtWidgets.QCheckBox(self.widget11)
        self.conformancedegree.setMinimumSize(QtCore.QSize(30, 30))
        self.conformancedegree.setMaximumSize(QtCore.QSize(30, 30))
        self.conformancedegree.setText("")
        self.conformancedegree.setObjectName("conformancedegree")
        self.horizontalLayout10.addWidget(self.conformancedegree, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_4.addWidget(self.widget11, 4, 3, 1, 1)
        self.btn_INSPIRE = QtWidgets.QPushButton(self.widget_3)
        self.btn_INSPIRE.setObjectName("btn_INSPIRE")
        self.gridLayout_4.addWidget(self.btn_INSPIRE, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.mGroupBox, 1, 0, 1, 1)
        self.widget12 = QtWidgets.QWidget(self.panel_report)
        self.widget12.setObjectName("widget12")
        self.horizontalLayout11 = QtWidgets.QHBoxLayout(self.widget12)
        self.horizontalLayout11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout11.setSpacing(0)
        self.horizontalLayout11.setObjectName("horizontalLayout11")
        self.info_label_report = QtWidgets.QPushButton(self.widget12)
        self.info_label_report.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_report.setFlat(True)
        self.info_label_report.setObjectName("info_label_report")
        self.horizontalLayout11.addWidget(self.info_label_report)
        self.label_report = QtWidgets.QLabel(self.widget12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_report.setFont(font)
        self.label_report.setObjectName("label_report")
        self.horizontalLayout11.addWidget(self.label_report)
        self.gridLayout_2.addWidget(self.widget12, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.panel_report)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(quality)
        QtCore.QMetaObject.connectSlotsByName(quality)

    def retranslateUi(self, quality):
        _translate = QtCore.QCoreApplication.translate
        quality.setWindowTitle(_translate("quality", "Form"))
        self.label_hist.setText(_translate("quality", "Histórico"))
        self.label_statement.setText(_translate("quality", "Declaração (Português)*"))
        self.label_statementEN.setText(_translate("quality", "Declaração (Inglês)"))
        self.hist_data.setText(_translate("quality", "Dado histórico marinho recuperado?"))
        self.btn_del_source.setText(_translate("quality", "-"))
        self.btn_del_processsteps.setText(_translate("quality", "-"))
        self.line_description.setPlaceholderText(_translate("quality", "Descrição..."))
        self.btn_add_source.setText(_translate("quality", "+"))
        self.btn_add_processsteps.setText(_translate("quality", "+"))
        self.line_source.setPlaceholderText(_translate("quality", "Fontes de Dados..."))
        self.label_source.setText(_translate("quality", "Fonte dos Dados"))
        self.line_rationale.setPlaceholderText(_translate("quality", "Justificação..."))
        self.label_processsteps.setText(_translate("quality", "Etapas do Processo"))
        self.date_processdate.setDisplayFormat(_translate("quality", "yyyy-MM-dd hh:mm:ss"))
        self.mGroupBox.setTitle(_translate("quality", "Consistência do Domínio*"))
        self.label_conformancetitle.setText(_translate("quality", "Especificação*"))
        self.label_conformancedatetype.setText(_translate("quality", "Tipo de Data*"))
        self.conformanceexplanation.setPlaceholderText(_translate("quality", "Significado do Resutado..."))
        self.label_conformanceexplanation.setText(_translate("quality", "Explicação*"))
        self.label_Conformity.setText(_translate("quality", "Resultado de Conformidade"))
        self.label_conformancedate.setText(_translate("quality", "Data de Especificação*"))
        self.conformancetitle.setPlaceholderText(_translate("quality", "Título da Especificação..."))
        self.conformancedate.setDisplayFormat(_translate("quality", "yyyy-MM-dd"))
        self.label_conform.setText(_translate("quality", "Resultado Conforme?*"))
        self.btn_INSPIRE.setText(_translate("quality", "Preencher automaticamente(INSPIRE)"))
        self.label_report.setText(_translate("quality", "Relatórios"))
from qgis import gui
