# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInfobiomares/snimarQtInterfaceView/templates/serviceOperationsPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_operations(object):
    def setupUi(self, operations):
        operations.setObjectName("operations")
        operations.resize(580, 116)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(operations.sizePolicy().hasHeightForWidth())
        operations.setSizePolicy(sizePolicy)
        operations.setMinimumSize(QtCore.QSize(580, 0))
        self.gridLayout = QtWidgets.QGridLayout(operations)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.asdad = QtWidgets.QScrollArea(operations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asdad.sizePolicy().hasHeightForWidth())
        self.asdad.setSizePolicy(sizePolicy)
        self.asdad.setWidgetResizable(True)
        self.asdad.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.asdad.setObjectName("asdad")
        self.cenas = QtWidgets.QWidget()
        self.cenas.setGeometry(QtCore.QRect(0, 0, 578, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cenas.sizePolicy().hasHeightForWidth())
        self.cenas.setSizePolicy(sizePolicy)
        self.cenas.setObjectName("cenas")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cenas)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.op_box = QtWidgets.QVBoxLayout()
        self.op_box.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.op_box.setObjectName("op_box")
        self.btn_add_operations = QtWidgets.QPushButton(self.cenas)
        self.btn_add_operations.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_operations.setFont(font)
        self.btn_add_operations.setFlat(False)
        self.btn_add_operations.setObjectName("btn_add_operations")
        self.op_box.addWidget(self.btn_add_operations, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_2.addLayout(self.op_box, 0, 0, 2, 1)
        self.asdad.setWidget(self.cenas)
        self.gridLayout.addWidget(self.asdad, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(operations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.info_label_operation = QtWidgets.QPushButton(self.widget_2)
        self.info_label_operation.setMaximumSize(QtCore.QSize(28, 16777215))
        self.info_label_operation.setText("")
        self.info_label_operation.setFlat(True)
        self.info_label_operation.setObjectName("info_label_operation")
        self.horizontalLayout_2.addWidget(self.info_label_operation)
        self.label_operation = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_operation.setFont(font)
        self.label_operation.setObjectName("label_operation")
        self.horizontalLayout_2.addWidget(self.label_operation)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(operations)
        QtCore.QMetaObject.connectSlotsByName(operations)

    def retranslateUi(self, operations):
        _translate = QtCore.QCoreApplication.translate
        operations.setWindowTitle(_translate("operations", "Form"))
        self.btn_add_operations.setText(_translate("operations", "Adicionar Operação"))
        self.label_operation.setText(_translate("operations", "Operações*:"))
