# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInfobiomares/snimarQtInterfaceView/templates/temporalInformationPanel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_temporal(object):
    def setupUi(self, temporal):
        temporal.setObjectName("temporal")
        temporal.resize(996, 462)
        self.gridLayout = QtWidgets.QGridLayout(temporal)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(temporal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 994, 400))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(1100, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info_label_temporalREf = QtWidgets.QPushButton(self.widget)
        self.info_label_temporalREf.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_temporalREf.setFlat(True)
        self.info_label_temporalREf.setObjectName("info_label_temporalREf")
        self.horizontalLayout.addWidget(self.info_label_temporalREf)
        self.label_temporalREf = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_temporalREf.setFont(font)
        self.label_temporalREf.setObjectName("label_temporalREf")
        self.horizontalLayout.addWidget(self.label_temporalREf)
        self.gridLayout_4.addWidget(self.widget, 13, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(4)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_timeextension = QtWidgets.QPushButton(self.widget1)
        self.info_label_timeextension.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_timeextension.setFlat(True)
        self.info_label_timeextension.setObjectName("info_label_timeextension")
        self.horizontalLayout1.addWidget(self.info_label_timeextension)
        self.label_timeextension = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_timeextension.setFont(font)
        self.label_timeextension.setObjectName("label_timeextension")
        self.horizontalLayout1.addWidget(self.label_timeextension)
        self.gridLayout_4.addWidget(self.widget1, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.info_label_enddate = QtWidgets.QPushButton(self.widget_3)
        self.info_label_enddate.setMinimumSize(QtCore.QSize(20, 20))
        self.info_label_enddate.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_enddate.setText("")
        self.info_label_enddate.setFlat(True)
        self.info_label_enddate.setObjectName("info_label_enddate")
        self.horizontalLayout_3.addWidget(self.info_label_enddate)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.enddate = QtWidgets.QDateTimeEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enddate.sizePolicy().hasHeightForWidth())
        self.enddate.setSizePolicy(sizePolicy)
        self.enddate.setMinimumSize(QtCore.QSize(200, 30))
        self.enddate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.enddate.setCalendarPopup(True)
        self.enddate.setObjectName("enddate")
        self.horizontalLayout_3.addWidget(self.enddate)
        self.btn_clear_enddate = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_enddate.sizePolicy().hasHeightForWidth())
        self.btn_clear_enddate.setSizePolicy(sizePolicy)
        self.btn_clear_enddate.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_clear_enddate.setMaximumSize(QtCore.QSize(40, 30))
        self.btn_clear_enddate.setText("")
        self.btn_clear_enddate.setObjectName("btn_clear_enddate")
        self.horizontalLayout_3.addWidget(self.btn_clear_enddate)
        self.gridLayout_4.addWidget(self.widget_3, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 23))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 5, 0, 1, 2)
        self.widget2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_creationdate = QtWidgets.QPushButton(self.widget2)
        self.info_label_creationdate.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_creationdate.setFlat(True)
        self.info_label_creationdate.setObjectName("info_label_creationdate")
        self.horizontalLayout2.addWidget(self.info_label_creationdate)
        self.label_creationdate = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_creationdate.sizePolicy().hasHeightForWidth())
        self.label_creationdate.setSizePolicy(sizePolicy)
        self.label_creationdate.setAccessibleDescription("")
        self.label_creationdate.setObjectName("label_creationdate")
        self.horizontalLayout2.addWidget(self.label_creationdate)
        self.gridLayout_4.addWidget(self.widget2, 14, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.creationdate = QtWidgets.QDateEdit(self.widget_4)
        self.creationdate.setMinimumSize(QtCore.QSize(200, 30))
        self.creationdate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.creationdate.setCalendarPopup(True)
        self.creationdate.setObjectName("creationdate")
        self.horizontalLayout_4.addWidget(self.creationdate)
        self.btn_clear_creationdate = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_creationdate.sizePolicy().hasHeightForWidth())
        self.btn_clear_creationdate.setSizePolicy(sizePolicy)
        self.btn_clear_creationdate.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_clear_creationdate.setMaximumSize(QtCore.QSize(40, 30))
        self.btn_clear_creationdate.setText("")
        self.btn_clear_creationdate.setObjectName("btn_clear_creationdate")
        self.horizontalLayout_4.addWidget(self.btn_clear_creationdate)
        self.gridLayout_4.addWidget(self.widget_4, 16, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.info_label_begindate = QtWidgets.QPushButton(self.widget_2)
        self.info_label_begindate.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_begindate.setText("")
        self.info_label_begindate.setFlat(True)
        self.info_label_begindate.setObjectName("info_label_begindate")
        self.horizontalLayout_2.addWidget(self.info_label_begindate)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.begindate = QtWidgets.QDateTimeEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.begindate.sizePolicy().hasHeightForWidth())
        self.begindate.setSizePolicy(sizePolicy)
        self.begindate.setMinimumSize(QtCore.QSize(200, 30))
        self.begindate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.begindate.setCalendarPopup(True)
        self.begindate.setObjectName("begindate")
        self.horizontalLayout_2.addWidget(self.begindate)
        self.btn_clear_begindate = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_begindate.sizePolicy().hasHeightForWidth())
        self.btn_clear_begindate.setSizePolicy(sizePolicy)
        self.btn_clear_begindate.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_clear_begindate.setMaximumSize(QtCore.QSize(40, 30))
        self.btn_clear_begindate.setText("")
        self.btn_clear_begindate.setObjectName("btn_clear_begindate")
        self.horizontalLayout_2.addWidget(self.btn_clear_begindate)
        self.gridLayout_4.addWidget(self.widget_2, 3, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.revisiondate = QtWidgets.QDateEdit(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.revisiondate.sizePolicy().hasHeightForWidth())
        self.revisiondate.setSizePolicy(sizePolicy)
        self.revisiondate.setMinimumSize(QtCore.QSize(200, 30))
        self.revisiondate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.revisiondate.setCalendarPopup(True)
        self.revisiondate.setObjectName("revisiondate")
        self.horizontalLayout_5.addWidget(self.revisiondate)
        self.btn_clear_revisiondate = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_revisiondate.sizePolicy().hasHeightForWidth())
        self.btn_clear_revisiondate.setSizePolicy(sizePolicy)
        self.btn_clear_revisiondate.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_clear_revisiondate.setMaximumSize(QtCore.QSize(40, 30))
        self.btn_clear_revisiondate.setText("")
        self.btn_clear_revisiondate.setObjectName("btn_clear_revisiondate")
        self.horizontalLayout_5.addWidget(self.btn_clear_revisiondate)
        self.gridLayout_4.addWidget(self.widget_5, 18, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_duration = QtWidgets.QLabel(self.widget_7)
        self.label_duration.setObjectName("label_duration")
        self.horizontalLayout_6.addWidget(self.label_duration)
        self.gridLayout_4.addWidget(self.widget_7, 0, 1, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_revisiondate = QtWidgets.QPushButton(self.widget3)
        self.info_label_revisiondate.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_revisiondate.setFlat(True)
        self.info_label_revisiondate.setObjectName("info_label_revisiondate")
        self.horizontalLayout3.addWidget(self.info_label_revisiondate)
        self.label_revisiondate = QtWidgets.QLabel(self.widget3)
        self.label_revisiondate.setAccessibleDescription("")
        self.label_revisiondate.setObjectName("label_revisiondate")
        self.horizontalLayout3.addWidget(self.label_revisiondate)
        self.gridLayout_4.addWidget(self.widget3, 17, 0, 1, 1)
        self.widget4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_publicationdate = QtWidgets.QPushButton(self.widget4)
        self.info_label_publicationdate.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_publicationdate.setFlat(True)
        self.info_label_publicationdate.setObjectName("info_label_publicationdate")
        self.horizontalLayout4.addWidget(self.info_label_publicationdate)
        self.label_publicationdate = QtWidgets.QLabel(self.widget4)
        self.label_publicationdate.setObjectName("label_publicationdate")
        self.horizontalLayout4.addWidget(self.label_publicationdate)
        self.gridLayout_4.addWidget(self.widget4, 14, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_add_publicationdate = QtWidgets.QPushButton(self.widget_6)
        self.btn_add_publicationdate.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_publicationdate.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_publicationdate.setObjectName("btn_add_publicationdate")
        self.gridLayout_2.addWidget(self.btn_add_publicationdate, 2, 1, 1, 1)
        self.date_publicationdate = QtWidgets.QDateEdit(self.widget_6)
        self.date_publicationdate.setMinimumSize(QtCore.QSize(0, 30))
        self.date_publicationdate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.date_publicationdate.setCalendarPopup(True)
        self.date_publicationdate.setObjectName("date_publicationdate")
        self.gridLayout_2.addWidget(self.date_publicationdate, 2, 0, 1, 1)
        self.btn_del_publicationdate = QtWidgets.QPushButton(self.widget_6)
        self.btn_del_publicationdate.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_publicationdate.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_publicationdate.setAccessibleDescription("")
        self.btn_del_publicationdate.setObjectName("btn_del_publicationdate")
        self.gridLayout_2.addWidget(self.btn_del_publicationdate, 1, 1, 1, 1)
        self.publicationdate = QtWidgets.QListView(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.publicationdate.sizePolicy().hasHeightForWidth())
        self.publicationdate.setSizePolicy(sizePolicy)
        self.publicationdate.setMinimumSize(QtCore.QSize(0, 100))
        self.publicationdate.setMaximumSize(QtCore.QSize(16777215, 180))
        self.publicationdate.setAccessibleDescription("")
        self.publicationdate.setInputMethodHints(QtCore.Qt.ImhNone)
        self.publicationdate.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.publicationdate.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.publicationdate.setObjectName("publicationdate")
        self.gridLayout_2.addWidget(self.publicationdate, 0, 0, 2, 1)
        self.gridLayout_4.addWidget(self.widget_6, 16, 1, 4, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(temporal)
        QtCore.QMetaObject.connectSlotsByName(temporal)

    def retranslateUi(self, temporal):
        _translate = QtCore.QCoreApplication.translate
        temporal.setWindowTitle(_translate("temporal", "Form"))
        self.label_temporalREf.setText(_translate("temporal", "Referência Temporal*"))
        self.label_timeextension.setText(_translate("temporal", "Extensão Temporal"))
        self.label_2.setText(_translate("temporal", "Data de Fim :"))
        self.enddate.setDisplayFormat(_translate("temporal", "yyyy-MM-dd hh:mm:ss"))
        self.label_creationdate.setText(_translate("temporal", "Data de Criação:"))
        self.creationdate.setDisplayFormat(_translate("temporal", "yyyy-MM-dd"))
        self.label.setText(_translate("temporal", "Data de Início:"))
        self.begindate.setDisplayFormat(_translate("temporal", "yyyy-MM-dd hh:mm:ss"))
        self.revisiondate.setDisplayFormat(_translate("temporal", "yyyy-MM-dd"))
        self.label_3.setText(_translate("temporal", "Duração:"))
        self.label_duration.setText(_translate("temporal", "00000 dias, 00 horas, 00 minutos, 00 segundos"))
        self.label_revisiondate.setText(_translate("temporal", "Data da Última Revisão:"))
        self.label_publicationdate.setText(_translate("temporal", "Datas de Publicação:"))
        self.btn_add_publicationdate.setText(_translate("temporal", "+"))
        self.date_publicationdate.setDisplayFormat(_translate("temporal", "yyyy-MM-dd"))
        self.btn_del_publicationdate.setText(_translate("temporal", "-"))
