# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditorMetadadosMarswInfobiomares/snimarQtInterfaceView/templates/dialogs//contactListManagerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contacts_dialog(object):
    def setupUi(self, contacts_dialog):
        contacts_dialog.setObjectName("contacts_dialog")
        contacts_dialog.resize(1227, 661)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(contacts_dialog.sizePolicy().hasHeightForWidth())
        contacts_dialog.setSizePolicy(sizePolicy)
        contacts_dialog.setMinimumSize(QtCore.QSize(0, 0))
        contacts_dialog.setModal(False)
        self.gridLayout_9 = QtWidgets.QGridLayout(contacts_dialog)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget = QtWidgets.QWidget(contacts_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(300, 0))
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.contact_list = QtWidgets.QListWidget(self.widget)
        self.contact_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.contact_list.setObjectName("contact_list")
        self.horizontalLayout.addWidget(self.contact_list)
        self.gridLayout_9.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(contacts_dialog)
        self.widget_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_add_contact_metadata = QtWidgets.QPushButton(self.widget_2)
        self.btn_add_contact_metadata.setMinimumSize(QtCore.QSize(200, 30))
        self.btn_add_contact_metadata.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_add_contact_metadata.setAutoDefault(False)
        self.btn_add_contact_metadata.setObjectName("btn_add_contact_metadata")
        self.gridLayout.addWidget(self.btn_add_contact_metadata, 1, 0, 1, 3)
        self.btn_contact_del = QtWidgets.QPushButton(self.widget_2)
        self.btn_contact_del.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_contact_del.setAutoDefault(False)
        self.btn_contact_del.setObjectName("btn_contact_del")
        self.gridLayout.addWidget(self.btn_contact_del, 0, 2, 1, 1)
        self.btn_contact_add = QtWidgets.QPushButton(self.widget_2)
        self.btn_contact_add.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_contact_add.setAutoDefault(False)
        self.btn_contact_add.setObjectName("btn_contact_add")
        self.gridLayout.addWidget(self.btn_contact_add, 0, 0, 1, 2)
        self.gridLayout_9.addWidget(self.widget_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.contactPanel = QtWidgets.QFrame(contacts_dialog)
        self.contactPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contactPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contactPanel.setObjectName("contactPanel")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.contactPanel)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame = QtWidgets.QFrame(self.contactPanel)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_contact_save = QtWidgets.QPushButton(self.frame)
        self.btn_contact_save.setAutoDefault(False)
        self.btn_contact_save.setObjectName("btn_contact_save")
        self.horizontalLayout_2.addWidget(self.btn_contact_save)
        self.btn_cancelClose = QtWidgets.QPushButton(self.frame)
        self.btn_cancelClose.setObjectName("btn_cancelClose")
        self.horizontalLayout_2.addWidget(self.btn_cancelClose)
        self.gridLayout_10.addWidget(self.frame, 1, 0, 1, 1)
        self.contactdetails = QtWidgets.QScrollArea(self.contactPanel)
        self.contactdetails.setMinimumSize(QtCore.QSize(560, 590))
        self.contactdetails.setWidgetResizable(True)
        self.contactdetails.setObjectName("contactdetails")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 887, 740))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.info_label_name = QtWidgets.QPushButton(self.widget1)
        self.info_label_name.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_name.setFlat(True)
        self.info_label_name.setObjectName("info_label_name")
        self.horizontalLayout1.addWidget(self.info_label_name)
        self.label_name = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout1.addWidget(self.label_name)
        self.gridLayout_2.addWidget(self.widget1, 0, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setSpacing(0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.info_label_address = QtWidgets.QPushButton(self.widget2)
        self.info_label_address.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_address.setFlat(True)
        self.info_label_address.setObjectName("info_label_address")
        self.horizontalLayout2.addWidget(self.info_label_address)
        self.label_address = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_address.sizePolicy().hasHeightForWidth())
        self.label_address.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_address.setFont(font)
        self.label_address.setObjectName("label_address")
        self.horizontalLayout2.addWidget(self.label_address)
        self.gridLayout_2.addWidget(self.widget2, 8, 0, 1, 1)
        self.country = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.country.setMinimumSize(QtCore.QSize(58, 30))
        self.country.setProperty("qgisRelation", "")
        self.country.setObjectName("country")
        self.gridLayout_2.addWidget(self.country, 13, 0, 1, 2)
        self.widget3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3.setSpacing(0)
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.info_label_postalcode = QtWidgets.QPushButton(self.widget3)
        self.info_label_postalcode.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_postalcode.setFlat(True)
        self.info_label_postalcode.setObjectName("info_label_postalcode")
        self.horizontalLayout3.addWidget(self.info_label_postalcode)
        self.label_postalcode = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_postalcode.setFont(font)
        self.label_postalcode.setObjectName("label_postalcode")
        self.horizontalLayout3.addWidget(self.label_postalcode)
        self.gridLayout_2.addWidget(self.widget3, 10, 2, 1, 1)
        self.email = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.email.setMaximumSize(QtCore.QSize(16777215, 100))
        self.email.setObjectName("email")
        self.gridLayout_2.addWidget(self.email, 21, 0, 2, 3)
        self.widget4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout4 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4.setSpacing(0)
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.info_label_online = QtWidgets.QPushButton(self.widget4)
        self.info_label_online.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_online.setFlat(True)
        self.info_label_online.setObjectName("info_label_online")
        self.horizontalLayout4.addWidget(self.info_label_online)
        self.label_online = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_online.setFont(font)
        self.label_online.setObjectName("label_online")
        self.horizontalLayout4.addWidget(self.label_online)
        self.gridLayout_2.addWidget(self.widget4, 18, 0, 1, 1)
        self.btn_del_phone = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_del_phone.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_phone.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_phone.setAutoDefault(False)
        self.btn_del_phone.setObjectName("btn_del_phone")
        self.gridLayout_2.addWidget(self.btn_del_phone, 16, 1, 1, 1)
        self.phone = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.phone.setMaximumSize(QtCore.QSize(16777215, 100))
        self.phone.setObjectName("phone")
        self.gridLayout_2.addWidget(self.phone, 15, 0, 2, 1)
        self.phone_input = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.phone_input.setMinimumSize(QtCore.QSize(0, 30))
        self.phone_input.setObjectName("phone_input")
        self.gridLayout_2.addWidget(self.phone_input, 17, 0, 1, 1)
        self.btn_add_email = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_add_email.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_email.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_email.setAutoDefault(False)
        self.btn_add_email.setObjectName("btn_add_email")
        self.gridLayout_2.addWidget(self.btn_add_email, 23, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 30, 3, 1, 1)
        self.fax = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.fax.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fax.setObjectName("fax")
        self.gridLayout_2.addWidget(self.fax, 15, 2, 2, 1)
        self.widget5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget5.setObjectName("widget5")
        self.horizontalLayout5 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout5.setSpacing(0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.info_label_country = QtWidgets.QPushButton(self.widget5)
        self.info_label_country.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_country.setFlat(True)
        self.info_label_country.setObjectName("info_label_country")
        self.horizontalLayout5.addWidget(self.info_label_country)
        self.label_country = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_country.setFont(font)
        self.label_country.setObjectName("label_country")
        self.horizontalLayout5.addWidget(self.label_country)
        self.gridLayout_2.addWidget(self.widget5, 12, 0, 1, 1)
        self.btn_add_phone = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_add_phone.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_phone.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_phone.setAutoDefault(False)
        self.btn_add_phone.setObjectName("btn_add_phone")
        self.gridLayout_2.addWidget(self.btn_add_phone, 17, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 28, 3, 1, 1)
        self.name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.name.setMinimumSize(QtCore.QSize(0, 30))
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 1, 0, 1, 4)
        self.email_input = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.email_input.setMinimumSize(QtCore.QSize(0, 30))
        self.email_input.setObjectName("email_input")
        self.gridLayout_2.addWidget(self.email_input, 23, 0, 1, 3)
        self.btn_add_fax = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_add_fax.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_fax.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_fax.setIconSize(QtCore.QSize(18, 18))
        self.btn_add_fax.setAutoDefault(False)
        self.btn_add_fax.setObjectName("btn_add_fax")
        self.gridLayout_2.addWidget(self.btn_add_fax, 17, 3, 1, 1)
        self.btn_del_fax = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_del_fax.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_fax.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_fax.setAutoDefault(False)
        self.btn_del_fax.setObjectName("btn_del_fax")
        self.gridLayout_2.addWidget(self.btn_del_fax, 16, 3, 1, 1)
        self.widget6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget6.setObjectName("widget6")
        self.horizontalLayout6 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout6.setSpacing(0)
        self.horizontalLayout6.setObjectName("horizontalLayout6")
        self.info_label_fax = QtWidgets.QPushButton(self.widget6)
        self.info_label_fax.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_fax.setFlat(True)
        self.info_label_fax.setObjectName("info_label_fax")
        self.horizontalLayout6.addWidget(self.info_label_fax)
        self.label_fax = QtWidgets.QLabel(self.widget6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_fax.setFont(font)
        self.label_fax.setObjectName("label_fax")
        self.horizontalLayout6.addWidget(self.label_fax)
        self.gridLayout_2.addWidget(self.widget6, 14, 2, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2.addWidget(self.widget_4, 5, 0, 1, 4)
        self.widget7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget7.setObjectName("widget7")
        self.horizontalLayout7 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout7.setSpacing(0)
        self.horizontalLayout7.setObjectName("horizontalLayout7")
        self.info_label_email = QtWidgets.QPushButton(self.widget7)
        self.info_label_email.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_email.setFlat(True)
        self.info_label_email.setObjectName("info_label_email")
        self.horizontalLayout7.addWidget(self.info_label_email)
        self.label_email = QtWidgets.QLabel(self.widget7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.horizontalLayout7.addWidget(self.label_email)
        self.gridLayout_2.addWidget(self.widget7, 20, 0, 1, 1)
        self.widget8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget8.setObjectName("widget8")
        self.horizontalLayout8 = QtWidgets.QHBoxLayout(self.widget8)
        self.horizontalLayout8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout8.setSpacing(0)
        self.horizontalLayout8.setObjectName("horizontalLayout8")
        self.info_label_phone = QtWidgets.QPushButton(self.widget8)
        self.info_label_phone.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_phone.setFlat(True)
        self.info_label_phone.setObjectName("info_label_phone")
        self.horizontalLayout8.addWidget(self.info_label_phone)
        self.label_phone = QtWidgets.QLabel(self.widget8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_phone.setFont(font)
        self.label_phone.setObjectName("label_phone")
        self.horizontalLayout8.addWidget(self.label_phone)
        self.gridLayout_2.addWidget(self.widget8, 14, 0, 1, 1)
        self.delivery_point = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.delivery_point.setProperty("qgisRelation", "")
        self.delivery_point.setObjectName("delivery_point")
        self.gridLayout_2.addWidget(self.delivery_point, 9, 0, 1, 4)
        self.city = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.city.setMinimumSize(QtCore.QSize(58, 30))
        self.city.setProperty("qgisRelation", "")
        self.city.setObjectName("city")
        self.gridLayout_2.addWidget(self.city, 11, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 15, 1, 1, 1)
        self.btn_del_email = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_del_email.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_del_email.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_del_email.setAutoDefault(False)
        self.btn_del_email.setObjectName("btn_del_email")
        self.gridLayout_2.addWidget(self.btn_del_email, 22, 3, 1, 1)
        self.postalcode = gui.QgsFilterLineEdit(self.scrollAreaWidgetContents)
        self.postalcode.setMinimumSize(QtCore.QSize(58, 30))
        self.postalcode.setProperty("qgisRelation", "")
        self.postalcode.setObjectName("postalcode")
        self.gridLayout_2.addWidget(self.postalcode, 11, 2, 1, 1)
        self.fax_input = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fax_input.setMinimumSize(QtCore.QSize(0, 30))
        self.fax_input.setObjectName("fax_input")
        self.gridLayout_2.addWidget(self.fax_input, 17, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 21, 3, 1, 1)
        self.online = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.online.setMinimumSize(QtCore.QSize(0, 30))
        self.online.setObjectName("online")
        self.gridLayout_2.addWidget(self.online, 19, 0, 1, 3)
        self.widget9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget9.setObjectName("widget9")
        self.horizontalLayout9 = QtWidgets.QHBoxLayout(self.widget9)
        self.horizontalLayout9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout9.setSpacing(0)
        self.horizontalLayout9.setObjectName("horizontalLayout9")
        self.info_label_city = QtWidgets.QPushButton(self.widget9)
        self.info_label_city.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_city.setFlat(True)
        self.info_label_city.setObjectName("info_label_city")
        self.horizontalLayout9.addWidget(self.info_label_city)
        self.label_city = QtWidgets.QLabel(self.widget9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_city.setFont(font)
        self.label_city.setObjectName("label_city")
        self.horizontalLayout9.addWidget(self.label_city)
        self.gridLayout_2.addWidget(self.widget9, 10, 0, 1, 1)
        self.widget10 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget10.setObjectName("widget10")
        self.horizontalLayout10 = QtWidgets.QHBoxLayout(self.widget10)
        self.horizontalLayout10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout10.setSpacing(0)
        self.horizontalLayout10.setObjectName("horizontalLayout10")
        self.info_label_organization = QtWidgets.QPushButton(self.widget10)
        self.info_label_organization.setMaximumSize(QtCore.QSize(20, 20))
        self.info_label_organization.setFlat(True)
        self.info_label_organization.setObjectName("info_label_organization")
        self.horizontalLayout10.addWidget(self.info_label_organization)
        self.label_organization = QtWidgets.QLabel(self.widget10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_organization.setFont(font)
        self.label_organization.setObjectName("label_organization")
        self.horizontalLayout10.addWidget(self.label_organization)
        self.gridLayout_2.addWidget(self.widget10, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(16, 2, 0, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.combo_org = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_org.sizePolicy().hasHeightForWidth())
        self.combo_org.setSizePolicy(sizePolicy)
        self.combo_org.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_org.setObjectName("combo_org")
        self.verticalLayout.addWidget(self.combo_org)
        self.label_outra = QtWidgets.QLabel(self.frame_2)
        self.label_outra.setObjectName("label_outra")
        self.verticalLayout.addWidget(self.label_outra)
        self.organization = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.organization.sizePolicy().hasHeightForWidth())
        self.organization.setSizePolicy(sizePolicy)
        self.organization.setMinimumSize(QtCore.QSize(0, 30))
        self.organization.setObjectName("organization")
        self.verticalLayout.addWidget(self.organization)
        self.gridLayout_2.addWidget(self.frame_2, 4, 0, 1, 4)
        self.contactdetails.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.contactdetails, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.contactPanel, 0, 1, 2, 1)

        self.retranslateUi(contacts_dialog)
        QtCore.QMetaObject.connectSlotsByName(contacts_dialog)

    def retranslateUi(self, contacts_dialog):
        _translate = QtCore.QCoreApplication.translate
        contacts_dialog.setWindowTitle(_translate("contacts_dialog", "Lista de Contactos"))
        self.btn_add_contact_metadata.setText(_translate("contacts_dialog", "Adicionar ao Metadado"))
        self.btn_contact_del.setText(_translate("contacts_dialog", "Apagar"))
        self.btn_contact_add.setText(_translate("contacts_dialog", "Novo"))
        self.btn_contact_save.setText(_translate("contacts_dialog", "Guardar Alterações"))
        self.btn_cancelClose.setText(_translate("contacts_dialog", "Cancelar Alterações"))
        self.label_name.setText(_translate("contacts_dialog", "Nome"))
        self.label_address.setText(_translate("contacts_dialog", "Morada"))
        self.label_postalcode.setText(_translate("contacts_dialog", "Código Postal"))
        self.label_online.setText(_translate("contacts_dialog", "Informação Online"))
        self.btn_del_phone.setText(_translate("contacts_dialog", "-"))
        self.btn_add_email.setText(_translate("contacts_dialog", "+"))
        self.label_country.setText(_translate("contacts_dialog", "País"))
        self.btn_add_phone.setText(_translate("contacts_dialog", "+"))
        self.btn_add_fax.setText(_translate("contacts_dialog", "+"))
        self.btn_del_fax.setText(_translate("contacts_dialog", "-"))
        self.label_fax.setText(_translate("contacts_dialog", "Fax"))
        self.label_email.setText(_translate("contacts_dialog", "Endereço Eletrónico"))
        self.label_phone.setText(_translate("contacts_dialog", "Telefone"))
        self.btn_del_email.setText(_translate("contacts_dialog", "-"))
        self.label_city.setText(_translate("contacts_dialog", "Cidade"))
        self.label_organization.setText(_translate("contacts_dialog", "Nome da Organização"))
        self.label_outra.setText(_translate("contacts_dialog", "Outra (Não Listada)  "))
        self.organization.setPlaceholderText(_translate("contacts_dialog", "NomePorExtenso (SIGLA)"))
from qgis import gui
